{"variants":[{"paths":["\/documentation\/chatroomuikit\/globalboardcastview\/iglobalboardcastviewdrive-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/globalboardcastview\/iglobalboardcastviewdrive-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView\/IGlobalBoardcastViewDrive-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView\/showNewNotify(text:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IGlobalBoardcastViewDrive Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GlobalBoardcastView/showNewNotify(text:)":{"role":"symbol","title":"showNewNotify(text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Display text on received global notify message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView\/showNewNotify(text:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showNewNotifyWithText:"}],"url":"\/documentation\/chatroomuikit\/globalboardcastview\/shownewnotify(text:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GlobalBoardcastView":{"role":"symbol","title":"GlobalBoardcastView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalBoardcastView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GlobalBoardcastView"}],"url":"\/documentation\/chatroomuikit\/globalboardcastview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GlobalBoardcastView\/showNewNotify(text:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GlobalBoardcastView~1showNewNotify(text:)\/title","value":"showNewNotifyWithText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GlobalBoardcastView~1showNewNotify(text:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewNotifyWithText:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GlobalBoardcastView\/title","value":"GlobalBoardcastView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GlobalBoardcastView\/fragments","value":[{"kind":"identifier","text":"GlobalBoardcastView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}