{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatRoom-swift.typealias","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma","text":"ChatRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMutes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMuteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroommutelistdidupdate(_:addedmutedmembers:muteexpire:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroommutelistdidupdate(_:addedmutedmembers:muteexpire:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMChatroomManagerDelegate.chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}],"role":"symbol","title":"chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomServiceImplement(im)chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatroomManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement":{"role":"symbol","title":"ChatroomServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomServiceImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)":{"role":"symbol","title":"chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroommutelistdidupdate(_:addedmutedmembers:muteexpire:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatRoom-swift.typealias":{"role":"symbol","title":"ChatRoom","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatRoom"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatRoom-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatRoom"}],"url":"\/documentation\/chatroomuikit\/chatroom-swift.typealias"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/EMChatroomManagerDelegate-Implementations":{"role":"collectionGroup","title":"EMChatroomManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatroomManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/emchatroommanagerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMChatroom","preciseIdentifier":"c:objc(cs)EMChatroom"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":" "},{"kind":"identifier","text":"addedMutedMembers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aMutes"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteExpire:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aMuteExpire"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/title","value":"ChatroomServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatroomServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/title","value":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}