{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatRoom-swift.typealias","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma","text":"ChatRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona","text":"ChatroomBeKickedReason"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/diddismiss(from:reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/diddismiss(from:reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/didDismiss(from:reason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMChatroomManagerDelegate.didDismiss(from:reason:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona"},{"kind":"text","text":")"}],"title":"didDismiss(from:reason:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomServiceImplement(im)didDismissFromChatroom:reason:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"didDismissFromChatroom:reason:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatroomManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement":{"role":"symbol","title":"ChatroomServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomServiceImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomBeKickedReason":{"role":"symbol","title":"ChatroomBeKickedReason","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomBeKickedReason"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomBeKickedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomBeKickedReason"}],"url":"\/documentation\/chatroomuikit\/chatroombekickedreason"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/didDismiss(from:reason:)":{"role":"symbol","title":"didDismiss(from:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/didDismiss(from:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissFromChatroom:reason:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/diddismiss(from:reason:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/EMChatroomManagerDelegate-Implementations":{"role":"collectionGroup","title":"EMChatroomManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatroomManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/emchatroommanagerdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatRoom-swift.typealias":{"role":"symbol","title":"ChatRoom","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatRoom"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatRoom-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatRoom"}],"url":"\/documentation\/chatroomuikit\/chatroom-swift.typealias"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didDismissFromChatroom:reason:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissFromChatroom:reason:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didDismissFromChatroom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMChatroom","preciseIdentifier":"c:objc(cs)EMChatroom"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMChatroomBeKickedReason","preciseIdentifier":"c:@E@EMChatroomBeKickedReason"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aReason"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/title","value":"ChatroomServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatroomServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1didDismiss(from:reason:)\/title","value":"didDismissFromChatroom:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1didDismiss(from:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissFromChatroom:reason:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}