{"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/emchatroommanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/emchatroommanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatroomManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomAnnouncementDidUpdate(_:announcement:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/didDismiss(from:reason:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/userDidLeave(_:user:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"EMChatroomManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement":{"role":"symbol","title":"ChatroomServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomServiceImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/didDismiss(from:reason:)":{"role":"symbol","title":"didDismiss(from:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/didDismiss(from:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissFromChatroom:reason:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/diddismiss(from:reason:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/chatroomAnnouncementDidUpdate(_:announcement:)":{"role":"symbol","title":"chatroomAnnouncementDidUpdate(_:announcement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAnnouncementDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomAnnouncementDidUpdate(_:announcement:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAnnouncementDidUpdate:announcement:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroomannouncementdidupdate(_:announcement:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)":{"role":"symbol","title":"chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroommutelistdidupdate(_:addedmutedmembers:muteexpire:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/userDidLeave(_:user:)":{"role":"symbol","title":"userDidLeave(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/userDidLeave(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidLeaveChatroom:user:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/userdidleave(_:user:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/chatroomMuteListDidUpdate(_:removedMutedMembers:)":{"role":"symbol","title":"chatroomMuteListDidUpdate(_:removedMutedMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatRoom","preciseIdentifier":"s:13ChatroomUIKit8ChatRooma"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:removedMutedMembers:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroommutelistdidupdate(_:removedmutedmembers:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomAnnouncementDidUpdate(_:announcement:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/didDismiss(from:reason:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/userDidLeave(_:user:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/title","value":"ChatroomServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatroomServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1didDismiss(from:reason:)\/title","value":"didDismissFromChatroom:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1didDismiss(from:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissFromChatroom:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomAnnouncementDidUpdate(_:announcement:)\/title","value":"chatroomAnnouncementDidUpdate:announcement:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomAnnouncementDidUpdate(_:announcement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAnnouncementDidUpdate:announcement:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/title","value":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1userDidLeave(_:user:)\/title","value":"userDidLeaveChatroom:user:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1userDidLeave(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLeaveChatroom:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:removedMutedMembers:)\/title","value":"chatroomMuteListDidUpdate:removedMutedMembers:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1chatroomMuteListDidUpdate(_:removedMutedMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:removedMutedMembers:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}