{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea","text":"ChatMessage"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/messagesdidreceive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/messagesdidreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/messagesDidReceive(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMChatManagerDelegate.messagesDidReceive(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messagesDidReceive:"}],"role":"symbol","title":"messagesDidReceive(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomServiceImplement(im)messagesDidReceive:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/EMChatManagerDelegate-Implementations":{"role":"collectionGroup","title":"EMChatManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/EMChatManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/emchatmanagerdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessage":{"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"url":"\/documentation\/chatroomuikit\/chatmessage"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/messagesDidReceive(_:)":{"role":"symbol","title":"messagesDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/messagesDidReceive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesDidReceive:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/messagesdidreceive(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement":{"role":"symbol","title":"ChatroomServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomServiceImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messagesDidReceive:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidReceive:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messagesDidReceive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<EMChatMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aMessages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1messagesDidReceive(_:)\/title","value":"messagesDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1messagesDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidReceive:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/title","value":"ChatroomServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatroomServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}