{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatroomResponseListener","text":"ChatroomResponseListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ChatResponseListener"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/unbindresponse(response:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomserviceimplement\/unbindresponse(response:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/unbindResponse(response:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unbind the listener."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatroomResponseListener"},{"kind":"text","text":")"}],"title":"unbindResponse(response:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomServiceImplement(im)unbindResponseWithResponse:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"unbindResponseWithResponse:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/ChatroomService-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/ChatroomService-Implementations":{"role":"collectionGroup","title":"ChatroomService Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/ChatroomService-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/chatroomservice-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement":{"role":"symbol","title":"ChatroomServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomServiceImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener":{"role":"symbol","title":"ChatroomResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomResponseListener"}],"url":"\/documentation\/chatroomuikit\/chatroomresponselistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomServiceImplement/unbindResponse(response:)":{"role":"symbol","title":"unbindResponse(response:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatroomResponseListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unbind the listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomServiceImplement\/unbindResponse(response:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unbindResponseWithResponse:"}],"url":"\/documentation\/chatroomuikit\/chatroomserviceimplement\/unbindresponse(response:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unbindResponseWithResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindResponseWithResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unbindResponseWithResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChatroomResponseListener>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)ChatroomResponseListener"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/title","value":"ChatroomServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatroomServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/title","value":"ChatroomResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/fragments","value":[{"kind":"identifier","text":"ChatroomResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1unbindResponse(response:)\/title","value":"unbindResponseWithResponse:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomServiceImplement~1unbindResponse(response:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindResponseWithResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}