{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/bottomareatoolbaractionevents\/onkeyboardwillwakeup()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/bottomareatoolbaractionevents\/onkeyboardwillwakeup()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBarActionEvents\/onKeyboardWillWakeup()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When you tap "},{"type":"codeVoice","code":"button"},{"type":"text","text":" let’s chat callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardWillWakeup"}],"role":"symbol","title":"onKeyboardWillWakeup()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)BottomAreaToolBarActionEvents(im)onKeyboardWillWakeup","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBarActionEvents"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBarActionEvents/onKeyboardWillWakeup()":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardWillWakeup"}],"role":"symbol","title":"onKeyboardWillWakeup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"When you tap "},{"type":"codeVoice","code":"button"},{"type":"text","text":" let’s chat callback."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBarActionEvents\/onKeyboardWillWakeup()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/bottomareatoolbaractionevents\/onkeyboardwillwakeup()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBarActionEvents":{"role":"symbol","title":"BottomAreaToolBarActionEvents","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomAreaToolBarActionEvents"}],"abstract":[{"type":"text","text":"ChatBottomFunctionBar actions delegate."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBarActionEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomAreaToolBarActionEvents"}],"url":"\/documentation\/chatroomuikit\/bottomareatoolbaractionevents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onKeyboardWillWakeup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardWillWakeup"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBarActionEvents~1onKeyboardWillWakeup()\/title","value":"onKeyboardWillWakeup"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBarActionEvents~1onKeyboardWillWakeup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardWillWakeup"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBarActionEvents\/title","value":"BottomAreaToolBarActionEvents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBarActionEvents\/fragments","value":[{"kind":"identifier","text":"BottomAreaToolBarActionEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}