{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/alertviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/alertviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentedViewType","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(coder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(custom:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/presentedViewComponent"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"title":"AlertViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)AlertViewController","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController/init(custom:)":{"role":"symbol","title":"init(custom:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"custom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"AlertViewController"},{"type":"text","text":" instance with a custom view and optional constraints size."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(custom:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCustom:"}],"url":"\/documentation\/chatroomuikit\/alertviewcontroller\/init(custom:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/chatroomuikit\/alertviewcontroller\/viewdidload()"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentedViewType":{"role":"symbol","title":"PresentedViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentedViewType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentedViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentedViewType"}],"url":"\/documentation\/chatroomuikit\/presentedviewtype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit\/alertviewcontroller\/init(coder:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController":{"role":"symbol","title":"AlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}],"url":"\/documentation\/chatroomuikit\/alertviewcontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController/presentedViewComponent":{"role":"symbol","title":"presentedViewComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentedViewComponent","preciseIdentifier":"s:13ChatroomUIKit22PresentedViewComponentV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/presentedViewComponent","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/alertviewcontroller\/presentedviewcomponent"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AlertViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlertViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AlertViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(coder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/init(custom:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1init(custom:)\/title","value":"initWithCustom:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1init(custom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustom:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController\/title","value":"AlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController\/fragments","value":[{"kind":"identifier","text":"AlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}