{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/alertview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/alertview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/init(coder:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/background(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/content(content:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentAttributes(content:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentColor(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentFont(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentTextAlignment(textAlignment:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/isShowCloseButton(isShow:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(width:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonTapClosure(onTap:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(width:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonTapClosure(onTap:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(bottomDividerColor:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(leftView:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(showBottomDivider:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(text:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(placeholder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/title(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleColor(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleFont(font:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"title":"AlertView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)AlertView","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"AlertView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButton(title:)":{"role":"symbol","title":"rightButton(title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(title:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithTitle:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbutton(title:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButton(color:)":{"role":"symbol","title":"leftButton(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbutton(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/title(title:)":{"role":"symbol","title":"title(title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/title(title:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleWithTitle:"}],"url":"\/documentation\/chatroomuikit\/alertview\/title(title:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textFieldPlaceholder(color:)":{"role":"symbol","title":"textFieldPlaceholder(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldPlaceholder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldPlaceholderWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfieldplaceholder(color:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(color:)":{"role":"symbol","title":"textField(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/titleFont(font:)":{"role":"symbol","title":"titleFont(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleFont"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleFont(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleFontWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/titlefont(font:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/contentFont(font:)":{"role":"symbol","title":"contentFont(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentFont"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentFont(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentFontWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/contentfont(font:)"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textFieldPlaceholder(font:)":{"role":"symbol","title":"textFieldPlaceholder(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldPlaceholder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldPlaceholderWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfieldplaceholder(font:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButton(font:)":{"role":"symbol","title":"leftButton(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbutton(font:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButtonBackground(color:)":{"role":"symbol","title":"leftButtonBackground(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButtonBackground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBackground(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonBackgroundWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbuttonbackground(color:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButtonBorder(color:)":{"role":"symbol","title":"rightButtonBorder(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonBorderWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbuttonborder(color:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(font:)":{"role":"symbol","title":"textField(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(font:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButtonBorder(color:)":{"role":"symbol","title":"leftButtonBorder(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButtonBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonBorderWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbuttonborder(color:)"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButtonBackground(color:)":{"role":"symbol","title":"rightButtonBackground(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonBackground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBackground(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonBackgroundWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbuttonbackground(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(text:)":{"role":"symbol","title":"textField(text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(text:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithText:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(text:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/background(color:)":{"role":"symbol","title":"background(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/background(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/background(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButton(cornerRadius:)":{"role":"symbol","title":"leftButton(cornerRadius:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(cornerRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonWithCornerRadius:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbutton(cornerradius:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(bottomDividerColor:)":{"role":"symbol","title":"textField(bottomDividerColor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bottomDividerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(bottomDividerColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithBottomDividerColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(bottomdividercolor:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit\/alertview\/init(coder:)"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButton(title:)":{"role":"symbol","title":"leftButton(title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(title:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonWithTitle:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbutton(title:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButton(font:)":{"role":"symbol","title":"rightButton(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(font:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithFont:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbutton(font:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButtonTapClosure(onTap:)":{"role":"symbol","title":"leftButtonTapClosure(onTap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButtonTapClosure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onTap"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonTapClosure(onTap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonTapClosureOnTap:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbuttontapclosure(ontap:)"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(showBottomDivider:)":{"role":"symbol","title":"textField(showBottomDivider:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"showBottomDivider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(showBottomDivider:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithShowBottomDivider:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(showbottomdivider:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButtonBorder(width:)":{"role":"symbol","title":"rightButtonBorder(width:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(width:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonBorderWithWidth:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbuttonborder(width:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButton(color:)":{"role":"symbol","title":"rightButton(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbutton(color:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(leftView:)":{"role":"symbol","title":"textField(leftView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"leftView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(leftView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithLeftView:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(leftview:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/contentTextAlignment(textAlignment:)":{"role":"symbol","title":"contentTextAlignment(textAlignment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentTextAlignment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentTextAlignment(textAlignment:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentTextAlignmentWithTextAlignment:"}],"url":"\/documentation\/chatroomuikit\/alertview\/contenttextalignment(textalignment:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(cornerRadius:)":{"role":"symbol","title":"textField(cornerRadius:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(cornerRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithCornerRadius:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(cornerradius:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView":{"role":"symbol","title":"AlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"url":"\/documentation\/chatroomuikit\/alertview"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/contentColor(color:)":{"role":"symbol","title":"contentColor(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentColor(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentColorWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/contentcolor(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/leftButtonBorder(width:)":{"role":"symbol","title":"leftButtonBorder(width:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButtonBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(width:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftButtonBorderWithWidth:"}],"url":"\/documentation\/chatroomuikit\/alertview\/leftbuttonborder(width:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/isShowCloseButton(isShow:)":{"role":"symbol","title":"isShowCloseButton(isShow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowCloseButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/isShowCloseButton(isShow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}],"url":"\/documentation\/chatroomuikit\/alertview\/isshowclosebutton(isshow:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textFieldPlaceholder(placeholder:)":{"role":"symbol","title":"textFieldPlaceholder(placeholder:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldPlaceholder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(placeholder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldPlaceholderWithPlaceholder:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfieldplaceholder(placeholder:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/titleColor(color:)":{"role":"symbol","title":"titleColor(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleColor(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleColorWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/titlecolor(color:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/content(content:)":{"role":"symbol","title":"content(content:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/content(content:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentWithContent:"}],"url":"\/documentation\/chatroomuikit\/alertview\/content(content:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/contentAttributes(content:)":{"role":"symbol","title":"contentAttributes(content:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentAttributes(content:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentAttributesWithContent:"}],"url":"\/documentation\/chatroomuikit\/alertview\/contentattributes(content:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButton(cornerRadius:)":{"role":"symbol","title":"rightButton(cornerRadius:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(cornerRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithCornerRadius:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbutton(cornerradius:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/rightButtonTapClosure(onTap:)":{"role":"symbol","title":"rightButtonTapClosure(onTap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonTapClosure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onTap"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonTapClosure(onTap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightButtonTapClosureOnTap:"}],"url":"\/documentation\/chatroomuikit\/alertview\/rightbuttontapclosure(ontap:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textFieldBackground(color:)":{"role":"symbol","title":"textFieldBackground(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldBackground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldBackground(color:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldBackgroundWithColor:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfieldbackground(color:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AlertView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlertView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AlertView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/background(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/content(content:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentAttributes(content:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentColor(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentFont(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/contentTextAlignment(textAlignment:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/init(coder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/isShowCloseButton(isShow:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButton(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonBorder(width:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/leftButtonTapClosure(onTap:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButton(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonBorder(width:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/rightButtonTapClosure(onTap:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(bottomDividerColor:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(cornerRadius:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(leftView:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(showBottomDivider:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(text:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldBackground(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(font:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textFieldPlaceholder(placeholder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/title(title:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleColor(color:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/titleFont(font:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(title:)\/title","value":"rightButtonWithTitle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(title:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonWithTitle:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(color:)\/title","value":"leftButtonWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1title(title:)\/title","value":"titleWithTitle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1title(title:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleWithTitle:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(color:)\/title","value":"textFieldPlaceholderWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldPlaceholderWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(color:)\/title","value":"textFieldWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1titleFont(font:)\/title","value":"titleFontWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1titleFont(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleFontWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentFont(font:)\/title","value":"contentFontWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentFont(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentFontWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(font:)\/title","value":"textFieldPlaceholderWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldPlaceholderWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(font:)\/title","value":"leftButtonWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBackground(color:)\/title","value":"leftButtonBackgroundWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBackground(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonBackgroundWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBorder(color:)\/title","value":"rightButtonBorderWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBorder(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonBorderWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(font:)\/title","value":"textFieldWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBorder(color:)\/title","value":"leftButtonBorderWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBorder(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonBorderWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBackground(color:)\/title","value":"rightButtonBackgroundWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBackground(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonBackgroundWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(text:)\/title","value":"textFieldWithText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(text:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithText:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1background(color:)\/title","value":"backgroundWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1background(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(cornerRadius:)\/title","value":"leftButtonWithCornerRadius:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(cornerRadius:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonWithCornerRadius:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(bottomDividerColor:)\/title","value":"textFieldWithBottomDividerColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(bottomDividerColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithBottomDividerColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(title:)\/title","value":"leftButtonWithTitle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButton(title:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonWithTitle:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(font:)\/title","value":"rightButtonWithFont:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonWithFont:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonTapClosure(onTap:)\/title","value":"leftButtonTapClosureOnTap:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonTapClosure(onTap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonTapClosureOnTap:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(showBottomDivider:)\/title","value":"textFieldWithShowBottomDivider:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(showBottomDivider:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithShowBottomDivider:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBorder(width:)\/title","value":"rightButtonBorderWithWidth:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonBorder(width:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonBorderWithWidth:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(color:)\/title","value":"rightButtonWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(leftView:)\/title","value":"textFieldWithLeftView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(leftView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithLeftView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentTextAlignment(textAlignment:)\/title","value":"contentTextAlignmentWithTextAlignment:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentTextAlignment(textAlignment:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentTextAlignmentWithTextAlignment:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(cornerRadius:)\/title","value":"textFieldWithCornerRadius:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(cornerRadius:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithCornerRadius:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/fragments","value":[{"kind":"identifier","text":"AlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentColor(color:)\/title","value":"contentColorWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentColor(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentColorWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBorder(width:)\/title","value":"leftButtonBorderWithWidth:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1leftButtonBorder(width:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leftButtonBorderWithWidth:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1isShowCloseButton(isShow:)\/title","value":"isShowCloseButtonWithIsShow:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1isShowCloseButton(isShow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(placeholder:)\/title","value":"textFieldPlaceholderWithPlaceholder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldPlaceholder(placeholder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldPlaceholderWithPlaceholder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1titleColor(color:)\/title","value":"titleColorWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1titleColor(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleColorWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1content(content:)\/title","value":"contentWithContent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1content(content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentWithContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentAttributes(content:)\/title","value":"contentAttributesWithContent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1contentAttributes(content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentAttributesWithContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(cornerRadius:)\/title","value":"rightButtonWithCornerRadius:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButton(cornerRadius:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonWithCornerRadius:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonTapClosure(onTap:)\/title","value":"rightButtonTapClosureOnTap:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1rightButtonTapClosure(onTap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonTapClosureOnTap:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldBackground(color:)\/title","value":"textFieldBackgroundWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textFieldBackground(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldBackgroundWithColor:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}