{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/appearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/appearance"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"title":"Appearance","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)Appearance","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"Appearance"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/actionSheetRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/alertContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/alertCornerRadius","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/avatarPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/avatarRadius","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultMessageActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationMuteUserActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationUserActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/emojiMap","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/errorHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftAreaRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftDialogContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPriceIcon","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/identityPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/inputBarCorner","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/inputPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/maxInputHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageDisplayStyle","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageTranslationLanguage","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/mutePageSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralSpecialHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyBackgroundColor","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageIcon","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageOriginPoint","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyTextColor","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerTitleBarItemWidth","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsPageSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/primaryHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/reportTags","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/secondaryHue"]}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/avatarRadius":{"role":"symbol","title":"avatarRadius","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:13ChatroomUIKit12CornerRadiusO"}],"abstract":[{"type":"text","text":"The corner radius of the avatar image view of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/avatarRadius","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/appearance\/avatarradius"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/inputBarCorner":{"role":"symbol","title":"inputBarCorner","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBarCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:13ChatroomUIKit12CornerRadiusO"}],"abstract":[{"type":"text","text":"The corner radius of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/inputBarCorner","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/appearance\/inputbarcorner"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/errorHue":{"role":"symbol","title":"errorHue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorHue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the secondary hue. The default value is 155\/360.0."},{"type":"text","text":" "},{"type":"text","text":"After the secondary hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the chat room UIKit will also change accordingly."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/errorHue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorHue"}],"url":"\/documentation\/chatroomuikit\/appearance\/errorhue"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/appearance\/init"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/alertContainerConstraintsSize":{"role":"symbol","title":"alertContainerConstraintsSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alertContainerConstraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of alert container constraints."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/alertContainerConstraintsSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alertContainerConstraintsSize"}],"url":"\/documentation\/chatroomuikit\/appearance\/alertcontainerconstraintssize"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertViewController":{"role":"symbol","title":"AlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}],"url":"\/documentation\/chatroomuikit\/alertviewcontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemProtocol":{"role":"symbol","title":"ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/chatroomuikit\/actionsheetitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/chatroomuikit\/appearance"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/notifyMessageIcon":{"role":"symbol","title":"notifyMessageIcon","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyMessageIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The default icon of "},{"type":"codeVoice","code":"HorizontalTextCarousel"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyMessageIcon"}],"url":"\/documentation\/chatroomuikit\/appearance\/notifymessageicon"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/notifyMessageOriginPoint":{"role":"symbol","title":"notifyMessageOriginPoint","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyMessageOriginPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"The origin point of the global notification message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageOriginPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyMessageOriginPoint"}],"url":"\/documentation\/chatroomuikit\/appearance\/notifymessageoriginpoint"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/maxInputHeight":{"role":"symbol","title":"maxInputHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxInputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The height limit of the input box in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/maxInputHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxInputHeight"}],"url":"\/documentation\/chatroomuikit\/appearance\/maxinputheight"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/giftPriceIcon":{"role":"symbol","title":"giftPriceIcon","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftPriceIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The default image of the gift price of the gift list cell "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPriceIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"giftPriceIcon"}],"url":"\/documentation\/chatroomuikit\/appearance\/giftpriceicon"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEmojiConvertor":{"role":"symbol","title":"ChatEmojiConvertor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiConvertor"}],"abstract":[{"type":"text","text":"A class that converts emojis in a given NSMutableAttributedString to their corresponding UIImage."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiConvertor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatEmojiConvertor"}],"url":"\/documentation\/chatroomuikit\/chatemojiconvertor"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/mutePageSize":{"role":"symbol","title":"mutePageSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutePageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of  mute list page size."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/mutePageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mutePageSize"}],"url":"\/documentation\/chatroomuikit\/appearance\/mutepagesize"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/identityPlaceHolder":{"role":"symbol","title":"identityPlaceHolder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identityPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The placeholder image of the user-level image view of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/identityPlaceHolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identityPlaceHolder"}],"url":"\/documentation\/chatroomuikit\/appearance\/identityplaceholder"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/pageContainerTitleBarItemWidth":{"role":"symbol","title":"pageContainerTitleBarItemWidth","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerTitleBarItemWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the width of a single option with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainerTitleBar"},{"type":"text","text":" in the popup container by setting the current property."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerTitleBarItemWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}],"url":"\/documentation\/chatroomuikit\/appearance\/pagecontainertitlebaritemwidth"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/primaryHue":{"role":"symbol","title":"primaryHue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryHue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the hue of the base color, and then change the thirteen UIColor objects of the related color series. The UI components that use the relevant color series in the chat room UIKit will also change accordingly. The default value is 203\/360.0."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/primaryHue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryHue"}],"url":"\/documentation\/chatroomuikit\/appearance\/primaryhue"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView":{"role":"symbol","title":"AlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"url":"\/documentation\/chatroomuikit\/alertview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/reportTags":{"role":"symbol","title":"reportTags","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportTags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The label for message reporting types."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/reportTags","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reportTags"}],"url":"\/documentation\/chatroomuikit\/appearance\/reporttags"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/giftDialogContainerConstraintsSize":{"role":"symbol","title":"giftDialogContainerConstraintsSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftDialogContainerConstraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogContainerViewController"},{"type":"text","text":" page."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftDialogContainerConstraintsSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"giftDialogContainerConstraintsSize"}],"url":"\/documentation\/chatroomuikit\/appearance\/giftdialogcontainerconstraintssize"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/defaultMessageActions":{"role":"symbol","title":"defaultMessageActions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMessageActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"ActionSheet data source of the message being long pressed."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultMessageActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultMessageActions"}],"url":"\/documentation\/chatroomuikit\/appearance\/defaultmessageactions"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/defaultOperationUserActions":{"role":"symbol","title":"defaultOperationUserActions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultOperationUserActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"ActionSheet data source of the member list cell on click "},{"type":"codeVoice","code":"..."},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationUserActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultOperationUserActions"}],"url":"\/documentation\/chatroomuikit\/appearance\/defaultoperationuseractions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityCell":{"role":"symbol","title":"GiftEntityCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityCell"}],"abstract":[{"type":"text","text":"A UICollectionViewCell subclass that displays a gift entity with an icon, name, and price. It also has a “Send” button that triggers a callback when tapped."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityCell"}],"url":"\/documentation\/chatroomuikit\/giftentitycell"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/avatarPlaceHolder":{"role":"symbol","title":"avatarPlaceHolder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The placeholder image of the avatar image view of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/avatarPlaceHolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"avatarPlaceHolder"}],"url":"\/documentation\/chatroomuikit\/appearance\/avatarplaceholder"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/messageDisplayStyle":{"role":"symbol","title":"messageDisplayStyle","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"You can change the overall cell layout style of the chat area by setting the current properties."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageDisplayStyle"}],"url":"\/documentation\/chatroomuikit\/appearance\/messagedisplaystyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/notifyTextColor":{"role":"symbol","title":"notifyTextColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyTextColor"}],"url":"\/documentation\/chatroomuikit\/appearance\/notifytextcolor"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/neutralSpecialHue":{"role":"symbol","title":"neutralSpecialHue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralSpecialHue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the neutral special hue. The default value is 220\/360.0."},{"type":"text","text":" "},{"type":"text","text":"After the neutral special hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the relevant color series in the chat room UIKit will also change accordingly."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralSpecialHue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"neutralSpecialHue"}],"url":"\/documentation\/chatroomuikit\/appearance\/neutralspecialhue"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageInputBar":{"role":"symbol","title":"MessageInputBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageInputBar"}],"url":"\/documentation\/chatroomuikit\/messageinputbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/pageContainerConstraintsSize":{"role":"symbol","title":"pageContainerConstraintsSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerConstraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainersDialogController"},{"type":"text","text":" constraints."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerConstraintsSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageContainerConstraintsSize"}],"url":"\/documentation\/chatroomuikit\/appearance\/pagecontainerconstraintssize"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/participantsRowHeight":{"role":"symbol","title":"participantsRowHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantsRowHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The row height of the member cell."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsRowHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantsRowHeight"}],"url":"\/documentation\/chatroomuikit\/appearance\/participantsrowheight"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainersDialogController":{"role":"symbol","title":"PageContainersDialogController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainersDialogController"}],"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainersDialogController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainersDialogController"}],"url":"\/documentation\/chatroomuikit\/pagecontainersdialogcontroller"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/messageTranslationLanguage":{"role":"symbol","title":"messageTranslationLanguage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTranslationLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LanguageType","preciseIdentifier":"s:13ChatroomUIKit12LanguageTypeO"}],"abstract":[{"type":"text","text":"The mirror type of the language code of LanguageType."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/LanguageType"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageTranslationLanguage","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/appearance\/messagetranslationlanguage"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/secondaryHue":{"role":"symbol","title":"secondaryHue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryHue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the primary hue. The default value is 203\/360.0."},{"type":"text","text":" "},{"type":"text","text":"After the primary hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the chat room UIKit will also change accordingly."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/secondaryHue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryHue"}],"url":"\/documentation\/chatroomuikit\/appearance\/secondaryhue"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle":{"role":"symbol","title":"ChatMessageDisplayContentStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell":{"role":"symbol","title":"ChatMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display chat messages as a content display style of the cell."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageCell"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/notifyBackgroundColor":{"role":"symbol","title":"notifyBackgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyBackgroundColor"}],"url":"\/documentation\/chatroomuikit\/appearance\/notifybackgroundcolor"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/emojiMap":{"role":"symbol","title":"emojiMap","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Replace the emoji resource."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiConvertor"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/emojiMap","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emojiMap"}],"url":"\/documentation\/chatroomuikit\/appearance\/emojimap"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/inputPlaceHolder":{"role":"symbol","title":"inputPlaceHolder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The placeholder text in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/inputPlaceHolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inputPlaceHolder"}],"url":"\/documentation\/chatroomuikit\/appearance\/inputplaceholder"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/participantsPageSize":{"role":"symbol","title":"participantsPageSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantsPageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of chat room members that you expect to get on each page."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsPageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantsPageSize"}],"url":"\/documentation\/chatroomuikit\/appearance\/participantspagesize"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/LanguageType":{"role":"symbol","title":"LanguageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageType"}],"abstract":[{"type":"text","text":"https:\/\/learn.microsoft.com\/en-us\/azure\/ai-services\/translator\/language-support#translation"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/LanguageType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageType"}],"url":"\/documentation\/chatroomuikit\/languagetype"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/neutralHue":{"role":"symbol","title":"neutralHue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralHue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the neutral hue. The default value is 203\/360.0."},{"type":"text","text":" "},{"type":"text","text":"After the neutral hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the chat room UIKit will also change accordingly."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralHue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"neutralHue"}],"url":"\/documentation\/chatroomuikit\/appearance\/neutralhue"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/giftAreaRowHeight":{"role":"symbol","title":"giftAreaRowHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftAreaRowHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The default height of "},{"type":"codeVoice","code":"GiftBarrageCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftAreaRowHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"giftAreaRowHeight"}],"url":"\/documentation\/chatroomuikit\/appearance\/giftarearowheight"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/actionSheetRowHeight":{"role":"symbol","title":"actionSheetRowHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheetRowHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"ActionSheet row height."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/actionSheetRowHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"actionSheetRowHeight"}],"url":"\/documentation\/chatroomuikit\/appearance\/actionsheetrowheight"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/giftPlaceHolder":{"role":"symbol","title":"giftPlaceHolder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The placeholder image of the gift image view of the gift list cell "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPlaceHolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"giftPlaceHolder"}],"url":"\/documentation\/chatroomuikit\/appearance\/giftplaceholder"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/defaultOperationMuteUserActions":{"role":"symbol","title":"defaultOperationMuteUserActions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultOperationMuteUserActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"ActionSheet data source of the mute member list cell on click "},{"type":"codeVoice","code":"..."},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationMuteUserActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultOperationMuteUserActions"}],"url":"\/documentation\/chatroomuikit\/appearance\/defaultoperationmuteuseractions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/alertCornerRadius":{"role":"symbol","title":"alertCornerRadius","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alertCornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:13ChatroomUIKit12CornerRadiusO"}],"abstract":[{"type":"text","text":"The corner radius of the alert view."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/alertCornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/appearance\/alertcornerradius"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainerTitleBar":{"role":"symbol","title":"PageContainerTitleBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainerTitleBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainerTitleBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainerTitleBar"}],"url":"\/documentation\/chatroomuikit\/pagecontainertitlebar"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogContainerViewController":{"role":"symbol","title":"DialogContainerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogContainerViewController"}],"abstract":[{"type":"text","text":"A view controller that manages the presentation of a dialog container view and its content."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogContainerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DialogContainerViewController"}],"url":"\/documentation\/chatroomuikit\/dialogcontainerviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Appearance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/actionSheetRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/alertContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/avatarPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultMessageActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationMuteUserActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/defaultOperationUserActions","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/emojiMap","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/errorHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftAreaRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftDialogContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/giftPriceIcon","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/identityPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/inputPlaceHolder","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/maxInputHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageDisplayStyle","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/mutePageSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/neutralSpecialHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyBackgroundColor","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageIcon","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyMessageOriginPoint","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/notifyTextColor","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerConstraintsSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerTitleBarItemWidth","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsPageSize","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/participantsRowHeight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/primaryHue","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/reportTags","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/secondaryHue"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1errorHue\/title","value":"errorHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1errorHue\/fragments","value":[{"kind":"identifier","text":"errorHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1alertContainerConstraintsSize\/title","value":"alertContainerConstraintsSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1alertContainerConstraintsSize\/fragments","value":[{"kind":"identifier","text":"alertContainerConstraintsSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController\/title","value":"AlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertViewController\/fragments","value":[{"kind":"identifier","text":"AlertViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyMessageIcon\/title","value":"notifyMessageIcon"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyMessageIcon\/fragments","value":[{"kind":"identifier","text":"notifyMessageIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyMessageOriginPoint\/title","value":"notifyMessageOriginPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyMessageOriginPoint\/fragments","value":[{"kind":"identifier","text":"notifyMessageOriginPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1maxInputHeight\/title","value":"maxInputHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1maxInputHeight\/fragments","value":[{"kind":"identifier","text":"maxInputHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftPriceIcon\/title","value":"giftPriceIcon"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftPriceIcon\/fragments","value":[{"kind":"identifier","text":"giftPriceIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiConvertor\/title","value":"ChatEmojiConvertor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiConvertor\/fragments","value":[{"kind":"identifier","text":"ChatEmojiConvertor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1mutePageSize\/title","value":"mutePageSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1mutePageSize\/fragments","value":[{"kind":"identifier","text":"mutePageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1identityPlaceHolder\/title","value":"identityPlaceHolder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1identityPlaceHolder\/fragments","value":[{"kind":"identifier","text":"identityPlaceHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerTitleBarItemWidth\/title","value":"pageContainerTitleBarItemWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerTitleBarItemWidth\/fragments","value":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1primaryHue\/title","value":"primaryHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1primaryHue\/fragments","value":[{"kind":"identifier","text":"primaryHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/fragments","value":[{"kind":"identifier","text":"AlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1reportTags\/title","value":"reportTags"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1reportTags\/fragments","value":[{"kind":"identifier","text":"reportTags"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftDialogContainerConstraintsSize\/title","value":"giftDialogContainerConstraintsSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftDialogContainerConstraintsSize\/fragments","value":[{"kind":"identifier","text":"giftDialogContainerConstraintsSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultMessageActions\/title","value":"defaultMessageActions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultMessageActions\/fragments","value":[{"kind":"identifier","text":"defaultMessageActions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultOperationUserActions\/title","value":"defaultOperationUserActions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultOperationUserActions\/fragments","value":[{"kind":"identifier","text":"defaultOperationUserActions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCell\/title","value":"GiftEntityCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCell\/fragments","value":[{"kind":"identifier","text":"GiftEntityCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1avatarPlaceHolder\/title","value":"avatarPlaceHolder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1avatarPlaceHolder\/fragments","value":[{"kind":"identifier","text":"avatarPlaceHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1messageDisplayStyle\/title","value":"messageDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1messageDisplayStyle\/fragments","value":[{"kind":"identifier","text":"messageDisplayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyTextColor\/title","value":"notifyTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyTextColor\/fragments","value":[{"kind":"identifier","text":"notifyTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1neutralSpecialHue\/title","value":"neutralSpecialHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1neutralSpecialHue\/fragments","value":[{"kind":"identifier","text":"neutralSpecialHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageInputBar\/fragments","value":[{"kind":"identifier","text":"MessageInputBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerConstraintsSize\/title","value":"pageContainerConstraintsSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerConstraintsSize\/fragments","value":[{"kind":"identifier","text":"pageContainerConstraintsSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1participantsRowHeight\/title","value":"participantsRowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1participantsRowHeight\/fragments","value":[{"kind":"identifier","text":"participantsRowHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainersDialogController\/fragments","value":[{"kind":"identifier","text":"PageContainersDialogController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1secondaryHue\/title","value":"secondaryHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1secondaryHue\/fragments","value":[{"kind":"identifier","text":"secondaryHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/title","value":"ChatMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyBackgroundColor\/title","value":"notifyBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1notifyBackgroundColor\/fragments","value":[{"kind":"identifier","text":"notifyBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1emojiMap\/title","value":"emojiMap"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1emojiMap\/fragments","value":[{"kind":"identifier","text":"emojiMap"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1inputPlaceHolder\/title","value":"inputPlaceHolder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1inputPlaceHolder\/fragments","value":[{"kind":"identifier","text":"inputPlaceHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1participantsPageSize\/title","value":"participantsPageSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1participantsPageSize\/fragments","value":[{"kind":"identifier","text":"participantsPageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1neutralHue\/title","value":"neutralHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1neutralHue\/fragments","value":[{"kind":"identifier","text":"neutralHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftAreaRowHeight\/title","value":"giftAreaRowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftAreaRowHeight\/fragments","value":[{"kind":"identifier","text":"giftAreaRowHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1actionSheetRowHeight\/title","value":"actionSheetRowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1actionSheetRowHeight\/fragments","value":[{"kind":"identifier","text":"actionSheetRowHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftPlaceHolder\/title","value":"giftPlaceHolder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1giftPlaceHolder\/fragments","value":[{"kind":"identifier","text":"giftPlaceHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultOperationMuteUserActions\/title","value":"defaultOperationMuteUserActions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1defaultOperationMuteUserActions\/fragments","value":[{"kind":"identifier","text":"defaultOperationMuteUserActions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainerTitleBar\/title","value":"PageContainerTitleBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainerTitleBar\/fragments","value":[{"kind":"identifier","text":"PageContainerTitleBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogContainerViewController\/title","value":"DialogContainerViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogContainerViewController\/fragments","value":[{"kind":"identifier","text":"DialogContainerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}