{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chatroom user operation events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"}],"title":"ChatroomUserOperationType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChatroomUIKit@E@ChatroomUserOperationType","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/addAdministrator","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/block","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/kick","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/mute","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/removeAdministrator","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unblock","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unmute"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/Equatable-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/kick":{"role":"symbol","title":"ChatroomUserOperationType.kick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"kick"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/kick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/kick"},"doc://org.cocoapods.ChatroomUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SY"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/unmute":{"role":"symbol","title":"ChatroomUserOperationType.unmute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unmute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/unmute"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType":{"role":"symbol","title":"ChatroomUserOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"}],"abstract":[{"type":"text","text":"Chatroom user operation events."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationType"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/mute":{"role":"symbol","title":"ChatroomUserOperationType.mute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/mute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeMute"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/mute"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/removeAdministrator":{"role":"symbol","title":"ChatroomUserOperationType.removeAdministrator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAdministrator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/removeAdministrator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeRemoveAdministrator"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/removeadministrator"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/block":{"role":"symbol","title":"ChatroomUserOperationType.block","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"block"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/block","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeBlock"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/block"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/init(rawvalue:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/addAdministrator":{"role":"symbol","title":"ChatroomUserOperationType.addAdministrator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdministrator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/addAdministrator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeAddAdministrator"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/addadministrator"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/rawrepresentable-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/equatable-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/unblock":{"role":"symbol","title":"ChatroomUserOperationType.unblock","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unblock"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unblock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnblock"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/unblock"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomUserOperationType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatroomUserOperationType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/addAdministrator","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/block","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/kick","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/mute","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/removeAdministrator","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unblock","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unmute"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1kick\/title","value":"ChatroomUserOperationTypeKick"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1kick\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unmute\/title","value":"ChatroomUserOperationTypeUnmute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unmute\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/title","value":"ChatroomUserOperationType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1mute\/title","value":"ChatroomUserOperationTypeMute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1mute\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeMute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1removeAdministrator\/title","value":"ChatroomUserOperationTypeRemoveAdministrator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1removeAdministrator\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeRemoveAdministrator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1block\/title","value":"ChatroomUserOperationTypeBlock"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1block\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1addAdministrator\/title","value":"ChatroomUserOperationTypeAddAdministrator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1addAdministrator\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeAddAdministrator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unblock\/title","value":"ChatroomUserOperationTypeUnblock"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unblock\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnblock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}