{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"title":"ChatMessageDisplayContentStyle","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/all","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTime","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentity","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentityAndAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentity","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentityAndAvatar"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideTime":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideTime"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTime"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hidetime"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/init(rawvalue:)"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle":{"role":"symbol","title":"ChatMessageDisplayContentStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideTimeAndUserIdentityAndAvatar":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideTimeAndUserIdentityAndAvatar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideTimeAndUserIdentityAndAvatar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentityAndAvatar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndUserIdentityAndAvatar"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hidetimeanduseridentityandavatar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideUserIdentity":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideUserIdentity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserIdentity"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideuseridentity"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/equatable-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/all":{"role":"symbol","title":"ChatMessageDisplayContentStyle.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleAll"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/all"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SY"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideUserIdentityAndAvatar":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideUserIdentityAndAvatar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserIdentityAndAvatar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentityAndAvatar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentityAndAvatar"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideuseridentityandavatar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideTimeAndAvatar":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideTimeAndAvatar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideTimeAndAvatar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndAvatar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndAvatar"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hidetimeandavatar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideAvatar":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideAvatar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideAvatar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideAvatar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideAvatar"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideavatar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/rawrepresentable-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideTimeAndUserIdentity":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideTimeAndUserIdentity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideTimeAndUserIdentity"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndUserIdentity"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hidetimeanduseridentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/all","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTime","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentity","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideTimeAndUserIdentityAndAvatar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentity","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentityAndAvatar"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTime\/title","value":"ChatMessageDisplayContentStyleHideTime"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTime\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTime"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndUserIdentityAndAvatar\/title","value":"ChatMessageDisplayContentStyleHideTimeAndUserIdentityAndAvatar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndUserIdentityAndAvatar\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndUserIdentityAndAvatar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentity\/title","value":"ChatMessageDisplayContentStyleHideUserIdentity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentity\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1all\/title","value":"ChatMessageDisplayContentStyleAll"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1all\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleAll"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentityAndAvatar\/title","value":"ChatMessageDisplayContentStyleHideUserIdentityAndAvatar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentityAndAvatar\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentityAndAvatar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndAvatar\/title","value":"ChatMessageDisplayContentStyleHideTimeAndAvatar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndAvatar\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndAvatar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideAvatar\/title","value":"ChatMessageDisplayContentStyleHideAvatar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideAvatar\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideAvatar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndUserIdentity\/title","value":"ChatMessageDisplayContentStyleHideTimeAndUserIdentity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideTimeAndUserIdentity\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideTimeAndUserIdentity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}