{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatemojicell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatemojicell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/init(frame:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/layoutSubviews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiCell"}],"title":"ChatEmojiCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatEmojiCell","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatEmojiCell"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEmojiCell/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/chatroomuikit\/chatemojicell\/init(frame:)"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UICollectionViewCell":{"type":"unresolvable","title":"UICollectionViewCell","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UICollectionViewCell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEmojiCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/chatroomuikit\/chatemojicell\/layoutsubviews()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEmojiCell":{"role":"symbol","title":"ChatEmojiCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatEmojiCell"}],"url":"\/documentation\/chatroomuikit\/chatemojicell"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatEmojiCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatEmojiCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatEmojiCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/init(frame:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEmojiCell\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell\/title","value":"ChatEmojiCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEmojiCell\/fragments","value":[{"kind":"identifier","text":"ChatEmojiCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}