{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ChatroomView all action events delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"title":"ChatroomViewActionEventsDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)ChatroomViewActionEventsDelegate","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onExtensionBottomItemClicked(item:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onKeyboardRaiseClicked()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageBarrageClicked(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageListBarrageLongPressed(message:)"]}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate":{"role":"symbol","title":"ChatroomViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"abstract":[{"type":"text","text":"ChatroomView all action events delegate."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onKeyboardRaiseClicked()":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardRaiseClicked"}],"role":"symbol","title":"onKeyboardRaiseClicked()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardRaiseClicked"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"The method called on ChatroomView raise keyboard button clicked."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onKeyboardRaiseClicked()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onkeyboardraiseclicked()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onMessageBarrageClicked(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageBarrageClickedWithMessage:"}],"role":"symbol","title":"onMessageBarrageClicked(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageBarrageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method called on ChatroomView message barrage clicked."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageBarrageClicked(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onmessagebarrageclicked(message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onExtensionBottomItemClicked(item:)":{"navigatorTitle":[{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}],"role":"symbol","title":"onExtensionBottomItemClicked(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method called on ChatroomView extension view  item clicked that below chat barrages list ."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onExtensionBottomItemClicked(item:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onextensionbottomitemclicked(item:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onMessageListBarrageLongPressed(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageListBarrageLongPressedWithMessage:"}],"role":"symbol","title":"onMessageListBarrageLongPressed(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageListBarrageLongPressed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method called on ChatroomView message barrage long pressed."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageListBarrageLongPressed(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onmessagelistbarragelongpressed(message:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomViewActionEventsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onExtensionBottomItemClicked(item:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onKeyboardRaiseClicked()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageBarrageClicked(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onMessageListBarrageLongPressed(message:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/title","value":"ChatroomViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onKeyboardRaiseClicked()\/title","value":"onKeyboardRaiseClicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onKeyboardRaiseClicked()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardRaiseClicked"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onMessageBarrageClicked(message:)\/title","value":"onMessageBarrageClickedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onMessageBarrageClicked(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageBarrageClickedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onExtensionBottomItemClicked(item:)\/title","value":"onExtensionBottomItemClickedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onExtensionBottomItemClicked(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onMessageListBarrageLongPressed(message:)\/title","value":"onMessageListBarrageLongPressedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onMessageListBarrageLongPressed(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageListBarrageLongPressedWithMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}