{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"title":"ChatroomUIKitClient","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitClient","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/option","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomId","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomService","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/userImplement"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/destroyRoom()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/launchRoomViewWithOptions(roomId:frame:is:options:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:use:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/logout()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/refreshToken(token:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/registerRoomEventsListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/setup(with:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/unregisterRoomEventsListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/updateUserInfo(info:completion:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/shared"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/destroyRoom()":{"role":"symbol","title":"destroyRoom()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyRoom"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Free memory.Free views and service"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/destroyRoom()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destroyRoom"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/destroyroom()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/launchRoomViewWithOptions(roomId:frame:is:options:)":{"role":"symbol","title":"launchRoomViewWithOptions(roomId:frame:is:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchRoomViewWithOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"is"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitInitialOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ChatroomView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomView"}],"abstract":[{"type":"text","text":"Launch a chatroom view of ChatroomUIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/launchRoomViewWithOptions(roomId:frame:is:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"launchRoomViewWithOptionsWithRoomId:frame:is:options:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/launchroomviewwithoptions(roomid:frame:is:options:)"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/refreshToken(token:)":{"role":"symbol","title":"refreshToken(token:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When you’ll fetch new token from your app server on receive "},{"type":"codeVoice","code":"RoomEventsListener.onUserTokenWillExpired"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/refreshToken(token:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshTokenWithToken:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/refreshtoken(token:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/roomService":{"role":"symbol","title":"roomService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomService"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Chat room related protocol implementation class"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roomService"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/unregisterRoomEventsListener(listener:)":{"role":"symbol","title":"unregisterRoomEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterRoomEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unregister chatroom events listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/unregisterRoomEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterRoomEventsListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/unregisterroomeventslistener(listener:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/updateUserInfo(info:completion:)":{"role":"symbol","title":"updateUserInfo(info:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update user information.When you user the "},{"type":"codeVoice","code":"login(with user: UserInfoProtocol,token: String,use userProperties: Bool = true,completion: @escaping (ChatError?) -> Void)"},{"type":"text","text":" method login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/updateUserInfo(info:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateUserInfoWithInfo:completion:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/updateuserinfo(info:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/option":{"role":"symbol","title":"option","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitInitialOptions"}],"abstract":[{"type":"text","text":"Options function wrapper."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/option","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"option"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/option"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/login(with:token:use:completion:)":{"role":"symbol","title":"login(with:token:use:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"login"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"use"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Login method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:use:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginWith:token:use:completion:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/login(with:token:use:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/logout()":{"role":"symbol","title":"logout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Logout user"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/logout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logout"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/logout()"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener":{"role":"symbol","title":"UserStateChangedListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/chatroomuikit\/userstatechangedlistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/UserStateChangedListener-Implementations":{"role":"collectionGroup","title":"UserStateChangedListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/userstatechangedlistener-implementations"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/userImplement":{"role":"symbol","title":"userImplement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userImplement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserServiceProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"User related protocol implementation class"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/userImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userImplement"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/userimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/init"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/login(with:token:completion:)":{"role":"symbol","title":"login(with:token:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"login"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Login method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginWith:token:completion:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/login(with:token:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomUIKitClient","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitClient"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/shared"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/setup(with:)":{"role":"symbol","title":"setup(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Initialize chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/setup(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWith:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/setup(with:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/roomId":{"role":"symbol","title":"roomId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"chatroom id"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roomId"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/roomid"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/registerRoomEventsListener(listener:)":{"role":"symbol","title":"registerRoomEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerRoomEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Register chatroom events listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/registerRoomEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/registerroomeventslistener(listener:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/option","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomId","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/roomService","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/userImplement"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/destroyRoom()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/init","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/launchRoomViewWithOptions(roomId:frame:is:options:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/login(with:token:use:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/logout()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/refreshToken(token:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/registerRoomEventsListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/setup(with:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/unregisterRoomEventsListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/updateUserInfo(info:completion:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/shared"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1destroyRoom()\/title","value":"destroyRoom"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1destroyRoom()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1launchRoomViewWithOptions(roomId:frame:is:options:)\/title","value":"launchRoomViewWithOptionsWithRoomId:frame:is:options:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1launchRoomViewWithOptions(roomId:frame:is:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"launchRoomViewWithOptionsWithRoomId:frame:is:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1refreshToken(token:)\/title","value":"refreshTokenWithToken:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1refreshToken(token:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshTokenWithToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1roomService\/title","value":"roomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1roomService\/fragments","value":[{"kind":"identifier","text":"roomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1unregisterRoomEventsListener(listener:)\/title","value":"unregisterRoomEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1unregisterRoomEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterRoomEventsListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1updateUserInfo(info:completion:)\/title","value":"updateUserInfoWithInfo:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1updateUserInfo(info:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserInfoWithInfo:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1option\/title","value":"option"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1option\/fragments","value":[{"kind":"identifier","text":"option"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1login(with:token:use:completion:)\/title","value":"loginWith:token:use:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1login(with:token:use:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginWith:token:use:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1logout()\/title","value":"logout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1logout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1userImplement\/title","value":"userImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1userImplement\/fragments","value":[{"kind":"identifier","text":"userImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1login(with:token:completion:)\/title","value":"loginWith:token:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1login(with:token:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginWith:token:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1setup(with:)\/title","value":"setupWith:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1setup(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1roomId\/title","value":"roomId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1roomId\/fragments","value":[{"kind":"identifier","text":"roomId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1registerRoomEventsListener(listener:)\/title","value":"registerRoomEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1registerRoomEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}