{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomresponselistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomresponselistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onAnnouncementUpdate(roomId:announcement:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onGlobalNotifyReceived(roomId:notifyMessage:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageRecalled(roomId:message:by:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageReceived(roomId:message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserBeKicked(roomId:reason:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserJoined(roomId:message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserLeave(roomId:userId:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserMuted(roomId:userId:operatorId:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserUnmuted(roomId:userId:operatorId:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"}],"title":"ChatroomResponseListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)ChatroomResponseListener","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomResponseListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onUserBeKicked(roomId:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserBeKickedWithRoomId:reason:"}],"role":"symbol","title":"onUserBeKicked(roomId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserBeKicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user kicked out by owner."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserBeKicked(roomId:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onuserbekicked(roomid:reason:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onMessageReceived(roomId:message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageReceivedWithRoomId:message:"}],"role":"symbol","title":"onMessageReceived(roomId:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Received message from chatroom members."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageReceived(roomId:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onmessagereceived(roomid:message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onAnnouncementUpdate(roomId:announcement:)":{"navigatorTitle":[{"kind":"identifier","text":"onAnnouncementUpdateWithRoomId:announcement:"}],"role":"symbol","title":"onAnnouncementUpdate(roomId:announcement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAnnouncementUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When chatroom announcement updated.The method will called."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onAnnouncementUpdate(roomId:announcement:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onannouncementupdate(roomid:announcement:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onUserUnmuted(roomId:userId:operatorId:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:operatorId:"}],"role":"symbol","title":"onUserUnmuted(roomId:userId:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserUnmuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some room members were unmuted,then method will call notify Administrator."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserUnmuted(roomId:userId:operatorId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onuserunmuted(roomid:userid:operatorid:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener":{"role":"symbol","title":"ChatroomResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomResponseListener"}],"url":"\/documentation\/chatroomuikit\/chatroomresponselistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onGlobalNotifyReceived(roomId:notifyMessage:)":{"navigatorTitle":[{"kind":"identifier","text":"onGlobalNotifyReceivedWithRoomId:notifyMessage:"}],"role":"symbol","title":"onGlobalNotifyReceived(roomId:notifyMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGlobalNotifyReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notifyMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When admin publish global notify message,the method will called."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onGlobalNotifyReceived(roomId:notifyMessage:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onglobalnotifyreceived(roomid:notifymessage:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onUserMuted(roomId:userId:operatorId:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}],"role":"symbol","title":"onUserMuted(roomId:userId:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserMuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some room members were muted,then method will call notify Administrator."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserMuted(roomId:userId:operatorId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onusermuted(roomid:userid:operatorid:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onMessageRecalled(roomId:message:by:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageRecalledWithRoomId:message:by:"}],"role":"symbol","title":"onMessageRecalled(roomId:message:by:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageRecalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some one recall a message,the method will call."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageRecalled(roomId:message:by:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onmessagerecalled(roomid:message:by:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room hub service transfer class in chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onUserLeave(roomId:userId:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserLeaveWithRoomId:userId:"}],"role":"symbol","title":"onUserLeave(roomId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLeave"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user leave chatroom."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserLeave(roomId:userId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onuserleave(roomid:userid:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener/onUserJoined(roomId:message:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserJoinedWithRoomId:message:"}],"role":"symbol","title":"onUserJoined(roomId:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserJoined"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When a user joins a chatroom.The method carry user info for display."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserJoined(roomId:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomresponselistener\/onuserjoined(roomid:message:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomResponseListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomResponseListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatroomResponseListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onAnnouncementUpdate(roomId:announcement:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onGlobalNotifyReceived(roomId:notifyMessage:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageRecalled(roomId:message:by:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onMessageReceived(roomId:message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserBeKicked(roomId:reason:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserJoined(roomId:message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserLeave(roomId:userId:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserMuted(roomId:userId:operatorId:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener\/onUserUnmuted(roomId:userId:operatorId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserBeKicked(roomId:reason:)\/title","value":"onUserBeKickedWithRoomId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserBeKicked(roomId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserBeKickedWithRoomId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onMessageReceived(roomId:message:)\/title","value":"onMessageReceivedWithRoomId:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onMessageReceived(roomId:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageReceivedWithRoomId:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onAnnouncementUpdate(roomId:announcement:)\/title","value":"onAnnouncementUpdateWithRoomId:announcement:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onAnnouncementUpdate(roomId:announcement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAnnouncementUpdateWithRoomId:announcement:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserUnmuted(roomId:userId:operatorId:)\/title","value":"onUserUnmutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserUnmuted(roomId:userId:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/title","value":"ChatroomResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/fragments","value":[{"kind":"identifier","text":"ChatroomResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onGlobalNotifyReceived(roomId:notifyMessage:)\/title","value":"onGlobalNotifyReceivedWithRoomId:notifyMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onGlobalNotifyReceived(roomId:notifyMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGlobalNotifyReceivedWithRoomId:notifyMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserMuted(roomId:userId:operatorId:)\/title","value":"onUserMutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserMuted(roomId:userId:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onMessageRecalled(roomId:message:by:)\/title","value":"onMessageRecalledWithRoomId:message:by:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onMessageRecalled(roomId:message:by:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageRecalledWithRoomId:message:by:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserLeave(roomId:userId:)\/title","value":"onUserLeaveWithRoomId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserLeave(roomId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLeaveWithRoomId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserJoined(roomId:message:)\/title","value":"onUserJoinedWithRoomId:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener~1onUserJoined(roomId:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinedWithRoomId:message:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}