{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatbottomfunctionbar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatbottomfunctionbar"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/init(frame:datas:hiddenChat:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/removeEventHandler(actionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/IChatBottomFunctionBarDrive-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"title":"ChatBottomFunctionBar","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatBottomFunctionBar","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/IChatBottomFunctionBarDrive-Implementations":{"role":"collectionGroup","title":"IChatBottomFunctionBarDrive Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/IChatBottomFunctionBarDrive-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/ichatbottomfunctionbardrive-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/uicollectionviewdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/init(frame:datas:hiddenChat:)":{"role":"symbol","title":"init(frame:datas:hiddenChat:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"datas"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenChat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"ChatBottomBar init method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/init(frame:datas:hiddenChat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:datas:hiddenChat:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/init(frame:datas:hiddenchat:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/uicollectionviewdatasource-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar":{"role":"symbol","title":"ChatBottomFunctionBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomFunctionBar"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/addActionHandler(actionHandler:)":{"role":"symbol","title":"addActionHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomFunctionBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add UI action handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/addActionHandler(actionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/addactionhandler(actionhandler:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/ThemeSwitchProtocol-Implementations":{"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/ThemeSwitchProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ThemeSwitchProtocol":{"role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"url":"\/documentation\/chatroomuikit\/themeswitchprotocol"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive":{"role":"symbol","title":"IChatBottomFunctionBarDrive","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"abstract":[{"type":"text","text":"ChatBottomFunctionBar‘s Drive."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UICollectionViewDataSource","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDataSource"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/removeEventHandler(actionHandler:)":{"role":"symbol","title":"removeEventHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomFunctionBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove UI action handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/removeEventHandler(actionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/removeeventhandler(actionhandler:)"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UICollectionViewDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatBottomFunctionBar"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/init(frame:datas:hiddenChat:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/removeEventHandler(actionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/IChatBottomFunctionBarDrive-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/UICollectionViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICollectionViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1init(frame:datas:hiddenChat:)\/title","value":"initWithFrame:datas:hiddenChat:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1init(frame:datas:hiddenChat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:datas:hiddenChat:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/title","value":"ChatBottomFunctionBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/fragments","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1addActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/title","value":"IChatBottomFunctionBarDrive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/fragments","value":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1removeEventHandler(actionHandler:)\/title","value":"removeEventHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1removeEventHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}