{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/dialogmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/dialogmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showAlert(content:showCancel:showConfirm:title:confirmClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showGiftsDialog(titles:gifts:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showMessageActions(_:action:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showParticipantsDialog(moreClosure:muteMoreClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showReportDialog(message:errorClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showUserActions(actions:action:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/shared"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogManager"}],"title":"DialogManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)DialogManager","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"DialogManager"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager":{"role":"symbol","title":"DialogManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DialogManager"}],"url":"\/documentation\/chatroomuikit\/dialogmanager"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DialogManager","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)DialogManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/shared","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/dialogmanager\/shared"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showParticipantsDialog(moreClosure:muteMoreClosure:)":{"role":"symbol","title":"showParticipantsDialog(moreClosure:muteMoreClosure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showParticipantsDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"muteMoreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows the chat room member list page."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showParticipantsDialog(moreClosure:muteMoreClosure:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showparticipantsdialog(moreclosure:mutemoreclosure:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showUserActions(actions:action:)":{"role":"symbol","title":"showUserActions(actions:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showUserActions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionClosure","preciseIdentifier":"s:13ChatroomUIKit13ActionClosurea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows the member operation list when you click "},{"type":"codeVoice","code":"..."},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showUserActions(actions:action:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showWithUserActions:action:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showuseractions(actions:action:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showMessageActions(_:action:)":{"role":"symbol","title":"showMessageActions(_:action:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMessageActions"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionClosure","preciseIdentifier":"s:13ChatroomUIKit13ActionClosurea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows message operations."},{"type":"text","text":" "},{"type":"text","text":"Generally, message operations are shown when you long-press a message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showMessageActions(_:action:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showWithMessageActions:action:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showmessageactions(_:action:)"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showGiftsDialog(titles:gifts:)":{"role":"symbol","title":"showGiftsDialog(titles:gifts:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showGiftsDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"titles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"gifts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GiftsViewController","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftsViewController"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Shows the gift list page."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showGiftsDialog(titles:gifts:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showGiftsDialogWithTitles:gifts:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showgiftsdialog(titles:gifts:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showReportDialog(message:errorClosure:)":{"role":"symbol","title":"showReportDialog(message:errorClosure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReportDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows the message reporting page."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showReportDialog(message:errorClosure:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showReportDialogWithMessage:errorClosure:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showreportdialog(message:errorclosure:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showAlert(content:showCancel:showConfirm:title:confirmClosure:)":{"role":"symbol","title":"showAlert(content:showCancel:showConfirm:title:confirmClosure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAlert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showCancel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showConfirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmClosure"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showAlert(content:showCancel:showConfirm:title:confirmClosure:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAlertWithContent:showCancel:showConfirm:title:confirmClosure:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showalert(content:showcancel:showconfirm:title:confirmclosure:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/init"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DialogManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DialogManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DialogManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/init","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showAlert(content:showCancel:showConfirm:title:confirmClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showGiftsDialog(titles:gifts:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showMessageActions(_:action:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showParticipantsDialog(moreClosure:muteMoreClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showReportDialog(message:errorClosure:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showUserActions(actions:action:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager\/title","value":"DialogManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager\/fragments","value":[{"kind":"identifier","text":"DialogManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showParticipantsDialog(moreClosure:muteMoreClosure:)\/title","value":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showParticipantsDialog(moreClosure:muteMoreClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showUserActions(actions:action:)\/title","value":"showWithUserActions:action:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showUserActions(actions:action:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWithUserActions:action:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showMessageActions(_:action:)\/title","value":"showWithMessageActions:action:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showMessageActions(_:action:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWithMessageActions:action:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showGiftsDialog(titles:gifts:)\/title","value":"showGiftsDialogWithTitles:gifts:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showGiftsDialog(titles:gifts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showGiftsDialogWithTitles:gifts:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showReportDialog(message:errorClosure:)\/title","value":"showReportDialogWithMessage:errorClosure:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showReportDialog(message:errorClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showReportDialogWithMessage:errorClosure:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showAlert(content:showCancel:showConfirm:title:confirmClosure:)\/title","value":"showAlertWithContent:showCancel:showConfirm:title:confirmClosure:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showAlert(content:showCancel:showConfirm:title:confirmClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAlertWithContent:showCancel:showConfirm:title:confirmClosure:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}