{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityCellActionEvents"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftentitycellactionevents"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftentitycellactionevents"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCellActionEvents","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCellActionEvents\/onSendClicked(item:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityCellActionEvents"}],"title":"GiftEntityCellActionEvents","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftEntityCellActionEvents","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GiftEntityCellActionEvents"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsView":{"role":"symbol","title":"GiftsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsView"}],"url":"\/documentation\/chatroomuikit\/giftsview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityCellActionEvents/onSendClicked(item:)":{"navigatorTitle":[{"kind":"identifier","text":"onSendClickedWithItem:"}],"role":"symbol","title":"onSendClicked(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSendClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCellActionEvents\/onSendClicked(item:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftentitycellactionevents\/onsendclicked(item:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityCellActionEvents":{"role":"symbol","title":"GiftEntityCellActionEvents","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityCellActionEvents"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCellActionEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityCellActionEvents"}],"url":"\/documentation\/chatroomuikit\/giftentitycellactionevents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GiftEntityCellActionEvents"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GiftEntityCellActionEvents"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GiftEntityCellActionEvents"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityCellActionEvents\/onSendClicked(item:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityCellActionEvents"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView\/title","value":"GiftsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView\/fragments","value":[{"kind":"identifier","text":"GiftsView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCellActionEvents~1onSendClicked(item:)\/title","value":"onSendClickedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCellActionEvents~1onSendClicked(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSendClickedWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCellActionEvents\/title","value":"GiftEntityCellActionEvents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityCellActionEvents\/fragments","value":[{"kind":"identifier","text":"GiftEntityCellActionEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}