{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"GiftsView event actions delegate"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"title":"GiftsViewActionEventsDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSelected(item:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSendClick(item:)"]}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewActionEventsDelegate":{"role":"symbol","title":"GiftsViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"abstract":[{"type":"text","text":"GiftsView event actions delegate"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewActionEventsDelegate/onGiftSendClick(item:)":{"navigatorTitle":[{"kind":"identifier","text":"onGiftSendClickWithItem:"}],"role":"symbol","title":"onGiftSendClick(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send button click"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSendClick(item:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate\/ongiftsendclick(item:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewActionEventsDelegate/onGiftSelected(item:)":{"navigatorTitle":[{"kind":"identifier","text":"onGiftSelectedWithItem:"}],"role":"symbol","title":"onGiftSelected(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Select a gift item."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSelected(item:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate\/ongiftselected(item:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController":{"role":"symbol","title":"GiftsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewController"}],"url":"\/documentation\/chatroomuikit\/giftsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GiftsViewActionEventsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSelected(item:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate\/onGiftSendClick(item:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/title","value":"GiftsViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate~1onGiftSendClick(item:)\/title","value":"onGiftSendClickWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate~1onGiftSendClick(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSendClickWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate~1onGiftSelected(item:)\/title","value":"onGiftSelectedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate~1onGiftSelected(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSelectedWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/title","value":"GiftsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/fragments","value":[{"kind":"identifier","text":"GiftsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}