{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientColors"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/gradientcolors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/gradientcolors"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/gradientColors0","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors1","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors2","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors3","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors4","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors5","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors6"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientColors"}],"title":"GradientColors","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)GradientColors","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GradientColors"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors6":{"role":"symbol","title":"graduentColors6","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors6"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors6"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors6"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/gradientColors0":{"role":"symbol","title":"gradientColors0","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradientColors0"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/gradientColors0","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gradientColors0"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/gradientcolors0"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors1":{"role":"symbol","title":"graduentColors1","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors1"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors1"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors1"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors3":{"role":"symbol","title":"graduentColors3","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors3"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors3"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors3"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors4":{"role":"symbol","title":"graduentColors4","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors4"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors4"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors4"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors5":{"role":"symbol","title":"graduentColors5","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors5"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors5"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors5"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/graduentColors2":{"role":"symbol","title":"graduentColors2","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors2"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graduentColors2"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/graduentcolors2"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors":{"role":"symbol","title":"GradientColors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientColors"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GradientColors"}],"url":"\/documentation\/chatroomuikit\/gradientcolors"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientColors/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/gradientcolors\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GradientColors"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GradientColors"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GradientColors"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/gradientColors0","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors1","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors2","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors3","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors4","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors5","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientColors\/graduentColors6"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientColors"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors6\/title","value":"graduentColors6"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors6\/fragments","value":[{"kind":"identifier","text":"graduentColors6"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1gradientColors0\/title","value":"gradientColors0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1gradientColors0\/fragments","value":[{"kind":"identifier","text":"gradientColors0"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors1\/title","value":"graduentColors1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors1\/fragments","value":[{"kind":"identifier","text":"graduentColors1"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors3\/title","value":"graduentColors3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors3\/fragments","value":[{"kind":"identifier","text":"graduentColors3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors4\/title","value":"graduentColors4"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors4\/fragments","value":[{"kind":"identifier","text":"graduentColors4"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors5\/title","value":"graduentColors5"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors5\/fragments","value":[{"kind":"identifier","text":"graduentColors5"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors2\/title","value":"graduentColors2"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors~1graduentColors2\/fragments","value":[{"kind":"identifier","text":"graduentColors2"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors\/title","value":"GradientColors"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientColors\/fragments","value":[{"kind":"identifier","text":"GradientColors"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}