{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/gradientforwardpoints"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/gradientforwardpoints"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomLeftToTopRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomRightToTopLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomToTop","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/leftToRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/rightToLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topLeftToBottomRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topRightToBottomLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topToBottom"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"}],"title":"GradientForwardPoints","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)GradientForwardPoints","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GradientForwardPoints"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/rightToLeft":{"role":"symbol","title":"rightToLeft","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightToLeft"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/rightToLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightToLeft"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/righttoleft"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/topRightToBottomLeft":{"role":"symbol","title":"topRightToBottomLeft","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRightToBottomLeft"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topRightToBottomLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topRightToBottomLeft"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/toprighttobottomleft"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/bottomLeftToTopRight":{"role":"symbol","title":"bottomLeftToTopRight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeftToTopRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomLeftToTopRight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomLeftToTopRight"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/bottomlefttotopright"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints":{"role":"symbol","title":"GradientForwardPoints","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GradientForwardPoints"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/leftToRight":{"role":"symbol","title":"leftToRight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftToRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/leftToRight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftToRight"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/lefttoright"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/topLeftToBottomRight":{"role":"symbol","title":"topLeftToBottomRight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeftToBottomRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topLeftToBottomRight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topLeftToBottomRight"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/toplefttobottomright"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/bottomToTop":{"role":"symbol","title":"bottomToTop","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomToTop"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomToTop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomToTop"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/bottomtotop"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/bottomRightToTopLeft":{"role":"symbol","title":"bottomRightToTopLeft","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRightToTopLeft"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomRightToTopLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomRightToTopLeft"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/bottomrighttotopleft"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/init"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GradientForwardPoints/topToBottom":{"role":"symbol","title":"topToBottom","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topToBottom"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topToBottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topToBottom"}],"url":"\/documentation\/chatroomuikit\/gradientforwardpoints\/toptobottom"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GradientForwardPoints"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GradientForwardPoints"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GradientForwardPoints"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomLeftToTopRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomRightToTopLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/bottomToTop","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/leftToRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/rightToLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topLeftToBottomRight","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topRightToBottomLeft","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GradientForwardPoints\/topToBottom"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1rightToLeft\/title","value":"rightToLeft"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1rightToLeft\/fragments","value":[{"kind":"identifier","text":"rightToLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topRightToBottomLeft\/title","value":"topRightToBottomLeft"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topRightToBottomLeft\/fragments","value":[{"kind":"identifier","text":"topRightToBottomLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/title","value":"bottomLeftToTopRight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/fragments","value":[{"kind":"identifier","text":"bottomLeftToTopRight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints\/title","value":"GradientForwardPoints"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints\/fragments","value":[{"kind":"identifier","text":"GradientForwardPoints"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1leftToRight\/title","value":"leftToRight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1leftToRight\/fragments","value":[{"kind":"identifier","text":"leftToRight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topLeftToBottomRight\/title","value":"topLeftToBottomRight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topLeftToBottomRight\/fragments","value":[{"kind":"identifier","text":"topLeftToBottomRight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomToTop\/title","value":"bottomToTop"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomToTop\/fragments","value":[{"kind":"identifier","text":"bottomToTop"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomRightToTopLeft\/title","value":"bottomRightToTopLeft"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1bottomRightToTopLeft\/fragments","value":[{"kind":"identifier","text":"bottomRightToTopLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topToBottom\/title","value":"topToBottom"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GradientForwardPoints~1topToBottom\/fragments","value":[{"kind":"identifier","text":"topToBottom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}