{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ChatBottomFunctionBar‘s Drive."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"title":"IChatBottomFunctionBarDrive","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)IChatBottomFunctionBarDrive","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemSelectState(index:select:)"]}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive/updateItemSelectState(index:select:)":{"navigatorTitle":[{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}],"role":"symbol","title":"updateItemSelectState(index:select:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemSelectState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item select state."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemSelectState(index:select:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updateitemselectstate(index:select:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar":{"role":"symbol","title":"ChatBottomFunctionBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomFunctionBar"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive/updateItemRedDot(index:showRedDot:)":{"navigatorTitle":[{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}],"role":"symbol","title":"updateItemRedDot(index:showRedDot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemRedDot"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showRedDot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item red dot show or hidden."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemRedDot(index:showRedDot:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updateitemreddot(index:showreddot:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive":{"role":"symbol","title":"IChatBottomFunctionBarDrive","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"abstract":[{"type":"text","text":"ChatBottomFunctionBar‘s Drive."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive/updateDatas(items:)":{"navigatorTitle":[{"kind":"identifier","text":"updateDatasWithItems:"}],"role":"symbol","title":"updateDatas(items:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"You can call then method update ChatBottomFunctionBar‘s data source."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateDatas(items:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updatedatas(items:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IChatBottomFunctionBarDrive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateItemSelectState(index:select:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateItemSelectState(index:select:)\/title","value":"updateItemSelectStateWithIndex:select:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateItemSelectState(index:select:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/title","value":"ChatBottomFunctionBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/fragments","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateItemRedDot(index:showRedDot:)\/title","value":"updateItemRedDotWithIndex:showRedDot:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateItemRedDot(index:showRedDot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/title","value":"IChatBottomFunctionBarDrive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/fragments","value":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateDatas(items:)\/title","value":"updateDatasWithItems:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateDatas(items:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDatasWithItems:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}