{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The PageContainerTitleBar displays a list of choices that correspond to the view controllers managed by the UIPageViewController."},{"type":"text","text":" "},{"type":"text","text":"The UIPageViewController displays the view controllers that correspond to the selected choice in the PageContainerTitleBar."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/pagecontainer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/pagecontainer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"title":"PageContainer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)PageContainer","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/init(frame:viewControllers:indicators:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPageViewControllerDataSource":{"type":"unresolvable","title":"UIPageViewControllerDataSource","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDataSource"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/UIPageViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIPageViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/init(frame:viewControllers:indicators:)":{"role":"symbol","title":"init(frame:viewControllers:indicators:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"indicators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A convenience initializer for creating a "},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":" with a given frame, view controllers, and indicators."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/init(frame:viewControllers:indicators:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}],"url":"\/documentation\/chatroomuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"role":"collectionGroup","title":"UIPageViewControllerDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer":{"role":"symbol","title":"PageContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"url":"\/documentation\/chatroomuikit\/pagecontainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ThemeSwitchProtocol":{"role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"url":"\/documentation\/chatroomuikit\/themeswitchprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/ThemeSwitchProtocol-Implementations":{"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/ThemeSwitchProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/pagecontainer\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPageViewControllerDelegate":{"type":"unresolvable","title":"UIPageViewControllerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PageContainer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/init(frame:viewControllers:indicators:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPageViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/title","value":"initWithFrame:viewControllers:indicators:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}