{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This class is a subclass of "},{"type":"codeVoice","code":"UIPresentationController"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"FILEPATH"}]}],"type":"aside","name":"Author"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/presentationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/presentationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)PresentationController","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/init(presentedViewController:presenting:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/frameOfPresentedViewInContainerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionWillBegin()"]}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController":{"role":"symbol","title":"PresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"abstract":[{"type":"text","text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/frameOfPresentedViewInContainerView":{"role":"symbol","title":"frameOfPresentedViewInContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/frameOfPresentedViewInContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/frameofpresentedviewincontainerview"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/presentationTransitionWillBegin()":{"role":"symbol","title":"presentationTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"将要弹出时添加背景按钮"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/presentationtransitionwillbegin()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/presentationTransitionDidEnd(_:)":{"role":"symbol","title":"presentationTransitionDidEnd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionDidEnd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"已经弹出视图"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionDidEnd:"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/presentationtransitiondidend(_:)"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIPresentationController":{"type":"unresolvable","title":"UIPresentationController","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIPresentationController"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/dismissalTransitionWillBegin()":{"role":"symbol","title":"dismissalTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissalTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissalTransitionWillBegin"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/dismissaltransitionwillbegin()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/init(presentedViewController:presenting:)":{"role":"symbol","title":"init(presentedViewController:presenting:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"presentedViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/init(presentedViewController:presenting:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationController/dismissalTransitionDidEnd(_:)":{"role":"symbol","title":"dismissalTransitionDidEnd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissalTransitionDidEnd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissalTransitionDidEnd:"}],"url":"\/documentation\/chatroomuikit\/presentationcontroller\/dismissaltransitiondidend(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PresentationController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/frameOfPresentedViewInContainerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/init(presentedViewController:presenting:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationController\/presentationTransitionWillBegin()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController\/title","value":"PresentationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController\/fragments","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/title","value":"frameOfPresentedViewInContainerView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/fragments","value":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1presentationTransitionWillBegin()\/title","value":"presentationTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1presentationTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/title","value":"presentationTransitionDidEnd:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionDidEnd:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1dismissalTransitionWillBegin()\/title","value":"dismissalTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1dismissalTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissalTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1init(presentedViewController:presenting:)\/title","value":"initWithPresentedViewController:presentingViewController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1init(presentedViewController:presenting:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/title","value":"dismissalTransitionDidEnd:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissalTransitionDidEnd:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}