{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/presentationanimation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/presentationanimation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/FlipHorizontalAnimation"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/init(options:origin:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/options","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/origin"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/performAnimation(animationContext:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"title":"PresentationAnimation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)PresentationAnimation","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/FlipHorizontalAnimation":{"role":"symbol","title":"FlipHorizontalAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlipHorizontalAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/FlipHorizontalAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlipHorizontalAnimation"}],"url":"\/documentation\/chatroomuikit\/fliphorizontalanimation"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/init(options:origin:)":{"role":"symbol","title":"init(options:origin:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"s:13ChatroomUIKit16AnimationOptionsO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationOrigin","preciseIdentifier":"s:13ChatroomUIKit18PresentationOriginO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/init(options:origin:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/init(options:origin:)"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/CrossZoomAnimation":{"role":"symbol","title":"CrossZoomAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CrossZoomAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossZoomAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CrossZoomAnimation"}],"url":"\/documentation\/chatroomuikit\/crosszoomanimation"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/UIViewControllerAnimatedTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/afterAnimation(animationContext:)":{"role":"symbol","title":"afterAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13ChatroomUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"动画完成后（做动画完成的清理工作，子类可覆写）"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/afteranimation(animationcontext:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/beforeAnimation(animationContext:)":{"role":"symbol","title":"beforeAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beforeAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13ChatroomUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/beforeanimation(animationcontext:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIViewControllerAnimatedTransitioning":{"type":"unresolvable","title":"UIViewControllerAnimatedTransitioning","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/origin":{"role":"symbol","title":"origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationOrigin","preciseIdentifier":"s:13ChatroomUIKit18PresentationOriginO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/origin","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/origin"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/CrossDissolveAnimation":{"role":"symbol","title":"CrossDissolveAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CrossDissolveAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossDissolveAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CrossDissolveAnimation"}],"url":"\/documentation\/chatroomuikit\/crossdissolveanimation"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/transformInitialFrame(containerFrame:finalFrame:)":{"role":"symbol","title":"transformInitialFrame(containerFrame:finalFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformInitialFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containerFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finalFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/transforminitialframe(containerframe:finalframe:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"s:13ChatroomUIKit16AnimationOptionsO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/options","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/options"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation":{"role":"symbol","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}],"url":"\/documentation\/chatroomuikit\/presentationanimation"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PresentationAnimation/performAnimation(animationContext:)":{"role":"symbol","title":"performAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13ChatroomUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/performAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/presentationanimation\/performanimation(animationcontext:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/FlipHorizontalAnimation"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1FlipHorizontalAnimation\/title","value":"FlipHorizontalAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1FlipHorizontalAnimation\/fragments","value":[{"kind":"identifier","text":"FlipHorizontalAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1CrossZoomAnimation\/title","value":"CrossZoomAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1CrossZoomAnimation\/fragments","value":[{"kind":"identifier","text":"CrossZoomAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1CrossDissolveAnimation\/title","value":"CrossDissolveAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1CrossDissolveAnimation\/fragments","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationAnimation\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PresentationAnimation\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}