{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/reportoptioncell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/reportoptioncell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(coder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(style:reuseIdentifier:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/normalImage","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/selectImage"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/layoutSubviews()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/refresh(select:title:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/ThemeSwitchProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionCell"}],"title":"ReportOptionCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ReportOptionCell","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ReportOptionCell"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/ThemeSwitchProtocol-Implementations":{"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/ThemeSwitchProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptioncell\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/normalImage":{"role":"symbol","title":"normalImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/normalImage","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptioncell\/normalimage"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIGestureRecognizerDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell":{"role":"symbol","title":"ReportOptionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportOptionCell"}],"url":"\/documentation\/chatroomuikit\/reportoptioncell"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/refresh(select:title:)":{"role":"symbol","title":"refresh(select:title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Refresh report option select state."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/refresh(select:title:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshWithSelect:title:"}],"url":"\/documentation\/chatroomuikit\/reportoptioncell\/refresh(select:title:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit\/reportoptioncell\/init(coder:)"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UITableViewCell"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ThemeSwitchProtocol":{"role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"url":"\/documentation\/chatroomuikit\/themeswitchprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/chatroomuikit\/reportoptioncell\/layoutsubviews()"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/selectImage":{"role":"symbol","title":"selectImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/selectImage","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptioncell\/selectimage"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionCell/init(style:reuseIdentifier:)":{"role":"symbol","title":"init(style:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(style:reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/chatroomuikit\/reportoptioncell\/init(style:reuseidentifier:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ReportOptionCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReportOptionCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ReportOptionCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(coder:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/init(style:reuseIdentifier:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/layoutSubviews()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/refresh(select:title:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionCell\/ThemeSwitchProtocol-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell\/title","value":"ReportOptionCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell\/fragments","value":[{"kind":"identifier","text":"ReportOptionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1refresh(select:title:)\/title","value":"refreshWithSelect:title:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1refresh(select:title:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithSelect:title:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionCell~1init(style:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}