{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionsController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/reportoptionscontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/reportoptionscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH","doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/init(message:completion:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/items","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/reportMessage","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/selectIndex"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionsController"}],"title":"ReportOptionsController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ReportOptionsController","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ReportOptionsController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/initwithcoder:"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UITableViewDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ChatroomUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s8SendableP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/uitableviewdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDataSource"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/reportMessage":{"role":"symbol","title":"reportMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/reportMessage","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/reportmessage"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController":{"role":"symbol","title":"ReportOptionsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionsController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportOptionsController"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/items":{"role":"symbol","title":"items","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/items","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/items"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ThemeSwitchProtocol":{"role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"url":"\/documentation\/chatroomuikit\/themeswitchprotocol"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/selectIndex":{"role":"symbol","title":"selectIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/selectIndex","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/selectindex"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/viewdidload()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/initwithnibname:bundle:"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/init(message:completion:)":{"role":"symbol","title":"init(message:completion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Init method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/init(message:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:completion:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/init(message:completion:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/ThemeSwitchProtocol-Implementations":{"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/ThemeSwitchProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/uitableviewdatasource-implementations"},"doc://org.cocoapods.ChatroomUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ReportOptionsController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReportOptionsController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ReportOptionsController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/init(message:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/initWithCoder:","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/initWithNibName:bundle:","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionsController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController\/title","value":"ReportOptionsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController\/fragments","value":[{"kind":"identifier","text":"ReportOptionsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1init(message:completion:)\/title","value":"initWithMessage:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1init(message:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}