{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chat room request & response wrapper class in the chat room UIKit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"title":"RoomService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)RoomService","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"RoomService"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/init(roomId:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/chatDrive","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/eventsListener","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftDrive","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftService","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/notifyDrive","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/pageNum","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/pageNumOfMute","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/roomId","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/roomService"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/destroyed(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/enterRoom(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchMuteUsers(pageSize:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchParticipants(pageSize:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/kick(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/leaveRoom(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/mute(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/recall(message:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/registerListener(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/report(message:tag:reason:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/translate(message:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unmute(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unregisterListener(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/ChatroomResponseListener-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/GiftResponseListener-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/chatDrive":{"role":"symbol","title":"chatDrive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IMessageListDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IMessageListDrive"},{"kind":"text","text":"?"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView"},{"type":"text","text":"  UI Drive."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/chatDrive","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/chatdrive"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/recall(message:completion:)":{"role":"symbol","title":"recall(message:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/recall(message:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recallWithMessage:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/recall(message:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/translate(message:completion:)":{"role":"symbol","title":"translate(message:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"translate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/translate(message:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translateWithMessage:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/translate(message:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/giftDrive":{"role":"symbol","title":"giftDrive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGiftMessageListDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftMessageListDrive"},{"kind":"text","text":"?"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageList"},{"type":"text","text":" UI Drive"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftDrive","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/giftdrive"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/report(message:tag:reason:completion:)":{"role":"symbol","title":"report(message:tag:reason:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"report"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/report(message:tag:reason:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reportWithMessage:tag:reason:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/report(message:tag:reason:completion:)"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/roomService":{"role":"symbol","title":"roomService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatroomService"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/roomService","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/pageNum":{"role":"symbol","title":"pageNum","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The current page number for getting chat room participants."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/pageNum","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/pagenum"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/kick(userId:completion:)":{"role":"symbol","title":"kick(userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"kick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/kick(userId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kickUserWithId:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/kick(userid:completion:)"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/pageNumOfMute":{"role":"symbol","title":"pageNumOfMute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNumOfMute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/pageNumOfMute","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/pagenumofmute"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/fetchMuteUsers(pageSize:completion:)":{"role":"symbol","title":"fetchMuteUsers(pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMuteUsers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchMuteUsers(pageSize:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchMuteUsersWithPageSize:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/fetchmuteusers(pagesize:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomResponseListener":{"role":"symbol","title":"ChatroomResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomResponseListener"}],"url":"\/documentation\/chatroomuikit\/chatroomresponselistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/fetchParticipants(pageSize:completion:)":{"role":"symbol","title":"fetchParticipants(pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchParticipants"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchParticipants(pageSize:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchParticipantsWithPageSize:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/fetchparticipants(pagesize:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/eventsListener":{"role":"symbol","title":"eventsListener","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventsListener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"The chat room events listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/eventsListener","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/eventslistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/GiftResponseListener-Implementations":{"role":"collectionGroup","title":"GiftResponseListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/GiftResponseListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/giftresponselistener-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/mute(userId:completion:)":{"role":"symbol","title":"mute(userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/mute(userId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteUserWithId:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/mute(userid:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageList":{"role":"symbol","title":"GiftMessageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageList"}],"url":"\/documentation\/chatroomuikit\/giftmessagelist"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)":{"role":"symbol","title":"fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchThenCacheUserInfosOnEndScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"unknownUserIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Fetch user infos on participants list end scroll,Then cache user info"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchThenCacheUserInfosOnEndScrollWithunknownUserIds:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/fetchthencacheuserinfosonendscroll(unknownuserids:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/ChatroomResponseListener-Implementations":{"role":"collectionGroup","title":"ChatroomResponseListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/ChatroomResponseListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/chatroomresponselistener-implementations"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/enterRoom(completion:)":{"role":"symbol","title":"enterRoom(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterRoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/enterRoom(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterRoomWithCompletion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/enterroom(completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room request & response wrapper class in the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/unmute(userId:completion:)":{"role":"symbol","title":"unmute(userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unmute(userId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmuteUserWithId:completion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/unmute(userid:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/roomId":{"role":"symbol","title":"roomId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Current chat room ID."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/roomId","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/roomid"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/giftService":{"role":"symbol","title":"giftService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftService"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftService","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/giftservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/registerListener(_:)":{"role":"symbol","title":"registerListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Registers an event listener in the chat room."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/registerListener(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerListener:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/registerlistener(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/unregisterListener(_:)":{"role":"symbol","title":"unregisterListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unregisters an event listener in the chat room."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unregisterListener(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterListener:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/unregisterlistener(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/destroyed(completion:)":{"role":"symbol","title":"destroyed(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/destroyed(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destroyedWithCompletion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/destroyed(completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftResponseListener":{"role":"symbol","title":"GiftResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftResponseListener"}],"url":"\/documentation\/chatroomuikit\/giftresponselistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/init(roomId:)":{"role":"symbol","title":"init(roomId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/init(roomId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRoomId:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/init(roomid:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/notifyDrive":{"role":"symbol","title":"notifyDrive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGlobalBoardcastViewDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGlobalBoardcastViewDrive"},{"kind":"text","text":"?"}],"abstract":[{"type":"codeVoice","code":"HorizontalTextCarousel"},{"type":"text","text":" UI Drive"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/notifyDrive","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/notifydrive"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/leaveRoom(completion:)":{"role":"symbol","title":"leaveRoom(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveRoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/leaveRoom(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveRoomWithCompletion:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/leaveroom(completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RoomService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/destroyed(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/enterRoom(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchMuteUsers(pageSize:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchParticipants(pageSize:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/init(roomId:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/kick(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/leaveRoom(completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/mute(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/recall(message:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/registerListener(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/report(message:tag:reason:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/translate(message:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unmute(userId:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/unregisterListener(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/ChatroomResponseListener-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/GiftResponseListener-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomResponseListener","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1recall(message:completion:)\/title","value":"recallWithMessage:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1recall(message:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recallWithMessage:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1translate(message:completion:)\/title","value":"translateWithMessage:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1translate(message:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"translateWithMessage:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1report(message:tag:reason:completion:)\/title","value":"reportWithMessage:tag:reason:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1report(message:tag:reason:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportWithMessage:tag:reason:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1kick(userId:completion:)\/title","value":"kickUserWithId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1kick(userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"kickUserWithId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchMuteUsers(pageSize:completion:)\/title","value":"fetchMuteUsersWithPageSize:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchMuteUsers(pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchMuteUsersWithPageSize:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/title","value":"ChatroomResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomResponseListener\/fragments","value":[{"kind":"identifier","text":"ChatroomResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchParticipants(pageSize:completion:)\/title","value":"fetchParticipantsWithPageSize:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchParticipants(pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchParticipantsWithPageSize:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1mute(userId:completion:)\/title","value":"muteUserWithId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1mute(userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteUserWithId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageList\/title","value":"GiftMessageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageList\/fragments","value":[{"kind":"identifier","text":"GiftMessageList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)\/title","value":"fetchThenCacheUserInfosOnEndScrollWithunknownUserIds:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1fetchThenCacheUserInfosOnEndScroll(unknownUserIds:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchThenCacheUserInfosOnEndScrollWithunknownUserIds:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1enterRoom(completion:)\/title","value":"enterRoomWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1enterRoom(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enterRoomWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1unmute(userId:completion:)\/title","value":"unmuteUserWithId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1unmute(userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmuteUserWithId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1registerListener(_:)\/title","value":"registerListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1registerListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1unregisterListener(_:)\/title","value":"unregisterListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1unregisterListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1destroyed(completion:)\/title","value":"destroyedWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1destroyed(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyedWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/title","value":"GiftResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/fragments","value":[{"kind":"identifier","text":"GiftResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1init(roomId:)\/title","value":"initWithRoomId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1init(roomId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRoomId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1leaveRoom(completion:)\/title","value":"leaveRoomWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1leaveRoom(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveRoomWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}