{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/userstatechangedlistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/userstatechangedlistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenWillExpired()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"title":"UserStateChangedListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)UserStateChangedListener","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener/onSocketConnectionStateChanged(state:)":{"navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}],"role":"symbol","title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Chatroom socket connection state changed listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/userstatechangedlistener\/onsocketconnectionstatechanged(state:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener":{"role":"symbol","title":"UserStateChangedListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/chatroomuikit\/userstatechangedlistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener/onUserTokenWillExpired()":{"navigatorTitle":[{"kind":"identifier","text":"onUserTokenWillExpired"}],"role":"symbol","title":"onUserTokenWillExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenWillExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"User token will expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenWillExpired()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/userstatechangedlistener\/onusertokenwillexpired()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener/onUserTokenDidExpired()":{"navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"role":"symbol","title":"onUserTokenDidExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenDidExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"User token expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/userstatechangedlistener\/onusertokendidexpired()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener/onUserLoginOtherDevice(device:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"role":"symbol","title":"onUserLoginOtherDevice(device:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"User login at other device"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"UserStateChangedListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener\/onUserTokenWillExpired()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onSocketConnectionStateChanged(state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserTokenWillExpired()\/title","value":"onUserTokenWillExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserTokenWillExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenWillExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}