{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanMessages"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/ichatbarragelistdrive\/cleanmessages()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/ichatbarragelistdrive\/cleanmessages()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBarrageListDrive\/cleanMessages()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clean data source."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cleanMessages"}],"role":"symbol","title":"cleanMessages()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanMessages"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)IChatBarrageListDrive(im)cleanMessages","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBarrageListDrive"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBarrageListDrive":{"role":"symbol","title":"IChatBarrageListDrive","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBarrageListDrive"}],"abstract":[{"type":"text","text":"ChatBarrageList’s Drive."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBarrageListDrive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IChatBarrageListDrive"}],"url":"\/documentation\/chatroomuikit\/ichatbarragelistdrive"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBarrageListDrive/cleanMessages()":{"navigatorTitle":[{"kind":"identifier","text":"cleanMessages"}],"role":"symbol","title":"cleanMessages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanMessages"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clean data source."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBarrageListDrive\/cleanMessages()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/ichatbarragelistdrive\/cleanmessages()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cleanMessages"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanMessages"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cleanMessages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBarrageListDrive\/title","value":"IChatBarrageListDrive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBarrageListDrive\/fragments","value":[{"kind":"identifier","text":"IChatBarrageListDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBarrageListDrive~1cleanMessages()\/title","value":"cleanMessages"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBarrageListDrive~1cleanMessages()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanMessages"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}