{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UserStateChangedListener"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bind user state changed listener"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"title":"bindUserStateChangedListener(listener:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)UserServiceImplement(im)bindUserStateChangedListenerWithListener:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/bindUserStateChangedListener(listener:)":{"role":"symbol","title":"bindUserStateChangedListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/UserServiceProtocol-Implementations":{"role":"collectionGroup","title":"UserServiceProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/userserviceimplement\/userserviceprotocol-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserStateChangedListener":{"role":"symbol","title":"UserStateChangedListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserStateChangedListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/chatroomuikit\/userstatechangedlistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement":{"role":"symbol","title":"UserServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bindUserStateChangedListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UserStateChangedListener>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/title","value":"bindUserStateChangedListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}