{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea","text":"ConnectionState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/connectionstatedidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/connectionstatedidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMClientDelegate.connectionStateDidChange(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"title":"connectionStateDidChange(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)UserServiceImplement(im)connectionStateDidChange:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/EMClientDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/connectionStateDidChange(_:)":{"role":"symbol","title":"connectionStateDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/connectionstatedidchange(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement":{"role":"symbol","title":"UserServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/EMClientDelegate-Implementations":{"role":"collectionGroup","title":"EMClientDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/EMClientDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/userserviceimplement\/emclientdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ConnectionState":{"role":"symbol","title":"ConnectionState","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionState"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionState"}],"url":"\/documentation\/chatroomuikit\/connectionstate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"connectionStateDidChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectionStateDidChange:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"connectionStateDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMConnectionState","preciseIdentifier":"c:@E@EMConnectionState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aConnectionState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/title","value":"connectionStateDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectionStateDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}