{"variants":[{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/emclientdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/userserviceimplement\/emclientdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/EMClientDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userDidForbidByServer()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"EMClientDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/userAccountDidRemoveFromServer()":{"role":"symbol","title":"userAccountDidRemoveFromServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/useraccountdidremovefromserver()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/connectionStateDidChange(_:)":{"role":"symbol","title":"connectionStateDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/connectionstatedidchange(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/userDidForbidByServer()":{"role":"symbol","title":"userDidForbidByServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userDidForbidByServer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidForbidByServer"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/userdidforbidbyserver()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/userAccountDidForced(toLogout:)":{"role":"symbol","title":"userAccountDidForced(toLogout:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForced"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toLogout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/useraccountdidforced(tologout:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/tokenWillExpire(_:)":{"role":"symbol","title":"tokenWillExpire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenWillExpire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatErrorCode","preciseIdentifier":"s:13ChatroomUIKit13ChatErrorCodea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenWillExpire(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenWillExpire:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/tokenwillexpire(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/userAccountDidLogin(fromOtherDevice:)":{"role":"symbol","title":"userAccountDidLogin(fromOtherDevice:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidLogin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromOtherDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement/tokenDidExpire(_:)":{"role":"symbol","title":"tokenDidExpire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenDidExpire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatErrorCode","preciseIdentifier":"s:13ChatroomUIKit13ChatErrorCodea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenDidExpire(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenDidExpire:"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement\/tokendidexpire(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserServiceImplement":{"role":"symbol","title":"UserServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/chatroomuikit\/userserviceimplement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserServiceImplement\/userDidForbidByServer()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/title","value":"userAccountDidRemoveFromServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/title","value":"connectionStateDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectionStateDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userDidForbidByServer()\/title","value":"userDidForbidByServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userDidForbidByServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidForbidByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/title","value":"userAccountDidForcedToLogout:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidForcedToLogout:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/title","value":"tokenWillExpire:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenWillExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/title","value":"userAccountDidLoginFromOtherDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/title","value":"tokenDidExpire:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenDidExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}