use_frameworks!

platform :ios, '11.0'

target 'ChatroomUIKit_Example' do
  pod 'ChatroomUIKit', :path => '../'
    post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
            config.build_settings["DEVELOPMENT_TEAM"] = "JC854K845H"
          end
        end
      end
    end
end
