{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol","text":"ChatBottomItemProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The item conform "},{"type":"codeVoice","code":"ChatBottomItemProtocol"},{"type":"text","text":" instance."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onextensionbottomitemclicked(item:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onextensionbottomitemclicked(item:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onExtensionBottomItemClicked(item:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method called on ChatroomView extension view  item clicked that below chat barrages list ."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}],"role":"symbol","title":"onExtensionBottomItemClicked(item:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)ChatroomViewActionEventsDelegate(im)onExtensionBottomItemClickedWithItem:","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate":{"role":"symbol","title":"ChatroomViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"abstract":[{"type":"text","text":"ChatroomView all action events delegate."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomItemProtocol":{"role":"symbol","title":"ChatBottomItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItemProtocol"}],"abstract":[{"type":"text","text":"ChatBottomBar item protocol"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItemProtocol"}],"url":"\/documentation\/chatroomuikit\/chatbottomitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onExtensionBottomItemClicked(item:)":{"navigatorTitle":[{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}],"role":"symbol","title":"onExtensionBottomItemClicked(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method called on ChatroomView extension view  item clicked that below chat barrages list ."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onExtensionBottomItemClicked(item:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onextensionbottomitemclicked(item:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onExtensionBottomItemClickedWithItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChatBottomItemProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/title","value":"ChatroomViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/title","value":"ChatBottomItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/fragments","value":[{"kind":"identifier","text":"ChatBottomItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onExtensionBottomItemClicked(item:)\/title","value":"onExtensionBottomItemClickedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onExtensionBottomItemClicked(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionBottomItemClickedWithItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}