{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardRaiseClicked"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onkeyboardraiseclicked()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onkeyboardraiseclicked()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onKeyboardRaiseClicked()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method called on ChatroomView raise keyboard button clicked."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardRaiseClicked"}],"role":"symbol","title":"onKeyboardRaiseClicked()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardRaiseClicked"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)ChatroomViewActionEventsDelegate(im)onKeyboardRaiseClicked","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate/onKeyboardRaiseClicked()":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardRaiseClicked"}],"role":"symbol","title":"onKeyboardRaiseClicked()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardRaiseClicked"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"The method called on ChatroomView raise keyboard button clicked."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate\/onKeyboardRaiseClicked()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate\/onkeyboardraiseclicked()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomViewActionEventsDelegate":{"role":"symbol","title":"ChatroomViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"abstract":[{"type":"text","text":"ChatroomView all action events delegate."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/chatroomviewactioneventsdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onKeyboardRaiseClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardRaiseClicked"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onKeyboardRaiseClicked"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onKeyboardRaiseClicked()\/title","value":"onKeyboardRaiseClicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate~1onKeyboardRaiseClicked()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardRaiseClicked"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/title","value":"ChatroomViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ChatroomViewActionEventsDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}