{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"kick"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype\/kick"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype\/kick"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/kick","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"kick"}],"title":"ChatroomUserOperationType.kick","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatroomUIKit@E@ChatroomUserOperationType@ChatroomUserOperationTypeKick","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/kick":{"role":"symbol","title":"ChatroomUserOperationType.kick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"kick"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/kick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/kick"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType":{"role":"symbol","title":"ChatroomUserOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"}],"abstract":[{"type":"text","text":"Chatroom user operation events."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationType"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomUserOperationTypeKick"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1kick\/title","value":"ChatroomUserOperationTypeKick"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1kick\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeKick"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/title","value":"ChatroomUserOperationType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}