{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype\/unmute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuseroperationtype\/unmute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unmute","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"title":"ChatroomUserOperationType.unmute","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatroomUIKit@E@ChatroomUserOperationType@ChatroomUserOperationTypeUnmute","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType":{"role":"symbol","title":"ChatroomUserOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUserOperationType"}],"abstract":[{"type":"text","text":"Chatroom user operation events."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationType"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUserOperationType/unmute":{"role":"symbol","title":"ChatroomUserOperationType.unmute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUserOperationType\/unmute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}],"url":"\/documentation\/chatroomuikit\/chatroomuseroperationtype\/unmute"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomUserOperationTypeUnmute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/title","value":"ChatroomUserOperationType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unmute\/title","value":"ChatroomUserOperationTypeUnmute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUserOperationType~1unmute\/fragments","value":[{"kind":"identifier","text":"ChatroomUserOperationTypeUnmute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}