{"variants":[{"paths":["\/documentation\/chatroomuikit\/bottomareatoolbar\/ibottomareatoolbardrive-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/bottomareatoolbar\/ibottomareatoolbardrive-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/IBottomAreaToolBarDrive-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemSelectState(index:select:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IBottomAreaToolBarDrive Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBar/updateItemRedDot(index:showRedDot:)":{"role":"symbol","title":"updateItemRedDot(index:showRedDot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemRedDot"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showRedDot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item red dot show or hidden."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemRedDot(index:showRedDot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}],"url":"\/documentation\/chatroomuikit\/bottomareatoolbar\/updateitemreddot(index:showreddot:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBar":{"role":"symbol","title":"BottomAreaToolBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomAreaToolBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BottomAreaToolBar"}],"url":"\/documentation\/chatroomuikit\/bottomareatoolbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBar/updateItemSelectState(index:select:)":{"role":"symbol","title":"updateItemSelectState(index:select:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemSelectState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item select state."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemSelectState(index:select:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}],"url":"\/documentation\/chatroomuikit\/bottomareatoolbar\/updateitemselectstate(index:select:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/BottomAreaToolBar/updateDatas(items:)":{"role":"symbol","title":"updateDatas(items:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"You can call then method update ChatBottomFunctionBar‘s data source."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateDatas(items:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateDatasWithItems:"}],"url":"\/documentation\/chatroomuikit\/bottomareatoolbar\/updatedatas(items:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/BottomAreaToolBar\/updateItemSelectState(index:select:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateItemRedDot(index:showRedDot:)\/title","value":"updateItemRedDotWithIndex:showRedDot:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateItemRedDot(index:showRedDot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar\/title","value":"BottomAreaToolBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar\/fragments","value":[{"kind":"identifier","text":"BottomAreaToolBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateItemSelectState(index:select:)\/title","value":"updateItemSelectStateWithIndex:select:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateItemSelectState(index:select:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateDatas(items:)\/title","value":"updateDatasWithItems:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1BottomAreaToolBar~1updateDatas(items:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDatasWithItems:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}