{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomeventstype\/sendmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomeventstype\/sendmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType\/sendMessage","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"}],"title":"RoomEventsType.sendMessage","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatroomUIKit@E@RoomEventsType@RoomEventsTypeSendMessage","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"RoomEventsTypeSendMessage"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsType/sendMessage":{"role":"symbol","title":"RoomEventsType.sendMessage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType\/sendMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsTypeSendMessage"}],"url":"\/documentation\/chatroomuikit\/roomeventstype\/sendmessage"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsType":{"role":"symbol","title":"RoomEventsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomEventsType"}],"abstract":[{"type":"text","text":"All business service errors"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsType"}],"url":"\/documentation\/chatroomuikit\/roomeventstype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"RoomEventsTypeSendMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RoomEventsTypeSendMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"RoomEventsTypeSendMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType~1sendMessage\/title","value":"RoomEventsTypeSendMessage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType~1sendMessage\/fragments","value":[{"kind":"identifier","text":"RoomEventsTypeSendMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/title","value":"RoomEventsType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/fragments","value":[{"kind":"identifier","text":"RoomEventsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}