{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomeventstype\/unmute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomeventstype\/unmute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType\/unmute","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"title":"RoomEventsType.unmute","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatroomUIKit@E@RoomEventsType@RoomEventsTypeUnmute","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"RoomEventsTypeUnmute"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsType":{"role":"symbol","title":"RoomEventsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomEventsType"}],"abstract":[{"type":"text","text":"All business service errors"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsType"}],"url":"\/documentation\/chatroomuikit\/roomeventstype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsType/unmute":{"role":"symbol","title":"RoomEventsType.unmute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType\/unmute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsTypeUnmute"}],"url":"\/documentation\/chatroomuikit\/roomeventstype\/unmute"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"RoomEventsTypeUnmute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RoomEventsTypeUnmute"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"RoomEventsTypeUnmute"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/title","value":"RoomEventsType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/fragments","value":[{"kind":"identifier","text":"RoomEventsType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType~1unmute\/title","value":"RoomEventsTypeUnmute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType~1unmute\/fragments","value":[{"kind":"identifier","text":"RoomEventsTypeUnmute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}