{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IGiftsBarrageListDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDrive","text":"IGiftsBarrageListDrive"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomservice\/giftdrive"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftDrive","interfaceLanguage":"swift"},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList"},{"type":"text","text":" UI Drive"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGiftsBarrageListDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDrive"},{"kind":"text","text":"?"}],"title":"giftDrive","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit11RoomServiceC9giftDriveAA017IGiftsBarrageListF0_pSgvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IGiftsBarrageListDrive":{"role":"symbol","title":"IGiftsBarrageListDrive","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IGiftsBarrageListDrive"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IGiftsBarrageListDrive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IGiftsBarrageListDrive"}],"url":"\/documentation\/chatroomuikit\/igiftsbarragelistdrive"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room hub service transfer class in chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList":{"role":"symbol","title":"GiftsBarrageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsBarrageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsBarrageList"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/giftDrive":{"role":"symbol","title":"giftDrive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGiftsBarrageListDrive","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDrive"},{"kind":"text","text":"?"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList"},{"type":"text","text":" UI Drive"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/giftDrive","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/giftdrive"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IGiftsBarrageListDrive\/title","value":"IGiftsBarrageListDrive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IGiftsBarrageListDrive\/fragments","value":[{"kind":"identifier","text":"IGiftsBarrageListDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/title","value":"GiftsBarrageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/fragments","value":[{"kind":"identifier","text":"GiftsBarrageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}