{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserUnmuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"roomId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"chatroom id"}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UserId were muted"}]}]},{"name":"operatorId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Operator user id"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomservice\/onuserunmuted(roomid:userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomservice\/onuserunmuted(roomid:userid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/onUserUnmuted(roomId:userId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When some room participants were unmuted,then method will call notify Administrator."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:"}],"role":"symbol","title":"onUserUnmuted(roomId:userId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserUnmuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)RoomService(im)onUserUnmutedWithRoomId:userId:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/ChatroomResponseListener-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/ChatroomResponseListener-Implementations":{"role":"collectionGroup","title":"ChatroomResponseListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/ChatroomResponseListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/chatroomresponselistener-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/onUserUnmuted(roomId:userId:)":{"role":"symbol","title":"onUserUnmuted(roomId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserUnmuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some room participants were unmuted,then method will call notify Administrator."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/onUserUnmuted(roomId:userId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/onuserunmuted(roomid:userid:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room request & response wrapper class in the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onUserUnmutedWithRoomId:userId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserUnmutedWithRoomId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"roomId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1onUserUnmuted(roomId:userId:)\/title","value":"onUserUnmutedWithRoomId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1onUserUnmuted(roomId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}