{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"muteTab"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol","text":"UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"muteTab","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" value,Indicate that is member list or mute list"}]}]},{"name":"moreClosure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback,when click more."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/participantscontroller\/init(mutetab:moreclosure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/participantscontroller\/init(mutetab:moreclosure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/init(muteTab:moreClosure:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ParticipantsController init method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"muteTab"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"init(muteTab:moreClosure:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ChatroomUIKit@objc(cs)ParticipantsController(im)initWithMuteTab:moreClosure:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMuteTab:moreClosure:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController/init(muteTab:moreClosure:)":{"role":"symbol","title":"init(muteTab:moreClosure:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"muteTab"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"ParticipantsController init method."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/init(muteTab:moreClosure:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMuteTab:moreClosure:"}],"url":"\/documentation\/chatroomuikit\/participantscontroller\/init(mutetab:moreclosure:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserInfoProtocol":{"role":"symbol","title":"UserInfoProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserInfoProtocol"}],"url":"\/documentation\/chatroomuikit\/userinfoprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController":{"role":"symbol","title":"ParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantsController"}],"abstract":[{"type":"text","text":"Chatroom participants list"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantsController"}],"url":"\/documentation\/chatroomuikit\/participantscontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMuteTab:moreClosure:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMuteTab:moreClosure:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMuteTab:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"muteTab"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreClosure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<UserInfoProtocol>)","preciseIdentifier":"c:BFv(#*Qo@M@ChatroomUIKit@objc(pl)UserInfoProtocol)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"moreClosure"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController~1init(muteTab:moreClosure:)\/title","value":"initWithMuteTab:moreClosure:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController~1init(muteTab:moreClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMuteTab:moreClosure:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/title","value":"UserInfoProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/fragments","value":[{"kind":"identifier","text":"UserInfoProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/title","value":"ParticipantsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/fragments","value":[{"kind":"identifier","text":"ParticipantsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}