{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/participantscontroller\/onsearchbarclicked()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/participantscontroller\/onsearchbarclicked()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/onSearchBarClicked()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SearchBarActionEvents.onSearchBarClicked()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"title":"onSearchBarClicked()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ParticipantsController(im)onSearchBarClicked","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onSearchBarClicked"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/SearchBarActionEvents-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController":{"role":"symbol","title":"ParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantsController"}],"abstract":[{"type":"text","text":"Chatroom participants list"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantsController"}],"url":"\/documentation\/chatroomuikit\/participantscontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController/onSearchBarClicked()":{"role":"symbol","title":"onSearchBarClicked()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/onSearchBarClicked()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSearchBarClicked"}],"url":"\/documentation\/chatroomuikit\/participantscontroller\/onsearchbarclicked()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController/SearchBarActionEvents-Implementations":{"role":"collectionGroup","title":"SearchBarActionEvents Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/SearchBarActionEvents-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/participantscontroller\/searchbaractionevents-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSearchBarClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearchBarClicked"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/title","value":"ParticipantsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/fragments","value":[{"kind":"identifier","text":"ParticipantsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController~1onSearchBarClicked()\/title","value":"onSearchBarClicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController~1onSearchBarClicked()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearchBarClicked"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}