{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomService","text":"RoomService"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/participantscontroller\/roomservice"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/roomService","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomService"}],"title":"roomService","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit22ParticipantsControllerC11roomServiceAA04RoomF0Cvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController":{"role":"symbol","title":"ParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantsController"}],"abstract":[{"type":"text","text":"Chatroom participants list"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantsController"}],"url":"\/documentation\/chatroomuikit\/participantscontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room hub service transfer class in chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ParticipantsController/roomService":{"role":"symbol","title":"roomService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomService","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomService"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ParticipantsController\/roomService","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/participantscontroller\/roomservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/title","value":"ParticipantsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ParticipantsController\/fragments","value":[{"kind":"identifier","text":"ParticipantsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}