{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","text":"GiftsViewActionEventsDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsview\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsview\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView\/addActionHandler(actionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add UI action handler."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":")"}],"title":"addActionHandler(actionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)GiftsView(im)addActionHandlerWithActionHandler:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsView":{"role":"symbol","title":"GiftsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsView"}],"url":"\/documentation\/chatroomuikit\/giftsview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsView/addActionHandler(actionHandler:)":{"role":"symbol","title":"addActionHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add UI action handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsView\/addActionHandler(actionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"url":"\/documentation\/chatroomuikit\/giftsview\/addactionhandler(actionhandler:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewActionEventsDelegate":{"role":"symbol","title":"GiftsViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"abstract":[{"type":"text","text":"GiftsView event actions delegate"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftsViewActionEventsDelegate>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"actionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView\/title","value":"GiftsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView\/fragments","value":[{"kind":"identifier","text":"GiftsView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsView~1addActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/title","value":"GiftsViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}