{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowCloseButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView","text":"AlertView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/alertview\/isshowclosebutton(isshow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/alertview\/isshowclosebutton(isshow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/isShowCloseButton(isShow:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowCloseButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"title":"isShowCloseButton(isShow:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)AlertView(im)isShowCloseButtonWithIsShow:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/isShowCloseButton(isShow:)":{"role":"symbol","title":"isShowCloseButton(isShow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowCloseButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/isShowCloseButton(isShow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}],"url":"\/documentation\/chatroomuikit\/alertview\/isshowclosebutton(isshow:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView":{"role":"symbol","title":"AlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"url":"\/documentation\/chatroomuikit\/alertview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isShowCloseButtonWithIsShow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView","text":"AlertView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isShow"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1isShowCloseButton(isShow:)\/title","value":"isShowCloseButtonWithIsShow:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1isShowCloseButton(isShow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isShowCloseButtonWithIsShow:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/fragments","value":[{"kind":"identifier","text":"AlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}