{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView","text":"AlertView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/alertview\/textfield(cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/alertview\/textfield(cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(cornerRadius:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"title":"textField(cornerRadius:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)AlertView(im)textFieldWithCornerRadius:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldWithCornerRadius:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView":{"role":"symbol","title":"AlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"url":"\/documentation\/chatroomuikit\/alertview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/AlertView/textField(cornerRadius:)":{"role":"symbol","title":"textField(cornerRadius:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView\/textField(cornerRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldWithCornerRadius:"}],"url":"\/documentation\/chatroomuikit\/alertview\/textfield(cornerradius:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textFieldWithCornerRadius:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithCornerRadius:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/AlertView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)AlertView","text":"AlertView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"textFieldWithCornerRadius:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView\/fragments","value":[{"kind":"identifier","text":"AlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(cornerRadius:)\/title","value":"textFieldWithCornerRadius:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1AlertView~1textField(cornerRadius:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithCornerRadius:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}