{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol","text":"UserInfoProtocol"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftentityprotocol\/senduser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftentityprotocol\/senduser"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol\/sendUser","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sendUser"}],"role":"symbol","title":"sendUser","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol(py)sendUser","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityProtocol":{"role":"symbol","title":"GiftEntityProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityProtocol"}],"url":"\/documentation\/chatroomuikit\/giftentityprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserInfoProtocol":{"role":"symbol","title":"UserInfoProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserInfoProtocol"}],"url":"\/documentation\/chatroomuikit\/userinfoprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityProtocol/sendUser":{"navigatorTitle":[{"kind":"identifier","text":"sendUser"}],"role":"symbol","title":"sendUser","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol\/sendUser","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftentityprotocol\/senduser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sendUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sendUser"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<UserInfoProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sendUser"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/title","value":"GiftEntityProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/fragments","value":[{"kind":"identifier","text":"GiftEntityProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/title","value":"UserInfoProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/fragments","value":[{"kind":"identifier","text":"UserInfoProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol~1sendUser\/title","value":"sendUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol~1sendUser\/fragments","value":[{"kind":"identifier","text":"sendUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}