{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea","text":"ChatMessage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessage"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/messagelistactioneventshandler\/onmessageclicked(message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/messagelistactioneventshandler\/onmessageclicked(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler\/onMessageClicked(message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method called on message  clicked."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onMessageClickedWithMessage:"}],"role":"symbol","title":"onMessageClicked(message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)MessageListActionEventsHandler(im)onMessageClickedWithMessage:","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageListActionEventsHandler/onMessageClicked(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageClickedWithMessage:"}],"role":"symbol","title":"onMessageClicked(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method called on message  clicked."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler\/onMessageClicked(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/messagelistactioneventshandler\/onmessageclicked(message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessage":{"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"url":"\/documentation\/chatroomuikit\/chatmessage"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageListActionEventsHandler":{"role":"symbol","title":"MessageListActionEventsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListActionEventsHandler"}],"abstract":[{"type":"text","text":"MessageList action events handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListActionEventsHandler"}],"url":"\/documentation\/chatroomuikit\/messagelistactioneventshandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onMessageClickedWithMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageClickedWithMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageClickedWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMChatMessage","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler~1onMessageClicked(message:)\/title","value":"onMessageClickedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler~1onMessageClicked(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageClickedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler\/title","value":"MessageListActionEventsHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler\/fragments","value":[{"kind":"identifier","text":"MessageListActionEventsHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}