{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISlider","preciseIdentifier":"c:objc(cs)UISlider"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/huesettingviewcontroller\/errorvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/huesettingviewcontroller\/errorvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController\/errorValue","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISlider","preciseIdentifier":"c:objc(cs)UISlider"},{"kind":"text","text":"!"}],"title":"errorValue","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)HueSettingViewController(py)errorValue","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"errorValue"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/HueSettingViewController":{"role":"symbol","title":"HueSettingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HueSettingViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HueSettingViewController"}],"url":"\/documentation\/chatroomuikit_example\/huesettingviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/HueSettingViewController/errorValue":{"role":"symbol","title":"errorValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISlider","preciseIdentifier":"c:objc(cs)UISlider"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController\/errorValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorValue"}],"url":"\/documentation\/chatroomuikit_example\/huesettingviewcontroller\/errorvalue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"errorValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"errorValue"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UISlider","preciseIdentifier":"c:objc(cs)UISlider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"errorValue"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController\/title","value":"HueSettingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController\/fragments","value":[{"kind":"identifier","text":"HueSettingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController~1errorValue\/title","value":"errorValue"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController~1errorValue\/fragments","value":[{"kind":"identifier","text":"errorValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}