{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatBottomFunctionBar","text":"ChatBottomFunctionBar"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomview\/bottombar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/bottomBar","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bottom function bar below chat barrages list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomFunctionBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatBottomFunctionBar"}],"title":"bottomBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit0A4ViewC9bottomBarAA018ChatBottomFunctionE0Cvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/bottomBar":{"role":"symbol","title":"bottomBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomFunctionBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatBottomFunctionBar"}],"abstract":[{"type":"text","text":"Bottom function bar below chat barrages list."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/bottomBar","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomview\/bottombar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar":{"role":"symbol","title":"ChatBottomFunctionBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomFunctionBar"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/title","value":"ChatBottomFunctionBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/fragments","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}