{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageList","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageList","text":"GiftMessageList"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomview\/giftarea"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/giftArea","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gift list on receive gift."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftMessageList","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageList"}],"title":"giftArea","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit0A4ViewC8giftAreaAA15GiftMessageListCvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/giftArea":{"role":"symbol","title":"giftArea","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftMessageList","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageList"}],"abstract":[{"type":"text","text":"Gift list on receive gift."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/giftArea","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomview\/giftarea"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageList":{"role":"symbol","title":"GiftMessageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageList"}],"url":"\/documentation\/chatroomuikit\/giftmessagelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageList\/title","value":"GiftMessageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageList\/fragments","value":[{"kind":"identifier","text":"GiftMessageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}