{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"respondTouch"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":" "},{"kind":"internalParam","text":"menus"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol","text":"ChatBottomItemProtocol"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"showGiftBarrage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"hiddenChat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CGRect"}]}]},{"name":"menus","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array"}]}]},{"name":"showGiftBarrage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" showGiftBarrage value"}]}]},{"name":"hiddenChat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" hiddenChat value"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomview\/init(respondtouch:bottom:showgiftbarrage:hiddenchat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomview\/init(respondtouch:bottom:showgiftbarrage:hiddenchat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/init(respondTouch:bottom:showGiftBarrage:hiddenChat:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chatroom view init method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"respondTouch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"showGiftBarrage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenChat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(respondTouch:bottom:showGiftBarrage:hiddenChat:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatroomView(im)initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomItemProtocol":{"role":"symbol","title":"ChatBottomItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItemProtocol"}],"abstract":[{"type":"text","text":"ChatBottomBar item protocol"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItemProtocol"}],"url":"\/documentation\/chatroomuikit\/chatbottomitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/init(respondTouch:bottom:showGiftBarrage:hiddenChat:)":{"role":"symbol","title":"init(respondTouch:bottom:showGiftBarrage:hiddenChat:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"respondTouch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"showGiftBarrage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenChat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Chatroom view init method."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/init(respondTouch:bottom:showGiftBarrage:hiddenChat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"}],"url":"\/documentation\/chatroomuikit\/chatroomview\/init(respondtouch:bottom:showgiftbarrage:hiddenchat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRespondTouch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ChatBottomItemProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"menus"},{"kind":"text","text":" "},{"kind":"identifier","text":"showGiftBarrage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"showGiftBarrage"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenChat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hiddenChat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/title","value":"ChatBottomItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/fragments","value":[{"kind":"identifier","text":"ChatBottomItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView~1init(respondTouch:bottom:showGiftBarrage:hiddenChat:)\/title","value":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView~1init(respondTouch:bottom:showGiftBarrage:hiddenChat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRespondTouch:bottom:showGiftBarrage:hiddenChat:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}