{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)MessageInputBar","text":"MessageInputBar"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomview\/inputbar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/inputBar","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Input text menu bar."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)MessageInputBar"}],"title":"inputBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit0A4ViewC8inputBarAA012MessageInputE0Cvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageInputBar":{"role":"symbol","title":"MessageInputBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageInputBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageInputBar"}],"url":"\/documentation\/chatroomuikit\/messageinputbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/inputBar":{"role":"symbol","title":"inputBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)MessageInputBar"}],"abstract":[{"type":"text","text":"Input text menu bar."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/inputBar","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomview\/inputbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageInputBar\/fragments","value":[{"kind":"identifier","text":"MessageInputBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}