{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomview\/onkeyboardwillwakeup()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomview\/onkeyboardwillwakeup()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/onKeyboardWillWakeup()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When you tap "},{"type":"codeVoice","code":"button"},{"type":"text","text":" let’s chat callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onKeyboardWillWakeup"}],"role":"symbol","title":"onKeyboardWillWakeup()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomView(im)onKeyboardWillWakeup","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/ChatBottomFunctionBarActionEvents-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/onKeyboardWillWakeup()":{"role":"symbol","title":"onKeyboardWillWakeup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"When you tap "},{"type":"codeVoice","code":"button"},{"type":"text","text":" let’s chat callback."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/onKeyboardWillWakeup()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onKeyboardWillWakeup"}],"url":"\/documentation\/chatroomuikit\/chatroomview\/onkeyboardwillwakeup()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView":{"role":"symbol","title":"ChatroomView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomView"}],"abstract":[{"type":"text","text":"ChatroomUIKit’s ChatroomView UI component."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomView"}],"url":"\/documentation\/chatroomuikit\/chatroomview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomView/ChatBottomFunctionBarActionEvents-Implementations":{"role":"collectionGroup","title":"ChatBottomFunctionBarActionEvents Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomView\/ChatBottomFunctionBarActionEvents-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomview\/chatbottomfunctionbaractionevents-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onKeyboardWillWakeup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardWillWakeup"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onKeyboardWillWakeup"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView~1onKeyboardWillWakeup()\/title","value":"onKeyboardWillWakeup"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView~1onKeyboardWillWakeup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeyboardWillWakeup"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/title","value":"ChatroomView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomView\/fragments","value":[{"kind":"identifier","text":"ChatroomView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}