{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(refreshWithChatEntity:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity","text":"ChatEntity"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"chat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatmessagecell\/refresh(chat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatmessagecell\/refresh(chat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell\/refresh(chat:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Refresh the entity that renders the chat barrage, which contains height, width and rich text cache."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity"},{"kind":"text","text":")"}],"title":"refresh(chat:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatMessageCell(im)refreshWithChatEntity:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"refreshWithChatEntity:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell/refresh(chat:)":{"role":"symbol","title":"refresh(chat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Refresh the entity that renders the chat barrage, which contains height, width and rich text cache."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell\/refresh(chat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshWithChatEntity:"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell\/refresh(chat:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell":{"role":"symbol","title":"ChatMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display chat messages as a content display style of the cell."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageCell"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEntity":{"role":"symbol","title":"ChatEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEntity"}],"abstract":[{"type":"text","text":"A class that represents a chat entity, which includes a message, a timestamp, attributed text, height, and width."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatEntity"}],"url":"\/documentation\/chatroomuikit\/chatentity"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshWithChatEntity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithChatEntity:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshWithChatEntity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity","text":"ChatEntity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"chat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell~1refresh(chat:)\/title","value":"refreshWithChatEntity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell~1refresh(chat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithChatEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/title","value":"ChatMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEntity\/title","value":"ChatEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEntity\/fragments","value":[{"kind":"identifier","text":"ChatEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}