{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle","text":"ChatMessageDisplayContentStyle"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatmessagecell\/style"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatmessagecell\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell\/style","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle"}],"title":"style","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatMessageCell(py)style","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"style"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell/style":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell\/style","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell\/style"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell":{"role":"symbol","title":"ChatMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display chat messages as a content display style of the cell."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageCell"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle":{"role":"symbol","title":"ChatMessageDisplayContentStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle","text":"ChatMessageDisplayContentStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell~1style\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell~1style\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/title","value":"ChatMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}