{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol","text":"ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"items","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Array<ChatBottomItemProtocol>"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updatedatas(items:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updatedatas(items:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateDatas(items:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can call then method update ChatBottomFunctionBar‘s data source."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateDatasWithItems:"}],"role":"symbol","title":"updateDatas(items:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)IChatBottomFunctionBarDrive(im)updateDatasWithItems:","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomItemProtocol":{"role":"symbol","title":"ChatBottomItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItemProtocol"}],"abstract":[{"type":"text","text":"ChatBottomBar item protocol"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItemProtocol"}],"url":"\/documentation\/chatroomuikit\/chatbottomitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive/updateDatas(items:)":{"navigatorTitle":[{"kind":"identifier","text":"updateDatasWithItems:"}],"role":"symbol","title":"updateDatas(items:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"You can call then method update ChatBottomFunctionBar‘s data source."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive\/updateDatas(items:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive\/updatedatas(items:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IChatBottomFunctionBarDrive":{"role":"symbol","title":"IChatBottomFunctionBarDrive","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"abstract":[{"type":"text","text":"ChatBottomFunctionBar‘s Drive."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IChatBottomFunctionBarDrive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}],"url":"\/documentation\/chatroomuikit\/ichatbottomfunctionbardrive"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateDatasWithItems:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDatasWithItems:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateDatasWithItems:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ChatBottomItemProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"items"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/title","value":"ChatBottomItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomItemProtocol\/fragments","value":[{"kind":"identifier","text":"ChatBottomItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateDatas(items:)\/title","value":"updateDatasWithItems:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive~1updateDatas(items:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDatasWithItems:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/title","value":"IChatBottomFunctionBarDrive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IChatBottomFunctionBarDrive\/fragments","value":[{"kind":"identifier","text":"IChatBottomFunctionBarDrive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}