{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchbaractionevents\/onsearchbarclicked()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/searchbaractionevents\/onsearchbarclicked()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents\/onSearchBarClicked()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onSearchBarClicked"}],"role":"symbol","title":"onSearchBarClicked()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents(im)onSearchBarClicked","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBarActionEvents/onSearchBarClicked()":{"navigatorTitle":[{"kind":"identifier","text":"onSearchBarClicked"}],"role":"symbol","title":"onSearchBarClicked()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents\/onSearchBarClicked()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/searchbaractionevents\/onsearchbarclicked()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBarActionEvents":{"role":"symbol","title":"SearchBarActionEvents","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBarActionEvents"}],"abstract":[{"type":"text","text":"SearchBar action events"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchBarActionEvents"}],"url":"\/documentation\/chatroomuikit\/searchbaractionevents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSearchBarClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearchBarClicked"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSearchBarClicked"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents~1onSearchBarClicked()\/title","value":"onSearchBarClicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents~1onSearchBarClicked()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearchBarClicked"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/title","value":"SearchBarActionEvents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/fragments","value":[{"kind":"identifier","text":"SearchBarActionEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}