{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle","text":"ChatMessageDisplayContentStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/appearance\/messagedisplaystyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/appearance\/messagedisplaystyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageDisplayStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can change the overall cell layout style of the chat area by setting the current properties."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle"}],"title":"messageDisplayStyle","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)Appearance(cpy)messageDisplayStyle","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"messageDisplayStyle"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle":{"role":"symbol","title":"ChatMessageDisplayContentStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/chatroomuikit\/appearance"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/messageDisplayStyle":{"role":"symbol","title":"messageDisplayStyle","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"You can change the overall cell layout style of the chat area by setting the current properties."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/messageDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageDisplayStyle"}],"url":"\/documentation\/chatroomuikit\/appearance\/messagedisplaystyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"messageDisplayStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageDisplayStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle","text":"ChatMessageDisplayContentStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDisplayStyle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1messageDisplayStyle\/title","value":"messageDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1messageDisplayStyle\/fragments","value":[{"kind":"identifier","text":"messageDisplayStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}