{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerTitleBarItemWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/appearance\/pagecontainertitlebaritemwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/appearance\/pagecontainertitlebaritemwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerTitleBarItemWidth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can change the width of a single option with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainerTitleBar"},{"type":"text","text":" in the popup container by setting the current property"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerTitleBarItemWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"pageContainerTitleBarItemWidth","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)Appearance(cpy)pageContainerTitleBarItemWidth","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configuration for whole application."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/chatroomuikit\/appearance"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainerTitleBar":{"role":"symbol","title":"PageContainerTitleBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainerTitleBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainerTitleBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainerTitleBar"}],"url":"\/documentation\/chatroomuikit\/pagecontainertitlebar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance/pageContainerTitleBarItemWidth":{"role":"symbol","title":"pageContainerTitleBarItemWidth","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerTitleBarItemWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"You can change the width of a single option with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainerTitleBar"},{"type":"text","text":" in the popup container by setting the current property"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance\/pageContainerTitleBarItemWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}],"url":"\/documentation\/chatroomuikit\/appearance\/pagecontainertitlebaritemwidth"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"pageContainerTitleBarItemWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainerTitleBar\/title","value":"PageContainerTitleBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainerTitleBar\/fragments","value":[{"kind":"identifier","text":"PageContainerTitleBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerTitleBarItemWidth\/title","value":"pageContainerTitleBarItemWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance~1pageContainerTitleBarItemWidth\/fragments","value":[{"kind":"identifier","text":"pageContainerTitleBarItemWidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}