{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerBefore"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPageViewControllerDataSource.pageViewController(_:viewControllerBefore:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"role":"symbol","title":"pageViewController(_:viewControllerBefore:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)PageContainer(im)pageViewController:viewControllerBeforeViewController:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"role":"collectionGroup","title":"UIPageViewControllerDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer":{"role":"symbol","title":"PageContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"url":"\/documentation\/chatroomuikit\/pagecontainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/pageViewController(_:viewControllerBefore:)":{"role":"symbol","title":"pageViewController(_:viewControllerBefore:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"url":"\/documentation\/chatroomuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pageViewController:viewControllerBeforeViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pageViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewControllerBeforeViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/title","value":"pageViewController:viewControllerBeforeViewController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}