{"variants":[{"paths":["\/documentation\/chatroomuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UIPageViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer":{"role":"symbol","title":"PageContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"url":"\/documentation\/chatroomuikit\/pagecontainer"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/pageViewController(_:willTransitionTo:)":{"role":"symbol","title":"pageViewController(_:willTransitionTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willTransitionTo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageViewController:willTransitionToViewControllers:"}],"url":"\/documentation\/chatroomuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/PageContainer/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)":{"role":"symbol","title":"pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAnimating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previousViewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transitionCompleted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}],"url":"\/documentation\/chatroomuikit\/pagecontainer\/pageviewcontroller(_:didfinishanimating:previousviewcontrollers:transitioncompleted:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/title","value":"pageViewController:willTransitionToViewControllers:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:willTransitionToViewControllers:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/title","value":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}