{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol","text":"GiftEntityProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"GiftEntityProtocol"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsviewcontroller\/ongiftsendclick(item:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsviewcontroller\/ongiftsendclick(item:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/onGiftSendClick(item:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Send button click"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onGiftSendClickWithItem:"}],"role":"symbol","title":"onGiftSendClick(item:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)GiftsViewController(im)onGiftSendClickWithItem:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/GiftsViewActionEventsDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController/GiftsViewActionEventsDelegate-Implementations":{"role":"collectionGroup","title":"GiftsViewActionEventsDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/GiftsViewActionEventsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/giftsviewcontroller\/giftsviewactioneventsdelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityProtocol":{"role":"symbol","title":"GiftEntityProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityProtocol"}],"url":"\/documentation\/chatroomuikit\/giftentityprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController/onGiftSendClick(item:)":{"role":"symbol","title":"onGiftSendClick(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send button click"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/onGiftSendClick(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGiftSendClickWithItem:"}],"url":"\/documentation\/chatroomuikit\/giftsviewcontroller\/ongiftsendclick(item:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController":{"role":"symbol","title":"GiftsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewController"}],"url":"\/documentation\/chatroomuikit\/giftsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onGiftSendClickWithItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSendClickWithItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onGiftSendClickWithItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftEntityProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/title","value":"GiftEntityProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/fragments","value":[{"kind":"identifier","text":"GiftEntityProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController~1onGiftSendClick(item:)\/title","value":"onGiftSendClickWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController~1onGiftSendClick(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSendClickWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/title","value":"GiftsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/fragments","value":[{"kind":"identifier","text":"GiftsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}