{"variants":[{"paths":["\/documentation\/chatroomuikit\/reportoptionscontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/reportoptionscontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:numberOfRowsInSection:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:titleForHeaderInSection:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UITableViewDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/tableview(_:numberofrowsinsection:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/tableView(_:titleForHeaderInSection:)":{"role":"symbol","title":"tableView(_:titleForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:titleForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:titleForHeaderInSection:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/tableview(_:titleforheaderinsection:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller\/tableview(_:cellforrowat:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ReportOptionsController":{"role":"symbol","title":"ReportOptionsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportOptionsController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportOptionsController"}],"url":"\/documentation\/chatroomuikit\/reportoptionscontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:numberOfRowsInSection:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ReportOptionsController\/tableView(_:titleForHeaderInSection:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:titleForHeaderInSection:)\/title","value":"tableView:titleForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:titleForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:titleForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController\/title","value":"ReportOptionsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ReportOptionsController\/fragments","value":[{"kind":"identifier","text":"ReportOptionsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}