{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftResponseListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener","text":"GiftResponseListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UserStateChangedListener"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/bindgiftresponselistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/bindgiftresponselistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/bindGiftResponseListener(listener:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bind user state changed listener"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftResponseListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":")"}],"title":"bindGiftResponseListener(listener:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)GiftServiceImplement(im)bindGiftResponseListenerWithListener:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement":{"role":"symbol","title":"GiftServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/bindGiftResponseListener(listener:)":{"role":"symbol","title":"bindGiftResponseListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftResponseListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/bindGiftResponseListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/bindgiftresponselistener(listener:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/GiftService-Implementations":{"role":"collectionGroup","title":"GiftService Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/giftserviceimplement\/giftservice-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftResponseListener":{"role":"symbol","title":"GiftResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftResponseListener"}],"url":"\/documentation\/chatroomuikit\/giftresponselistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bindGiftResponseListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftResponseListener>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1bindGiftResponseListener(listener:)\/title","value":"bindGiftResponseListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1bindGiftResponseListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/title","value":"GiftResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/fragments","value":[{"kind":"identifier","text":"GiftResponseListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}