{"variants":[{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/emchatmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/emchatmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/EMChatManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/messagesDidReceive(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"EMChatManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement":{"role":"symbol","title":"GiftServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/messagesDidReceive(_:)":{"role":"symbol","title":"messagesDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/messagesDidReceive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesDidReceive:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/messagesdidreceive(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/messagesDidReceive(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1messagesDidReceive(_:)\/title","value":"messagesDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1messagesDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidReceive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}