{"variants":[{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/giftservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/giftservice-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/bindGiftResponseListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/sendGift(gift:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/unbindGiftResponseListener(listener:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"GiftService Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/unbindGiftResponseListener(listener:)":{"role":"symbol","title":"unbindGiftResponseListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGiftResponseListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unbind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/unbindGiftResponseListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unbindGiftResponseListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/unbindgiftresponselistener(listener:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement":{"role":"symbol","title":"GiftServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/sendGift(gift:completion:)":{"role":"symbol","title":"sendGift(gift:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendGift"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send gift."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/sendGift(gift:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendGiftWithGift:completion:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/sendgift(gift:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/bindGiftResponseListener(listener:)":{"role":"symbol","title":"bindGiftResponseListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftResponseListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/bindGiftResponseListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/bindgiftresponselistener(listener:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/bindGiftResponseListener(listener:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/sendGift(gift:completion:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/unbindGiftResponseListener(listener:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1unbindGiftResponseListener(listener:)\/title","value":"unbindGiftResponseListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1unbindGiftResponseListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindGiftResponseListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1sendGift(gift:completion:)\/title","value":"sendGiftWithGift:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1sendGift(gift:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendGiftWithGift:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1bindGiftResponseListener(listener:)\/title","value":"bindGiftResponseListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1bindGiftResponseListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindGiftResponseListenerWithListener:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}