{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseDelegates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener","text":"GiftResponseListener"},{"kind":"text","text":"> { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement\/responsedelegates"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/responseDelegates","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseDelegates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":">"}],"title":"responseDelegates","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit20GiftServiceImplementC17responseDelegatesSo11NSHashTableCyAA0C16ResponseListener_pGvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/responseDelegates":{"role":"symbol","title":"responseDelegates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseDelegates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"GiftResponseListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftResponseListener"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/responseDelegates","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/giftserviceimplement\/responsedelegates"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftResponseListener":{"role":"symbol","title":"GiftResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftResponseListener"}],"url":"\/documentation\/chatroomuikit\/giftresponselistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement":{"role":"symbol","title":"GiftServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/title","value":"GiftResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftResponseListener\/fragments","value":[{"kind":"identifier","text":"GiftResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}