{"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsbarragelist\/giftsbarragelisttransformanimationdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsbarragelist\/giftsbarragelisttransformanimationdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/GiftsBarrageListTransformAnimationDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/rowHeight()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleX()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleY()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"GiftsBarrageListTransformAnimationDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList/rowHeight()":{"role":"symbol","title":"rowHeight()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional method that returns the row height for the GiftsBarrageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/rowHeight()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rowHeight"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist\/rowheight()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList/zoomScaleY()":{"role":"symbol","title":"zoomScaleY()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScaleY"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional method that returns the zoom scale for the y-axis of the GiftsBarrageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleY()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zoomScaleY"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist\/zoomscaley()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList/zoomScaleX()":{"role":"symbol","title":"zoomScaleX()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScaleX"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional method that returns the zoom scale for the x-axis of the GiftsBarrageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleX()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zoomScaleX"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist\/zoomscalex()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList":{"role":"symbol","title":"GiftsBarrageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsBarrageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsBarrageList"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/rowHeight()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleX()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/zoomScaleY()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1rowHeight()\/title","value":"rowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1rowHeight()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rowHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1zoomScaleY()\/title","value":"zoomScaleY"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1zoomScaleY()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"zoomScaleY"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1zoomScaleX()\/title","value":"zoomScaleX"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1zoomScaleX()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"zoomScaleX"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/title","value":"GiftsBarrageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/fragments","value":[{"kind":"identifier","text":"GiftsBarrageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}