{"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsbarragelist\/igiftsbarragelistdrive-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsbarragelist\/igiftsbarragelistdrive-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/IGiftsBarrageListDrive-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/receiveGift(gift:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IGiftsBarrageListDrive Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList/receiveGift(gift:)":{"role":"symbol","title":"receiveGift(gift:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiveGift"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Refresh the UI after receiving the gift"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/receiveGift(gift:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receiveGiftWithGift:"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist\/receivegift(gift:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageList":{"role":"symbol","title":"GiftsBarrageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsBarrageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsBarrageList"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageList\/receiveGift(gift:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1receiveGift(gift:)\/title","value":"receiveGiftWithGift:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList~1receiveGift(gift:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"receiveGiftWithGift:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/title","value":"GiftsBarrageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageList\/fragments","value":[{"kind":"identifier","text":"GiftsBarrageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}