{"variants":[{"paths":["\/documentation\/chatroomuikit\/chatbottomfunctionbar\/ichatbottomfunctionbardrive-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatbottomfunctionbar\/ichatbottomfunctionbardrive-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/IChatBottomFunctionBarDrive-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemSelectState(index:select:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IChatBottomFunctionBarDrive Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/updateItemRedDot(index:showRedDot:)":{"role":"symbol","title":"updateItemRedDot(index:showRedDot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemRedDot"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showRedDot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item red dot show or hidden."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemRedDot(index:showRedDot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/updateitemreddot(index:showreddot:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar":{"role":"symbol","title":"ChatBottomFunctionBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomFunctionBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomFunctionBar"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/updateDatas(items:)":{"role":"symbol","title":"updateDatas(items:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDatas"},{"kind":"text","text":"("},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"You can call then method update ChatBottomFunctionBar‘s data source."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateDatas(items:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateDatasWithItems:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/updatedatas(items:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBottomFunctionBar/updateItemSelectState(index:select:)":{"role":"symbol","title":"updateItemSelectState(index:select:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItemSelectState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can call the method update item select state."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemSelectState(index:select:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}],"url":"\/documentation\/chatroomuikit\/chatbottomfunctionbar\/updateitemselectstate(index:select:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateDatas(items:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemRedDot(index:showRedDot:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBottomFunctionBar\/updateItemSelectState(index:select:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateItemRedDot(index:showRedDot:)\/title","value":"updateItemRedDotWithIndex:showRedDot:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateItemRedDot(index:showRedDot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemRedDotWithIndex:showRedDot:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/title","value":"ChatBottomFunctionBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar\/fragments","value":[{"kind":"identifier","text":"ChatBottomFunctionBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateDatas(items:)\/title","value":"updateDatasWithItems:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateDatas(items:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDatasWithItems:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateItemSelectState(index:select:)\/title","value":"updateItemSelectStateWithIndex:select:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBottomFunctionBar~1updateItemSelectState(index:select:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItemSelectStateWithIndex:select:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}