{"variants":[{"paths":["\/documentation\/chatroomuikit_example"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomListViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ExampleRequiredConfig","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ExamplesViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/OCUIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController"]},{"title":"Structures","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ColorResource","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ImageResource"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/SwiftUI","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIKit"]}],"kind":"symbol","metadata":{"roleHeading":"Application","externalID":"ChatroomUIKit_Example","title":"ChatroomUIKit_Example","symbolKind":"module","role":"collection","modules":[{"name":"ChatroomUIKit_Example"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ColorResource":{"role":"symbol","title":"ColorResource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorResource"}],"abstract":[{"type":"text","text":"A color resource."}],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ColorResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorResource"}],"url":"\/documentation\/chatroomuikit_example\/colorresource"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatroomCell":{"role":"symbol","title":"ChatroomCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomCell"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomCell"}],"url":"\/documentation\/chatroomuikit_example\/chatroomcell"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ExampleRequiredConfig":{"role":"symbol","title":"ExampleRequiredConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExampleRequiredConfig"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ExampleRequiredConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExampleRequiredConfig"}],"url":"\/documentation\/chatroomuikit_example\/examplerequiredconfig"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/MineGiftsViewController":{"role":"symbol","title":"MineGiftsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MineGiftsViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MineGiftsViewController"}],"url":"\/documentation\/chatroomuikit_example\/minegiftsviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatroomListViewController":{"role":"symbol","title":"ChatroomListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomListViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomListViewController"}],"url":"\/documentation\/chatroomuikit_example\/chatroomlistviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController":{"role":"symbol","title":"UIWithBusinessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIWithBusinessViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIWithBusinessViewController"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIKit":{"role":"collection","title":"UIKit","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uikit"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ExamplesViewController":{"role":"symbol","title":"ExamplesViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExamplesViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ExamplesViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExamplesViewController"}],"url":"\/documentation\/chatroomuikit_example\/examplesviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem":{"role":"symbol","title":"ChatBottomItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItem"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ImageResource":{"role":"symbol","title":"ImageResource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageResource"}],"abstract":[{"type":"text","text":"An image resource."}],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ImageResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageResource"}],"url":"\/documentation\/chatroomuikit_example\/imageresource"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/OCUIComponentsExampleViewController":{"role":"symbol","title":"OCUIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/OCUIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/ocuicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/SwiftUI":{"role":"collection","title":"SwiftUI","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/SwiftUI","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/swiftui"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/HueSettingViewController":{"role":"symbol","title":"HueSettingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HueSettingViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HueSettingViewController"}],"url":"\/documentation\/chatroomuikit_example\/huesettingviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomListViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ExamplesViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/HueSettingViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/OCUIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell\/title","value":"ChatroomCell"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell\/fragments","value":[{"kind":"identifier","text":"ChatroomCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController\/title","value":"MineGiftsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController\/fragments","value":[{"kind":"identifier","text":"MineGiftsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomListViewController\/title","value":"ChatroomListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomListViewController\/fragments","value":[{"kind":"identifier","text":"ChatroomListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/title","value":"UIWithBusinessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/fragments","value":[{"kind":"identifier","text":"UIWithBusinessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ExamplesViewController\/title","value":"ExamplesViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ExamplesViewController\/fragments","value":[{"kind":"identifier","text":"ExamplesViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/title","value":"ChatBottomItem"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/fragments","value":[{"kind":"identifier","text":"ChatBottomItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1OCUIComponentsExampleViewController\/title","value":"OCUIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1OCUIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController\/title","value":"HueSettingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1HueSettingViewController\/fragments","value":[{"kind":"identifier","text":"HueSettingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}