{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol","text":"GiftEntityProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftmessagecell\/gift"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftmessagecell\/gift"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell\/gift","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":"?"}],"title":"gift","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)GiftMessageCell(py)gift","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"gift"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageCell/gift":{"role":"symbol","title":"gift","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell\/gift","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gift"}],"url":"\/documentation\/chatroomuikit\/giftmessagecell\/gift"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageCell":{"role":"symbol","title":"GiftMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display a gift item in a  view."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageCell"}],"url":"\/documentation\/chatroomuikit\/giftmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityProtocol":{"role":"symbol","title":"GiftEntityProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityProtocol"}],"url":"\/documentation\/chatroomuikit\/giftentityprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"gift"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"gift"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<GiftEntityProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"gift"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell~1gift\/title","value":"gift"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell~1gift\/fragments","value":[{"kind":"identifier","text":"gift"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/title","value":"GiftMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/fragments","value":[{"kind":"identifier","text":"GiftMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/title","value":"GiftEntityProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/fragments","value":[{"kind":"identifier","text":"GiftEntityProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}