{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ImageView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ImageView","text":"ImageView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftmessagecell\/gifticon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftmessagecell\/gifticon"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell\/giftIcon","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ImageView"}],"title":"giftIcon","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)GiftMessageCell(py)giftIcon","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"giftIcon"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageCell/giftIcon":{"role":"symbol","title":"giftIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell\/giftIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"giftIcon"}],"url":"\/documentation\/chatroomuikit\/giftmessagecell\/gifticon"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"A subclass of "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":" that provides a method for loading an image from a URL."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/chatroomuikit\/imageview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageCell":{"role":"symbol","title":"GiftMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display a gift item in a  view."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageCell"}],"url":"\/documentation\/chatroomuikit\/giftmessagecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"giftIcon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"giftIcon"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ImageView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ImageView","text":"ImageView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"giftIcon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell~1giftIcon\/title","value":"giftIcon"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell~1giftIcon\/fragments","value":[{"kind":"identifier","text":"giftIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/title","value":"GiftMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/fragments","value":[{"kind":"identifier","text":"GiftMessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}