{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ThemeStyle","text":"ThemeStyle"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ThemeStyle"},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"type":"text","text":" "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/theme\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/theme\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Theme\/switchTheme(style:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"title":"switchTheme(style:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)Theme(cm)switchThemeWithStyle:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Theme"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Theme":{"role":"symbol","title":"Theme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"type":"text","text":" "},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  "},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer ."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Theme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Theme"}],"url":"\/documentation\/chatroomuikit\/theme"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/chatroomuikit\/appearance"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ThemeStyle":{"role":"symbol","title":"ThemeStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}],"abstract":[{"type":"text","text":"Contain light and dark themes of the chat room UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"url":"\/documentation\/chatroomuikit\/themestyle"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/Theme/switchTheme(style:)":{"role":"symbol","title":"switchTheme(style:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/Theme\/switchTheme(style:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"url":"\/documentation\/chatroomuikit\/theme\/switchtheme(style:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"switchThemeWithStyle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"switchThemeWithStyle:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ThemeStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ThemeStyle","text":"ThemeStyle"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Theme\/title","value":"Theme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Theme\/fragments","value":[{"kind":"identifier","text":"Theme"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ThemeStyle\/fragments","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Theme~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1Theme~1switchTheme(style:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"switchThemeWithStyle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}