{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents","text":"SearchBarActionEvents"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchbar\/addactionhandler(handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/searchbar\/addactionhandler(handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar\/addActionHandler(handler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents"},{"kind":"text","text":")"}],"title":"addActionHandler(handler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)SearchBar(im)addActionHandlerWithHandler:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithHandler:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBarActionEvents":{"role":"symbol","title":"SearchBarActionEvents","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBarActionEvents"}],"abstract":[{"type":"text","text":"SearchBar action events"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchBarActionEvents"}],"url":"\/documentation\/chatroomuikit\/searchbaractionevents"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBar/addActionHandler(handler:)":{"role":"symbol","title":"addActionHandler(handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar\/addActionHandler(handler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithHandler:"}],"url":"\/documentation\/chatroomuikit\/searchbar\/addactionhandler(handler:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBar":{"role":"symbol","title":"SearchBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchBar"}],"url":"\/documentation\/chatroomuikit\/searchbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addActionHandlerWithHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addActionHandlerWithHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SearchBarActionEvents>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)SearchBarActionEvents"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/title","value":"SearchBarActionEvents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/fragments","value":[{"kind":"identifier","text":"SearchBarActionEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar~1addActionHandler(handler:)\/title","value":"addActionHandlerWithHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar~1addActionHandler(handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar\/title","value":"SearchBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar\/fragments","value":[{"kind":"identifier","text":"SearchBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}