{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents","text":"SearchBarActionEvents"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchbar\/removeeventhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar\/removeEventHandler(actionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents"},{"kind":"text","text":")"}],"title":"removeEventHandler(actionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:13ChatroomUIKit9SearchBarC18removeEventHandler06actionG0yAA0cD12ActionEvents_p_tF","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBar":{"role":"symbol","title":"SearchBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchBar"}],"url":"\/documentation\/chatroomuikit\/searchbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBar/removeEventHandler(actionHandler:)":{"role":"symbol","title":"removeEventHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchBarActionEvents","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)SearchBarActionEvents"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBar\/removeEventHandler(actionHandler:)","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/searchbar\/removeeventhandler(actionhandler:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchBarActionEvents":{"role":"symbol","title":"SearchBarActionEvents","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBarActionEvents"}],"abstract":[{"type":"text","text":"SearchBar action events"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchBarActionEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchBarActionEvents"}],"url":"\/documentation\/chatroomuikit\/searchbaractionevents"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar\/title","value":"SearchBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBar\/fragments","value":[{"kind":"identifier","text":"SearchBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/title","value":"SearchBarActionEvents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchBarActionEvents\/fragments","value":[{"kind":"identifier","text":"SearchBarActionEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}