{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScaleX"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsbarragelisttransformanimationdatasource\/zoomscalex()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsbarragelisttransformanimationdatasource\/zoomscalex()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageListTransformAnimationDataSource\/zoomScaleX()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An optional method that returns the zoom scale for the x-axis of the GiftsBarrageList."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"zoomScaleX"}],"role":"symbol","title":"zoomScaleX()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScaleX"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftsBarrageListTransformAnimationDataSource(im)zoomScaleX","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageListTransformAnimationDataSource"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageListTransformAnimationDataSource":{"role":"symbol","title":"GiftsBarrageListTransformAnimationDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsBarrageListTransformAnimationDataSource"}],"abstract":[{"type":"text","text":"A protocol that defines optional methods for transforming animations in the GiftsBarrageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageListTransformAnimationDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsBarrageListTransformAnimationDataSource"}],"url":"\/documentation\/chatroomuikit\/giftsbarragelisttransformanimationdatasource"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsBarrageListTransformAnimationDataSource/zoomScaleX()":{"navigatorTitle":[{"kind":"identifier","text":"zoomScaleX"}],"role":"symbol","title":"zoomScaleX()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScaleX"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional method that returns the zoom scale for the x-axis of the GiftsBarrageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsBarrageListTransformAnimationDataSource\/zoomScaleX()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftsbarragelisttransformanimationdatasource\/zoomscalex()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"zoomScaleX"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"zoomScaleX"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"zoomScaleX"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageListTransformAnimationDataSource\/title","value":"GiftsBarrageListTransformAnimationDataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageListTransformAnimationDataSource\/fragments","value":[{"kind":"identifier","text":"GiftsBarrageListTransformAnimationDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageListTransformAnimationDataSource~1zoomScaleX()\/title","value":"zoomScaleX"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsBarrageListTransformAnimationDataSource~1zoomScaleX()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"zoomScaleX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}