{"variants":[{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/ihorizontaltextcarouseldrive-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/ihorizontaltextcarouseldrive-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/IHorizontalTextCarouselDrive-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/showNewNotify(text:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IHorizontalTextCarouselDrive Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel":{"role":"symbol","title":"HorizontalTextCarousel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalTextCarousel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalTextCarousel"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel/showNewNotify(text:)":{"role":"symbol","title":"showNewNotify(text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Display text on received global notify message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/showNewNotify(text:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showNewNotifyWithText:"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel\/shownewnotify(text:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/showNewNotify(text:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/title","value":"HorizontalTextCarousel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/fragments","value":[{"kind":"identifier","text":"HorizontalTextCarousel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1showNewNotify(text:)\/title","value":"showNewNotifyWithText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1showNewNotify(text:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewNotifyWithText:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}