{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"originPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"originPoint","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HorizontalTextCarousel’s origin point."}]}]},{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HorizontalTextCarousel’s width."}]}]},{"name":"font","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HorizontalTextCarousel’s text font."}]}]},{"name":"textColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HorizontalTextCarousel’s text color."}]}]},{"name":"hiddenIcon","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether hidden icon or not."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/init(originpoint:width:font:textcolor:hiddenicon:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/init(originpoint:width:font:textcolor:hiddenicon:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/init(originPoint:width:font:textColor:hiddenIcon:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"HorizontalTextCarousel init method"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"originPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(originPoint:width:font:textColor:hiddenIcon:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ChatroomUIKit@objc(cs)HorizontalTextCarousel(im)initWithOriginPoint:width:font:textColor:hiddenIcon:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOriginPoint:width:font:textColor:hiddenIcon:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel":{"role":"symbol","title":"HorizontalTextCarousel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalTextCarousel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalTextCarousel"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel/init(originPoint:width:font:textColor:hiddenIcon:)":{"role":"symbol","title":"init(originPoint:width:font:textColor:hiddenIcon:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"originPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"HorizontalTextCarousel init method"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/init(originPoint:width:font:textColor:hiddenIcon:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOriginPoint:width:font:textColor:hiddenIcon:"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel\/init(originpoint:width:font:textcolor:hiddenicon:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithOriginPoint:width:font:textColor:hiddenIcon:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOriginPoint:width:font:textColor:hiddenIcon:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOriginPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"originPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"font:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"font"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenIcon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hiddenIcon"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/title","value":"HorizontalTextCarousel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/fragments","value":[{"kind":"identifier","text":"HorizontalTextCarousel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1init(originPoint:width:font:textColor:hiddenIcon:)\/title","value":"initWithOriginPoint:width:font:textColor:hiddenIcon:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1init(originPoint:width:font:textColor:hiddenIcon:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOriginPoint:width:font:textColor:hiddenIcon:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}