{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"show text"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/shownewnotify(text:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/horizontaltextcarousel\/shownewnotify(text:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/showNewNotify(text:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Display text on received global notify message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"showNewNotify(text:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)HorizontalTextCarousel(im)showNewNotifyWithText:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showNewNotifyWithText:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/IHorizontalTextCarouselDrive-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel/IHorizontalTextCarouselDrive-Implementations":{"role":"collectionGroup","title":"IHorizontalTextCarouselDrive Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/IHorizontalTextCarouselDrive-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/horizontaltextcarousel\/ihorizontaltextcarouseldrive-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel":{"role":"symbol","title":"HorizontalTextCarousel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalTextCarousel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalTextCarousel"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel/showNewNotify(text:)":{"role":"symbol","title":"showNewNotify(text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Display text on received global notify message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel\/showNewNotify(text:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showNewNotifyWithText:"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel\/shownewnotify(text:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showNewNotifyWithText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewNotifyWithText:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showNewNotifyWithText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/title","value":"HorizontalTextCarousel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/fragments","value":[{"kind":"identifier","text":"HorizontalTextCarousel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1showNewNotify(text:)\/title","value":"showNewNotifyWithText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel~1showNewNotify(text:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewNotifyWithText:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}