{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)MessageListActionEventsHandler","text":"MessageListActionEventsHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/messagelist\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/messagelist\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/addActionHandler(actionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add UI actions handler."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListActionEventsHandler","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)MessageListActionEventsHandler"},{"kind":"text","text":")"}],"title":"addActionHandler(actionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)MessageList(im)addActionHandlerWithActionHandler:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageList/addActionHandler(actionHandler:)":{"role":"symbol","title":"addActionHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListActionEventsHandler","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)MessageListActionEventsHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add UI actions handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/addActionHandler(actionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"url":"\/documentation\/chatroomuikit\/messagelist\/addactionhandler(actionhandler:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageListActionEventsHandler":{"role":"symbol","title":"MessageListActionEventsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListActionEventsHandler"}],"abstract":[{"type":"text","text":"MessageList action events handler."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageListActionEventsHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListActionEventsHandler"}],"url":"\/documentation\/chatroomuikit\/messagelistactioneventshandler"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageList":{"role":"symbol","title":"MessageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageList"}],"url":"\/documentation\/chatroomuikit\/messagelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MessageListActionEventsHandler>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)MessageListActionEventsHandler"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"actionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1addActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler\/title","value":"MessageListActionEventsHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageListActionEventsHandler\/fragments","value":[{"kind":"identifier","text":"MessageListActionEventsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList\/title","value":"MessageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList\/fragments","value":[{"kind":"identifier","text":"MessageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}