{"variants":[{"paths":["\/documentation\/chatroomuikit\/messagelist\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/messagelist\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewWillBeginDragging(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageList":{"role":"symbol","title":"MessageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageList"}],"url":"\/documentation\/chatroomuikit\/messagelist"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageList/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/chatroomuikit\/messagelist\/scrollviewwillbegindragging(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/MessageList/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/chatroomuikit\/messagelist\/scrollviewdidscroll(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/MessageList\/scrollViewWillBeginDragging(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList\/title","value":"MessageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList\/fragments","value":[{"kind":"identifier","text":"MessageList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1MessageList~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}