{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"empty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/EmptyStateView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)EmptyStateView","text":"EmptyStateView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/empty"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/empty","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"empty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EmptyStateView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)EmptyStateView"}],"title":"empty","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit32SearchParticipantsViewControllerC5emptyAA010EmptyStateE0Cvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController/empty":{"role":"symbol","title":"empty","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"empty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EmptyStateView","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)EmptyStateView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/empty","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/empty"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/EmptyStateView":{"role":"symbol","title":"EmptyStateView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmptyStateView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/EmptyStateView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmptyStateView"}],"url":"\/documentation\/chatroomuikit\/emptystateview"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController":{"role":"symbol","title":"SearchParticipantsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchParticipantsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchParticipantsViewController"}],"url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1EmptyStateView\/title","value":"EmptyStateView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1EmptyStateView\/fragments","value":[{"kind":"identifier","text":"EmptyStateView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/title","value":"SearchParticipantsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/fragments","value":[{"kind":"identifier","text":"SearchParticipantsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}