{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawSources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol","text":"UserInfoProtocol"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/rawsources"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/rawSources","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawSources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"]"}],"title":"rawSources","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit32SearchParticipantsViewControllerC10rawSourcesSayAA16UserInfoProtocol_pGvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController/rawSources":{"role":"symbol","title":"rawSources","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawSources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/rawSources","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/rawsources"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController":{"role":"symbol","title":"SearchParticipantsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchParticipantsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchParticipantsViewController"}],"url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserInfoProtocol":{"role":"symbol","title":"UserInfoProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserInfoProtocol"}],"url":"\/documentation\/chatroomuikit\/userinfoprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/title","value":"SearchParticipantsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/fragments","value":[{"kind":"identifier","text":"SearchParticipantsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/title","value":"UserInfoProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/fragments","value":[{"kind":"identifier","text":"UserInfoProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}