{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarCancelButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/searchbarcancelbuttonclicked(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/searchbarcancelbuttonclicked(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/searchBarCancelButtonClicked(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISearchBarDelegate.searchBarCancelButtonClicked(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"role":"symbol","title":"searchBarCancelButtonClicked(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarCancelButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)SearchParticipantsViewController(im)searchBarCancelButtonClicked:","extendedModule":"ChatroomUIKit","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/UISearchBarDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController/searchBarCancelButtonClicked(_:)":{"role":"symbol","title":"searchBarCancelButtonClicked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarCancelButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/searchBarCancelButtonClicked(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/searchbarcancelbuttonclicked(_:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController/UISearchBarDelegate-Implementations":{"role":"collectionGroup","title":"UISearchBarDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController\/UISearchBarDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller\/uisearchbardelegate-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/SearchParticipantsViewController":{"role":"symbol","title":"SearchParticipantsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchParticipantsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/SearchParticipantsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchParticipantsViewController"}],"url":"\/documentation\/chatroomuikit\/searchparticipantsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"searchBarCancelButtonClicked:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarCancelButtonClicked:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"searchBarCancelButtonClicked:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController~1searchBarCancelButtonClicked(_:)\/title","value":"searchBarCancelButtonClicked:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController~1searchBarCancelButtonClicked(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarCancelButtonClicked:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/title","value":"SearchParticipantsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1SearchParticipantsViewController\/fragments","value":[{"kind":"identifier","text":"SearchParticipantsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}