{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserIdentity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideuseridentity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideuseridentity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentity","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserIdentity"}],"title":"ChatMessageDisplayContentStyle.hideUserIdentity","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatroomUIKit@E@ChatMessageDisplayContentStyle@ChatMessageDisplayContentStyleHideUserIdentity","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle/hideUserIdentity":{"role":"symbol","title":"ChatMessageDisplayContentStyle.hideUserIdentity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserIdentity"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle\/hideUserIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle\/hideuseridentity"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageDisplayContentStyle":{"role":"symbol","title":"ChatMessageDisplayContentStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"abstract":[{"type":"text","text":"An enumeration that represents the different styles of a chat  cell.Time,level and avatar can be hidden"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageDisplayContentStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}],"url":"\/documentation\/chatroomuikit\/chatmessagedisplaycontentstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChatMessageDisplayContentStyleHideUserIdentity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentity\/title","value":"ChatMessageDisplayContentStyleHideUserIdentity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle~1hideUserIdentity\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyleHideUserIdentity"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/title","value":"ChatMessageDisplayContentStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageDisplayContentStyle\/fragments","value":[{"kind":"identifier","text":"ChatMessageDisplayContentStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}