{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionClosure","preciseIdentifier":"s:13ChatroomUIKit13ActionClosurea","text":"ActionClosure"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/actionsheetitemprotocol\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/actionsheetitemprotocol\/action"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol\/action","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The closure to be executed when the action sheet item is selected."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"action"}],"role":"symbol","title":"action","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionClosure","preciseIdentifier":"s:13ChatroomUIKit13ActionClosurea"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol(py)action","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemProtocol":{"role":"symbol","title":"ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/chatroomuikit\/actionsheetitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionClosure":{"role":"symbol","title":"ActionClosure","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionClosure"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionClosure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionClosure"}],"url":"\/documentation\/chatroomuikit\/actionclosure"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemProtocol/action":{"navigatorTitle":[{"kind":"identifier","text":"action"}],"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionClosure","preciseIdentifier":"s:13ChatroomUIKit13ActionClosurea"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The closure to be executed when the action sheet item is selected."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol\/action","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/actionsheetitemprotocol\/action"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"action"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(id<ActionSheetItemProtocol>)","preciseIdentifier":"c:BFv(#*Qo@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol)"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol~1action\/fragments","value":[{"kind":"identifier","text":"action"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}