{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ActionSheetItemType","text":"ActionSheetItemType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/actionsheetitemprotocol\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/actionsheetitemprotocol\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the action sheet item."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemType"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","title":"type","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionSheetItemType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ActionSheetItemType"}],"symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(pl)ActionSheetItemProtocol(py)type","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemType":{"role":"symbol","title":"ActionSheetItemType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemType"}],"abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemType"}],"url":"\/documentation\/chatroomuikit\/actionsheetitemtype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemProtocol":{"role":"symbol","title":"ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/chatroomuikit\/actionsheetitemprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ActionSheetItemProtocol/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionSheetItemType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ActionSheetItemType"}],"abstract":[{"type":"text","text":"The type of the action sheet item."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemType"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemProtocol\/type","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/actionsheetitemprotocol\/type"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ActionSheetItemType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ActionSheetItemType","text":"ActionSheetItemType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemType\/title","value":"ActionSheetItemType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemType\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ActionSheetItemProtocol~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}