{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserMuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusermuted(roomid:userid:operatorid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusermuted(roomid:userid:operatorid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserMuted(roomId:userId:operatorId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RoomEventsListener.onUserMuted(roomId:userId:operatorId:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserMuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"onUserMuted(roomId:userId:operatorId:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit_Example@objc(cs)UIWithBusinessViewController(im)onUserMutedWithRoomId:userId:operatorId:","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/RoomEventsListener-Implementations"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserMuted(roomId:userId:operatorId:)":{"role":"symbol","title":"onUserMuted(roomId:userId:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserMuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserMuted(roomId:userId:operatorId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusermuted(roomid:userid:operatorid:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/RoomEventsListener-Implementations":{"role":"collectionGroup","title":"RoomEventsListener Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/RoomEventsListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/roomeventslistener-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController":{"role":"symbol","title":"UIWithBusinessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIWithBusinessViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIWithBusinessViewController"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onUserMutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserMutedWithRoomId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"roomId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"operatorId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserMuted(roomId:userId:operatorId:)\/title","value":"onUserMutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserMuted(roomId:userId:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/title","value":"UIWithBusinessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/fragments","value":[{"kind":"identifier","text":"UIWithBusinessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}