{"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/roomeventslistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/roomeventslistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/RoomEventsListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onAnnouncementUpdate(roomId:announcement:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onErrorOccur(error:type:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onReceiveGlobalNotify(message:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onSocketConnectionStateChanged(state:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserBeKicked(roomId:reason:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserJoined(roomId:user:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLeave(roomId:userId:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLoginOtherDevice(device:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserMuted(roomId:userId:operatorId:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenDidExpired()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenWillExpired()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserUnmuted(roomId:userId:operatorId:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit_Example"}],"role":"collectionGroup","title":"RoomEventsListener Implementations"},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserJoined(roomId:user:)":{"role":"symbol","title":"onUserJoined(roomId:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserJoined"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserJoined(roomId:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserJoinedWithRoomId:user:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onuserjoined(roomid:user:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onSocketConnectionStateChanged(state:)":{"role":"symbol","title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onSocketConnectionStateChanged(state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onsocketconnectionstatechanged(state:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onErrorOccur(error:type:)":{"role":"symbol","title":"onErrorOccur(error:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onErrorOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RoomEventsError","preciseIdentifier":"c:@M@ChatroomUIKit@E@RoomEventsError"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onErrorOccur(error:type:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onErrorOccurWithError:type:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onerroroccur(error:type:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserMuted(roomId:userId:operatorId:)":{"role":"symbol","title":"onUserMuted(roomId:userId:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserMuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserMuted(roomId:userId:operatorId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusermuted(roomid:userid:operatorid:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserLoginOtherDevice(device:)":{"role":"symbol","title":"onUserLoginOtherDevice(device:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLoginOtherDevice(device:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onuserloginotherdevice(device:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController":{"role":"symbol","title":"UIWithBusinessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIWithBusinessViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIWithBusinessViewController"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserLeave(roomId:userId:)":{"role":"symbol","title":"onUserLeave(roomId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLeave"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLeave(roomId:userId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserLeaveWithRoomId:userId:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onuserleave(roomid:userid:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserBeKicked(roomId:reason:)":{"role":"symbol","title":"onUserBeKicked(roomId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserBeKicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatroomBeKickedReason","preciseIdentifier":"s:13ChatroomUIKit0A14BeKickedReasona"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserBeKicked(roomId:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserBeKickedWithRoomId:reason:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onuserbekicked(roomid:reason:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserTokenDidExpired()":{"role":"symbol","title":"onUserTokenDidExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenDidExpired"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenDidExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusertokendidexpired()"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserTokenWillExpired()":{"role":"symbol","title":"onUserTokenWillExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenWillExpired"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenWillExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenWillExpired"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onusertokenwillexpired()"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onAnnouncementUpdate(roomId:announcement:)":{"role":"symbol","title":"onAnnouncementUpdate(roomId:announcement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAnnouncementUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onAnnouncementUpdate(roomId:announcement:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAnnouncementUpdateWithRoomId:announcement:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onannouncementupdate(roomid:announcement:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onReceiveGlobalNotify(message:)":{"role":"symbol","title":"onReceiveGlobalNotify(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceiveGlobalNotify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onReceiveGlobalNotify(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onReceiveGlobalNotifyWithMessage:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onreceiveglobalnotify(message:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIWithBusinessViewController/onUserUnmuted(roomId:userId:operatorId:)":{"role":"symbol","title":"onUserUnmuted(roomId:userId:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserUnmuted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserUnmuted(roomId:userId:operatorId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:operatorId:"}],"url":"\/documentation\/chatroomuikit_example\/uiwithbusinessviewcontroller\/onuserunmuted(roomid:userid:operatorid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onAnnouncementUpdate(roomId:announcement:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onErrorOccur(error:type:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onReceiveGlobalNotify(message:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onSocketConnectionStateChanged(state:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserBeKicked(roomId:reason:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserJoined(roomId:user:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLeave(roomId:userId:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserLoginOtherDevice(device:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserMuted(roomId:userId:operatorId:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenDidExpired()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserTokenWillExpired()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIWithBusinessViewController\/onUserUnmuted(roomId:userId:operatorId:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserJoined(roomId:user:)\/title","value":"onUserJoinedWithRoomId:user:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserJoined(roomId:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinedWithRoomId:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onSocketConnectionStateChanged(state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onErrorOccur(error:type:)\/title","value":"onErrorOccurWithError:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onErrorOccur(error:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorOccurWithError:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserMuted(roomId:userId:operatorId:)\/title","value":"onUserMutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserMuted(roomId:userId:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserMutedWithRoomId:userId:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserLoginOtherDevice(device:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/title","value":"UIWithBusinessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController\/fragments","value":[{"kind":"identifier","text":"UIWithBusinessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserLeave(roomId:userId:)\/title","value":"onUserLeaveWithRoomId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserLeave(roomId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLeaveWithRoomId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserBeKicked(roomId:reason:)\/title","value":"onUserBeKickedWithRoomId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserBeKicked(roomId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserBeKickedWithRoomId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserTokenDidExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserTokenWillExpired()\/title","value":"onUserTokenWillExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserTokenWillExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenWillExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onAnnouncementUpdate(roomId:announcement:)\/title","value":"onAnnouncementUpdateWithRoomId:announcement:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onAnnouncementUpdate(roomId:announcement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAnnouncementUpdateWithRoomId:announcement:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onReceiveGlobalNotify(message:)\/title","value":"onReceiveGlobalNotifyWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onReceiveGlobalNotify(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReceiveGlobalNotifyWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserUnmuted(roomId:userId:operatorId:)\/title","value":"onUserUnmutedWithRoomId:userId:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIWithBusinessViewController~1onUserUnmuted(roomId:userId:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserUnmutedWithRoomId:userId:operatorId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}