{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatsCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatMessageCell","text":"ChatMessageCell"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/componentsregister\/chatscell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/componentsregister\/chatscell"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/ChatsCell","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chatroom chat list cell class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatsCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatMessageCell"},{"kind":"text","text":".Type"}],"title":"ChatsCell","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)ComponentsRegister(py)ChatsCell","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatsCell"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/ChatsCell":{"role":"symbol","title":"ChatsCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatsCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatMessageCell"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Chatroom chat list cell class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/ChatsCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatsCell"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/chatscell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatMessageCell":{"role":"symbol","title":"ChatMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display chat messages as a content display style of the cell."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessageCell"}],"url":"\/documentation\/chatroomuikit\/chatmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the ChatroomUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/chatroomuikit\/componentsregister"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ChatsCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatsCell"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatsCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1ChatsCell\/title","value":"ChatsCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1ChatsCell\/fragments","value":[{"kind":"identifier","text":"ChatsCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/title","value":"ChatMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}