{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessagesViewCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageCell","text":"GiftMessageCell"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/componentsregister\/giftmessagesviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/componentsregister\/giftmessagesviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftMessagesViewCell","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gift message area list cell class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessagesViewCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageCell"},{"kind":"text","text":".Type"}],"title":"GiftMessagesViewCell","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)ComponentsRegister(py)GiftMessagesViewCell","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GiftMessagesViewCell"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageCell":{"role":"symbol","title":"GiftMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageCell"}],"abstract":[{"type":"text","text":"A UITableViewCell subclass used to display a gift item in a  view."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageCell"}],"url":"\/documentation\/chatroomuikit\/giftmessagecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the ChatroomUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/chatroomuikit\/componentsregister"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/GiftMessagesViewCell":{"role":"symbol","title":"GiftMessagesViewCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessagesViewCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftMessageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftMessageCell"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Gift message area list cell class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftMessagesViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessagesViewCell"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/giftmessagesviewcell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"GiftMessagesViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GiftMessagesViewCell"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessagesViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/title","value":"GiftMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageCell\/fragments","value":[{"kind":"identifier","text":"GiftMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftMessagesViewCell\/title","value":"GiftMessagesViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftMessagesViewCell\/fragments","value":[{"kind":"identifier","text":"GiftMessagesViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}