{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showParticipantsDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol","text":"UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"muteMoreClosure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol","text":"UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"moreClosure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback you want to operator user info on click "},{"type":"codeVoice","code":"..."},{"type":"text","text":"."}]}]},{"name":"muteMoreClosure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback you want to operator user  info  on click "},{"type":"codeVoice","code":"..."},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/dialogmanager\/showparticipantsdialog(moreclosure:mutemoreclosure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/dialogmanager\/showparticipantsdialog(moreclosure:mutemoreclosure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showParticipantsDialog(moreClosure:muteMoreClosure:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Participants list dialog will show on call the method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showParticipantsDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"muteMoreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"showParticipantsDialog(moreClosure:muteMoreClosure:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)DialogManager(im)showParticipantsDialogWithMoreClosure:muteMoreClosure:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager":{"role":"symbol","title":"DialogManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DialogManager"}],"url":"\/documentation\/chatroomuikit\/dialogmanager"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/DialogManager/showParticipantsDialog(moreClosure:muteMoreClosure:)":{"role":"symbol","title":"showParticipantsDialog(moreClosure:muteMoreClosure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showParticipantsDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"moreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"muteMoreClosure"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UserInfoProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)UserInfoProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Participants list dialog will show on call the method."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/DialogManager\/showParticipantsDialog(moreClosure:muteMoreClosure:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}],"url":"\/documentation\/chatroomuikit\/dialogmanager\/showparticipantsdialog(moreclosure:mutemoreclosure:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/UserInfoProtocol":{"role":"symbol","title":"UserInfoProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/UserInfoProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserInfoProtocol"}],"url":"\/documentation\/chatroomuikit\/userinfoprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<UserInfoProtocol>)","preciseIdentifier":"c:BFv(#*Qo@M@ChatroomUIKit@objc(pl)UserInfoProtocol)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"moreClosure"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteMoreClosure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<UserInfoProtocol>)","preciseIdentifier":"c:BFv(#*Qo@M@ChatroomUIKit@objc(pl)UserInfoProtocol)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"muteMoreClosure"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager\/title","value":"DialogManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager\/fragments","value":[{"kind":"identifier","text":"DialogManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showParticipantsDialog(moreClosure:muteMoreClosure:)\/title","value":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1DialogManager~1showParticipantsDialog(moreClosure:muteMoreClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showParticipantsDialogWithMoreClosure:muteMoreClosure:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/title","value":"UserInfoProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1UserInfoProtocol\/fragments","value":[{"kind":"identifier","text":"UserInfoProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}