{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"kind":"text","text":" "},{"kind":"internalParam","text":"updateItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"kind":"text","text":"])"}],"title":"prepare(forCollectionViewUpdates:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)ChoiceItemLayout(im)prepareForCollectionViewUpdates:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChoiceItemLayout"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChoiceItemLayout":{"role":"symbol","title":"ChoiceItemLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"abstract":[{"type":"text","text":"Choice layout"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChoiceItemLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"url":"\/documentation\/chatroomuikit\/choiceitemlayout"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChoiceItemLayout/prepare(forCollectionViewUpdates:)":{"role":"symbol","title":"prepare(forCollectionViewUpdates:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}],"url":"\/documentation\/chatroomuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareForCollectionViewUpdates:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<UICollectionViewUpdateItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"updateItems"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChoiceItemLayout\/title","value":"ChoiceItemLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChoiceItemLayout\/fragments","value":[{"kind":"identifier","text":"ChoiceItemLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/title","value":"prepareForCollectionViewUpdates:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}