{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftmessagelisttransformanimationdatasource\/rowheight()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftmessagelisttransformanimationdatasource\/rowheight()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageListTransformAnimationDataSource\/rowHeight()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An optional method that returns the row height for the GiftMessageList."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rowHeight"}],"role":"symbol","title":"rowHeight()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftMessageListTransformAnimationDataSource(im)rowHeight","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageListTransformAnimationDataSource"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageListTransformAnimationDataSource":{"role":"symbol","title":"GiftMessageListTransformAnimationDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftMessageListTransformAnimationDataSource"}],"abstract":[{"type":"text","text":"A protocol that defines optional methods for transforming animations in the GiftMessageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageListTransformAnimationDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftMessageListTransformAnimationDataSource"}],"url":"\/documentation\/chatroomuikit\/giftmessagelisttransformanimationdatasource"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftMessageListTransformAnimationDataSource/rowHeight()":{"navigatorTitle":[{"kind":"identifier","text":"rowHeight"}],"role":"symbol","title":"rowHeight()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional method that returns the row height for the GiftMessageList."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftMessageListTransformAnimationDataSource\/rowHeight()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/giftmessagelisttransformanimationdatasource\/rowheight()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rowHeight"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rowHeight"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageListTransformAnimationDataSource\/title","value":"GiftMessageListTransformAnimationDataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageListTransformAnimationDataSource\/fragments","value":[{"kind":"identifier","text":"GiftMessageListTransformAnimationDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageListTransformAnimationDataSource~1rowHeight()\/title","value":"rowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftMessageListTransformAnimationDataSource~1rowHeight()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rowHeight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}