{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomOperating"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomOperationType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatroomOperationType","text":"ChatroomOperationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"roomId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"chatroom id"}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"user id"}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ChatroomOperationType"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback,what if success or error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomservice\/chatroomoperating(roomid:userid:type:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomservice\/chatroomoperating(roomid:userid:type:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomService\/chatroomOperating(roomId:userId:type:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chatroom operation events."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"chatroomOperatingWithRoomId:userId:type:completion:"}],"role":"symbol","title":"chatroomOperating(roomId:userId:type:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomOperating"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomOperationType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatroomOperationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)ChatroomService(im)chatroomOperatingWithRoomId:userId:type:completion:","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomService"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/chatroomuikit\/chaterror"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomService":{"role":"symbol","title":"ChatroomService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomService"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomService"}],"url":"\/documentation\/chatroomuikit\/chatroomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomOperationType":{"role":"symbol","title":"ChatroomOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomOperationType"}],"abstract":[{"type":"text","text":"Chatroom operation events.Ext,leave or join."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomOperationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomOperationType"}],"url":"\/documentation\/chatroomuikit\/chatroomoperationtype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomService/chatroomOperating(roomId:userId:type:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"chatroomOperatingWithRoomId:userId:type:completion:"}],"role":"symbol","title":"chatroomOperating(roomId:userId:type:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomOperating"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomOperationType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatroomOperationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Chatroom operation events."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomService\/chatroomOperating(roomId:userId:type:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/chatroomservice\/chatroomoperating(roomid:userid:type:completion:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"chatroomOperatingWithRoomId:userId:type:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomOperatingWithRoomId:userId:type:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"chatroomOperatingWithRoomId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"roomId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomOperationType","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatroomOperationType","text":"ChatroomOperationType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool, EMError *)","preciseIdentifier":"c:BFv(#b#*$objc(cs)EMError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomService\/title","value":"ChatroomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomService\/fragments","value":[{"kind":"identifier","text":"ChatroomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomOperationType\/title","value":"ChatroomOperationType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomOperationType\/fragments","value":[{"kind":"identifier","text":"ChatroomOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomService~1chatroomOperating(roomId:userId:type:completion:)\/title","value":"chatroomOperatingWithRoomId:userId:type:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomService~1chatroomOperating(roomId:userId:type:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomOperatingWithRoomId:userId:type:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}