{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea","text":"ConnectionState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ConnectionState"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/onsocketconnectionstatechanged(state:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/onsocketconnectionstatechanged(state:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onSocketConnectionStateChanged(state:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chatroom socket connection state changed listener."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"title":"onSocketConnectionStateChanged(state:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomUIKitClient(im)onSocketConnectionStateChangedWithState:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/onSocketConnectionStateChanged(state:)":{"role":"symbol","title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Chatroom socket connection state changed listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onSocketConnectionStateChanged(state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/onsocketconnectionstatechanged(state:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ConnectionState":{"role":"symbol","title":"ConnectionState","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionState"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionState"}],"url":"\/documentation\/chatroomuikit\/connectionstate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/UserStateChangedListener-Implementations":{"role":"collectionGroup","title":"UserStateChangedListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/userstatechangedlistener-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMConnectionState","preciseIdentifier":"c:@E@EMConnectionState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onSocketConnectionStateChanged(state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}