{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"token"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/refreshtoken(token:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/refreshtoken(token:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/refreshToken(token:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When you’ll fetch new token from your app server on receive "},{"type":"codeVoice","code":"RoomEventsListener.onUserTokenWillExpired"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"refreshToken(token:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitClient(im)refreshTokenWithToken:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"refreshTokenWithToken:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/refreshToken(token:)":{"role":"symbol","title":"refreshToken(token:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When you’ll fetch new token from your app server on receive "},{"type":"codeVoice","code":"RoomEventsListener.onUserTokenWillExpired"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/refreshToken(token:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshTokenWithToken:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/refreshtoken(token:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshTokenWithToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshTokenWithToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshTokenWithToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1refreshToken(token:)\/title","value":"refreshTokenWithToken:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1refreshToken(token:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshTokenWithToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}