{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(setupWithAppkey:option:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitInitialOptions","text":"ChatroomUIKitInitialOptions"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitInitialOptions\/ChatOptions","preciseIdentifier":"s:13ChatroomUIKit0aB14InitialOptionsC04ChatD0C","text":"ChatOptions"},{"kind":"text","text":" = ChatroomUIKitInitialOptions.ChatOptions()) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora","text":"ChatError"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"appKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier that Chat assigns to each app. For details, see https:\/\/docs.agora.io\/en\/agora-chat\/get-started\/enable?platform=ios#get-chat-project-information."},{"type":"text","text":" "},{"type":"text","text":"Returns the initialization success or an error that includes the description of the cause of the failure."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/setup(appkey:option:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/setup(appkey:option:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/setup(appKey:option:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the chat room UIKit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitInitialOptions"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"s:13ChatroomUIKit0aB14InitialOptionsC04ChatD0C"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?"}],"title":"setup(appKey:option:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitClient(im)setupWithAppkey:option:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setupWithAppkey:option:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitInitialOptions":{"role":"symbol","title":"ChatroomUIKitInitialOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitInitialOptions"}],"abstract":[{"type":"text","text":"A wrapper class for some options to be set during initialization of ChatroomUIKit.ChatroomView."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitInitialOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitInitialOptions"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitinitialoptions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialization class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/chatroomuikit\/chaterror"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitInitialOptions/ChatOptions":{"role":"symbol","title":"ChatroomUIKitInitialOptions.ChatOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatOptions"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitInitialOptions\/ChatOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatOptions"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitinitialoptions\/chatoptions"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/setup(appKey:option:)":{"role":"symbol","title":"setup(appKey:option:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomUIKitInitialOptions"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"s:13ChatroomUIKit0aB14InitialOptionsC04ChatD0C"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Initializes the chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/setup(appKey:option:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWithAppkey:option:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/setup(appkey:option:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setupWithAppkey:option:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupWithAppkey:option:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"EMError","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"setupWithAppkey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"option:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"c:objc(cs)ChatOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"option"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitInitialOptions\/title","value":"ChatroomUIKitInitialOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitInitialOptions\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitInitialOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1setup(appKey:option:)\/title","value":"setupWithAppkey:option:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1setup(appKey:option:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupWithAppkey:option:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}