{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForcedToLogout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora","text":"ChatError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/useraccountdidforcedtologout(error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/useraccountdidforcedtologout(error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/userAccountDidForcedToLogout(error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user account logout by server."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForcedToLogout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"title":"userAccountDidForcedToLogout(error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit@objc(cs)ChatroomUIKitClient(im)userAccountDidForcedToLogoutWithError:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogoutWithError:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialization class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/UserStateChangedListener-Implementations":{"role":"collectionGroup","title":"UserStateChangedListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/userstatechangedlistener-implementations"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/chatroomuikit\/chaterror"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/userAccountDidForcedToLogout(error:)":{"role":"symbol","title":"userAccountDidForcedToLogout(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForcedToLogout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The user account logout by server."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/userAccountDidForcedToLogout(error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogoutWithError:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/useraccountdidforcedtologout(error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userAccountDidForcedToLogoutWithError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidForcedToLogoutWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userAccountDidForcedToLogoutWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMError","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1userAccountDidForcedToLogout(error:)\/title","value":"userAccountDidForcedToLogoutWithError:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1userAccountDidForcedToLogout(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidForcedToLogoutWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}