{"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/userstatechangedlistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomuikitclient\/userstatechangedlistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/UserStateChangedListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenWillExpired()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UserStateChangedListener Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/onUserTokenDidExpired()":{"role":"symbol","title":"onUserTokenDidExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenDidExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"User token expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenDidExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/onusertokendidexpired()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient":{"role":"symbol","title":"ChatroomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomUIKitClient"}],"abstract":[{"type":"text","text":"ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/onSocketConnectionStateChanged(state:)":{"role":"symbol","title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Chatroom socket connection state changed listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onSocketConnectionStateChanged(state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/onsocketconnectionstatechanged(state:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/onUserLoginOtherDevice(device:)":{"role":"symbol","title":"onUserLoginOtherDevice(device:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"User login at other device"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserLoginOtherDevice(device:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/onuserloginotherdevice(device:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomUIKitClient/onUserTokenWillExpired()":{"role":"symbol","title":"onUserTokenWillExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenWillExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"User token will expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenWillExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenWillExpired"}],"url":"\/documentation\/chatroomuikit\/chatroomuikitclient\/onusertokenwillexpired()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomUIKitClient\/onUserTokenWillExpired()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserTokenDidExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/title","value":"ChatroomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatroomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onSocketConnectionStateChanged(state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserLoginOtherDevice(device:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserTokenWillExpired()\/title","value":"onUserTokenWillExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomUIKitClient~1onUserTokenWillExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenWillExpired"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}