{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextMenuInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIContextMenuInteraction","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurationForMenuAtLocation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIContextMenuConfiguration","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/contextmenuinteraction(_:configurationformenuatlocation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/contextmenuinteraction(_:configurationformenuatlocation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/contextMenuInteraction(_:configurationForMenuAtLocation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIContextMenuInteractionDelegate.contextMenuInteraction(_:configurationForMenuAtLocation:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIContextMenuInteraction","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurationForMenuAtLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIContextMenuConfiguration","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration"},{"kind":"text","text":"?"}],"title":"contextMenuInteraction(_:configurationForMenuAtLocation:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit_Example@objc(cs)UIComponentsExampleViewController(im)contextMenuInteraction:configurationForMenuAtLocation:","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/UIContextMenuInteractionDelegate-Implementations"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/contextMenuInteraction(_:configurationForMenuAtLocation:)":{"role":"symbol","title":"contextMenuInteraction(_:configurationForMenuAtLocation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIContextMenuInteraction","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurationForMenuAtLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIContextMenuConfiguration","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/contextMenuInteraction(_:configurationForMenuAtLocation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/contextmenuinteraction(_:configurationformenuatlocation:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/UIContextMenuInteractionDelegate-Implementations":{"role":"collectionGroup","title":"UIContextMenuInteractionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/UIContextMenuInteractionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/uicontextmenuinteractiondelegate-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"contextMenuInteraction:configurationForMenuAtLocation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIContextMenuConfiguration","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"contextMenuInteraction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIContextMenuInteraction","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationForMenuAtLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1contextMenuInteraction(_:configurationForMenuAtLocation:)\/title","value":"contextMenuInteraction:configurationForMenuAtLocation:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1contextMenuInteraction(_:configurationForMenuAtLocation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}