{"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/giftsviewactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/giftsviewactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSelected(item:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSendClick(item:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit_Example"}],"role":"collectionGroup","title":"GiftsViewActionEventsDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/onGiftSelected(item:)":{"role":"symbol","title":"onGiftSelected(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSelected(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGiftSelectedWithItem:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/ongiftselected(item:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/onGiftSendClick(item:)":{"role":"symbol","title":"onGiftSendClick(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSendClick(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGiftSendClickWithItem:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/ongiftsendclick(item:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSelected(item:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSendClick(item:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSelected(item:)\/title","value":"onGiftSelectedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSelected(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSelectedWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSendClick(item:)\/title","value":"onGiftSendClickWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSendClick(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSendClickWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}