{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/onbottomitemclicked(item:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/onbottomitemclicked(item:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onBottomItemClicked(item:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ChatBottomFunctionBarActionEvents.onBottomItemClicked(item:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onBottomItemClickedWithItem:"}],"role":"symbol","title":"onBottomItemClicked(item:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@ChatroomUIKit_Example@objc(cs)UIComponentsExampleViewController(im)onBottomItemClickedWithItem:","extendedModule":"ChatroomUIKit_Example","modules":[{"name":"ChatroomUIKit_Example"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/ChatBottomFunctionBarActionEvents-Implementations"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/ChatBottomFunctionBarActionEvents-Implementations":{"role":"collectionGroup","title":"ChatBottomFunctionBarActionEvents Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/ChatBottomFunctionBarActionEvents-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/chatbottomfunctionbaractionevents-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/onBottomItemClicked(item:)":{"role":"symbol","title":"onBottomItemClicked(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBottomItemClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onBottomItemClicked(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBottomItemClickedWithItem:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/onbottomitemclicked(item:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onBottomItemClickedWithItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBottomItemClickedWithItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onBottomItemClickedWithItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChatBottomItemProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onBottomItemClicked(item:)\/title","value":"onBottomItemClickedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onBottomItemClicked(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBottomItemClickedWithItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}