{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/ongiftselected(item:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/ongiftselected(item:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSelected(item:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GiftsViewActionEventsDelegate.onGiftSelected(item:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"title":"onGiftSelected(item:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ChatroomUIKit_Example@objc(cs)UIComponentsExampleViewController(im)onGiftSelectedWithItem:","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"onGiftSelectedWithItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/onGiftSelected(item:)":{"role":"symbol","title":"onGiftSelected(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/onGiftSelected(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGiftSelectedWithItem:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/ongiftselected(item:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/GiftsViewActionEventsDelegate-Implementations":{"role":"collectionGroup","title":"GiftsViewActionEventsDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/giftsviewactioneventsdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onGiftSelectedWithItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSelectedWithItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onGiftSelectedWithItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftEntityProtocol>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSelected(item:)\/title","value":"onGiftSelectedWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1onGiftSelected(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSelectedWithItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}