{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@UIApplicationMain"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/appdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/appdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH","doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIApplicationDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillTerminate(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/UIApplicationDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"title":"AppDelegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)AppDelegate","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/appdelegate\/uiapplicationdelegate-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/window":{"role":"symbol","title":"window","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"window"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/window"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/init"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/applicationDidEnterBackground(_:)":{"role":"symbol","title":"applicationDidEnterBackground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidEnterBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidEnterBackground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidEnterBackground:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/applicationdidenterbackground(_:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/applicationWillResignActive(_:)":{"role":"symbol","title":"applicationWillResignActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillResignActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillResignActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillResignActive:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/applicationwillresignactive(_:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"role":"symbol","title":"application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplicationLaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/applicationWillTerminate(_:)":{"role":"symbol","title":"applicationWillTerminate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillTerminate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillTerminate:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/applicationwillterminate(_:)"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/applicationWillEnterForeground(_:)":{"role":"symbol","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillEnterForeground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/applicationwillenterforeground(_:)"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/AppDelegate/applicationDidBecomeActive(_:)":{"role":"symbol","title":"applicationDidBecomeActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidBecomeActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidBecomeActive:"}],"url":"\/documentation\/chatroomuikit_example\/appdelegate\/applicationdidbecomeactive(_:)"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIApplicationDelegate":{"type":"unresolvable","title":"UIApplicationDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIApplicationDelegate"},"doc://com.easemob.chatroomuikit.demo/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP"},"doc://com.easemob.chatroomuikit.demo/objc(cs)UIResponder":{"type":"unresolvable","title":"UIResponder","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIResponder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/applicationWillTerminate(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/AppDelegate\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIApplicationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIResponder","preciseIdentifier":"c:objc(cs)UIResponder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1window\/title","value":"window"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationDidEnterBackground(_:)\/title","value":"applicationDidEnterBackground:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationDidEnterBackground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidEnterBackground:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillResignActive(_:)\/title","value":"applicationWillResignActive:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillResignActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillResignActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillTerminate(_:)\/title","value":"applicationWillTerminate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillTerminate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillTerminate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillEnterForeground(_:)\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationWillEnterForeground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationDidBecomeActive(_:)\/title","value":"applicationDidBecomeActive:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1AppDelegate~1applicationDidBecomeActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidBecomeActive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}