{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/chatroomcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/chatroomcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)CALayerDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH","doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearance","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UICoordinateSpace","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIDynamicItem","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusItem","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusItemContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UILargeContentViewerItem","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(coder:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(style:reuseIdentifier:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomCell"}],"title":"ChatroomCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)ChatroomCell","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"ChatroomCell"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusItemContainer"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearance"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)CALayerDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatroomCell":{"role":"symbol","title":"ChatroomCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomCell"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomCell"}],"url":"\/documentation\/chatroomuikit_example\/chatroomcell"},"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitChangeObservable":{"type":"unresolvable","title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"},"doc://com.easemob.chatroomuikit.demo/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatroomCell/init(style:reuseIdentifier:)":{"role":"symbol","title":"init(style:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(style:reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/chatroomuikit_example\/chatroomcell\/init(style:reuseidentifier:)"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatroomCell/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit_example\/chatroomcell\/init(coder:)"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIDynamicItem"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding"},"doc://com.easemob.chatroomuikit.demo/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UITableViewCell"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UICoordinateSpace"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusItem"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UILargeContentViewerItem"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAccessibilityIdentification"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatroomCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatroomCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatroomCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(coder:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatroomCell\/init(style:reuseIdentifier:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell\/title","value":"ChatroomCell"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell\/fragments","value":[{"kind":"identifier","text":"ChatroomCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell~1init(style:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatroomCell~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}