{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/chatbottomitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/chatbottomitem"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/action","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/normalImage","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selected","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selectedImage","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/showRedDot","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/type"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"}],"title":"ChatBottomItem","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)ChatBottomItem","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"ChatBottomItem"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/action":{"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": ((ChatroomUIKit"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/action","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/action"},"doc://com.easemob.chatroomuikit.demo/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)NSObject"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/showRedDot":{"role":"symbol","title":"showRedDot","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showRedDot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/showRedDot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showRedDot"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/showreddot"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/type"},"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol":{"type":"unresolvable","title":"ChatBottomItemProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/normalImage":{"role":"symbol","title":"normalImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/normalImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"normalImage"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/normalimage"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/selectedImage":{"role":"symbol","title":"selectedImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selectedImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedImage"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/selectedimage"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/init"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/selected":{"role":"symbol","title":"selected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selected"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/selected"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem":{"role":"symbol","title":"ChatBottomItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItem"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatBottomItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatBottomItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatBottomItem"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/action","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/normalImage","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selected","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/selectedImage","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/showRedDot","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1action\/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1showRedDot\/title","value":"showRedDot"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1showRedDot\/fragments","value":[{"kind":"identifier","text":"showRedDot"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1normalImage\/title","value":"normalImage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1normalImage\/fragments","value":[{"kind":"identifier","text":"normalImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1selectedImage\/title","value":"selectedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1selectedImage\/fragments","value":[{"kind":"identifier","text":"selectedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1selected\/title","value":"selected"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1selected\/fragments","value":[{"kind":"identifier","text":"selected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/title","value":"ChatBottomItem"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/fragments","value":[{"kind":"identifier","text":"ChatBottomItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}