{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MineGiftsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/minegiftsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/minegiftsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(cs)GiftsViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH","doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/onGiftSendClick(item:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MineGiftsViewController"}],"title":"MineGiftsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)MineGiftsViewController","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"MineGiftsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/MineGiftsViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/chatroomuikit_example\/minegiftsviewcontroller\/initwithnibname:bundle:"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/MineGiftsViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit_example\/minegiftsviewcontroller\/initwithcoder:"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding"},"doc://com.easemob.chatroomuikit.demo/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitChangeObservable":{"type":"unresolvable","title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/MineGiftsViewController":{"role":"symbol","title":"MineGiftsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MineGiftsViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MineGiftsViewController"}],"url":"\/documentation\/chatroomuikit_example\/minegiftsviewcontroller"},"doc://com.easemob.chatroomuikit.demo/@M@ChatroomUIKit@objc(cs)GiftsViewController":{"type":"unresolvable","title":"_TtC13ChatroomUIKit19GiftsViewController","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(cs)GiftsViewController"},"doc://com.easemob.chatroomuikit.demo/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate":{"type":"unresolvable","title":"ChatroomUIKit.GiftsViewActionEventsDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/MineGiftsViewController/onGiftSendClick(item:)":{"role":"symbol","title":"onGiftSendClick(item:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGiftSendClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/onGiftSendClick(item:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGiftSendClickWithItem:"}],"url":"\/documentation\/chatroomuikit_example\/minegiftsviewcontroller\/ongiftsendclick(item:)"},"doc://com.easemob.chatroomuikit.demo/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MineGiftsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MineGiftsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MineGiftsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/initWithCoder:","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/initWithNibName:bundle:","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/MineGiftsViewController\/onGiftSendClick(item:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(cs)GiftsViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MineGiftsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"GiftsViewController","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftsViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController\/title","value":"MineGiftsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController\/fragments","value":[{"kind":"identifier","text":"MineGiftsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController~1onGiftSendClick(item:)\/title","value":"onGiftSendClickWithItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1MineGiftsViewController~1onGiftSendClick(item:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGiftSendClickWithItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}