{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/ocuicomponentsexampleviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/ocuicomponentsexampleviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH","doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/OCUIComponentsExampleViewController","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"title":"OCUIComponentsExampleViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)OCUIComponentsExampleViewController","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitChangeObservable":{"type":"unresolvable","title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"},"doc://com.easemob.chatroomuikit.demo/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment"},"doc://com.easemob.chatroomuikit.demo/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s8SendableP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/OCUIComponentsExampleViewController":{"role":"symbol","title":"OCUIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/OCUIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/ocuicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions"},"doc://com.easemob.chatroomuikit.demo/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OCUIComponentsExampleViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCUIComponentsExampleViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1OCUIComponentsExampleViewController\/title","value":"OCUIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1OCUIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"OCUIComponentsExampleViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}