{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents","doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject","doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP","doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP","doc:\/\/com.easemob.chatroomuikit.demo\/SQ","doc:\/\/com.easemob.chatroomuikit.demo\/SH","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/background","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/barrageList","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/bottomBar","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/carouselTextView","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/gift1","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/gift2","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/giftBarrages","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/inputBar","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/style"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/addCarouselTask()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/bottomBarDatas()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/startMessage(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchSpeakerIcon(sender:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchTheme(sender:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/ChatBottomFunctionBarActionEvents-Implementations","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/UIContextMenuInteractionDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"title":"UIComponentsExampleViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)UIComponentsExampleViewController","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/gift2":{"role":"symbol","title":"gift2","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gift2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewController","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftsViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/gift2","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/gift2"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIStateRestoring"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContentContainer"},"doc://com.easemob.chatroomuikit.demo/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/5UIKit23UITraitChangeObservableP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitEnvironment"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/switchSpeakerIcon(sender:)":{"role":"symbol","title":"switchSpeakerIcon(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchSpeakerIcon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchSpeakerIcon(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchSpeakerIconWithSender:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/switchspeakericon(sender:)"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIResponderStandardEditActions"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIAppearanceContainer"},"doc://com.easemob.chatroomuikit.demo/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate":{"type":"unresolvable","title":"GiftsViewActionEventsDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.easemob.chatroomuikit.demo/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SQ"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/carouselTextView":{"role":"symbol","title":"carouselTextView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"carouselTextView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HorizontalTextCarousel","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)HorizontalTextCarousel"}],"abstract":[{"type":"text","text":"Global notify container"}],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/carouselTextView","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/carouseltextview"},"doc://com.easemob.chatroomuikit.demo/@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents":{"type":"unresolvable","title":"ChatBottomFunctionBarActionEvents","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/bottomBarDatas()":{"role":"symbol","title":"bottomBarDatas()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarDatas"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"ChatBottomItemProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)ChatBottomItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Constructor of "},{"type":"codeVoice","code":"ChatBottomFunctionBar"},{"type":"text","text":" data source."}],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/bottomBarDatas()","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/bottombardatas()"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/barrageList":{"role":"symbol","title":"barrageList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barrageList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBarrageList","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatBarrageList"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/barrageList","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/barragelist"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIContextMenuInteractionDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContextMenuInteractionDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSObject"},"doc://com.easemob.chatroomuikit.demo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/SH"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/background":{"role":"symbol","title":"background","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/background","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/background"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/gift1":{"role":"symbol","title":"gift1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gift1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewController","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftsViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/gift1","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/gift1"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/style":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ThemeStyle"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/style","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/style"},"doc://com.easemob.chatroomuikit.demo/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s7CVarArgP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/initwithcoder:"},"doc://com.easemob.chatroomuikit.demo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s23CustomStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UITraitChangeObservable":{"type":"unresolvable","title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UITraitChangeObservable"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/inputBar":{"role":"symbol","title":"inputBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatInputBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatInputBar"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/inputBar","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/inputbar"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIFocusEnvironment"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/giftBarrages":{"role":"symbol","title":"giftBarrages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftBarrages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsBarrageList","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftsBarrageList"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/giftBarrages","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/giftbarrages"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/GiftsViewActionEventsDelegate-Implementations":{"role":"collectionGroup","title":"GiftsViewActionEventsDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/giftsviewactioneventsdelegate-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/viewdidload()"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/bottomBar":{"role":"symbol","title":"bottomBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBottomFunctionBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatBottomFunctionBar"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/bottomBar","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/bottombar"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSExtensionRequestHandling"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/switchTheme(sender:)":{"role":"symbol","title":"switchTheme(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchTheme(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithSender:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/switchtheme(sender:)"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController":{"role":"symbol","title":"UIComponentsExampleViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIComponentsExampleViewController"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/initwithnibname:bundle:"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIUserActivityRestoring"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/UIContextMenuInteractionDelegate-Implementations":{"role":"collectionGroup","title":"UIContextMenuInteractionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/UIContextMenuInteractionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/uicontextmenuinteractiondelegate-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/ChatBottomFunctionBarActionEvents-Implementations":{"role":"collectionGroup","title":"ChatBottomFunctionBarActionEvents Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/ChatBottomFunctionBarActionEvents-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/chatbottomfunctionbaractionevents-implementations"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/addCarouselTask()":{"role":"symbol","title":"addCarouselTask()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCarouselTask"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/addCarouselTask()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCarouselTask"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/addcarouseltask()"},"doc://com.easemob.chatroomuikit.demo/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"},"doc://com.easemob.chatroomuikit.demo/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)NSCoding"},"doc://com.easemob.chatroomuikit.demo/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.easemob.chatroomuikit.demo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/UIComponentsExampleViewController/startMessage(_:)":{"role":"symbol","title":"startMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/startMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startMessage:"}],"url":"\/documentation\/chatroomuikit_example\/uicomponentsexampleviewcontroller\/startmessage(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/addCarouselTask()","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/initWithCoder:","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/initWithNibName:bundle:","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/startMessage(_:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchSpeakerIcon(sender:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/switchTheme(sender:)","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/ChatBottomFunctionBarActionEvents-Implementations","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/GiftsViewActionEventsDelegate-Implementations","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/UIComponentsExampleViewController\/UIContextMenuInteractionDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)ChatBottomFunctionBarActionEvents","doc:\/\/com.easemob.chatroomuikit.demo\/@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","doc:\/\/com.easemob.chatroomuikit.demo\/objc(pl)UIContextMenuInteractionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIComponentsExampleViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1switchSpeakerIcon(sender:)\/title","value":"switchSpeakerIconWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1switchSpeakerIcon(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchSpeakerIconWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1switchTheme(sender:)\/title","value":"switchThemeWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1switchTheme(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/title","value":"UIComponentsExampleViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController\/fragments","value":[{"kind":"identifier","text":"UIComponentsExampleViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1addCarouselTask()\/title","value":"addCarouselTask"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1addCarouselTask()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCarouselTask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1startMessage(_:)\/title","value":"startMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1UIComponentsExampleViewController~1startMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}