{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEventResultChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora","text":"ChatError"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType","preciseIdentifier":"c:@M@ChatroomUIKit@E@RoomEventsType","text":"RoomEventsType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError"},{"type":"text","text":".If error is empty, it means success, otherwise it fails."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomeventslistener\/oneventresultchanged(error:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomeventslistener\/oneventresultchanged(error:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener\/onEventResultChanged(error:type:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a chat room event error is reported."},{"type":"text","text":" "},{"type":"text","text":"The current user receives the event."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onEventResultChangedWithError:type:"}],"role":"symbol","title":"onEventResultChanged(error:type:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEventResultChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsType","preciseIdentifier":"c:@M@ChatroomUIKit@E@RoomEventsType"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener(im)onEventResultChangedWithError:type:","required":true,"modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsListener":{"role":"symbol","title":"RoomEventsListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomEventsListener"}],"abstract":[{"type":"text","text":"The chat room event listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsListener"}],"url":"\/documentation\/chatroomuikit\/roomeventslistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/chatroomuikit\/chaterror"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsType":{"role":"symbol","title":"RoomEventsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomEventsType"}],"abstract":[{"type":"text","text":"All business service errors"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsType"}],"url":"\/documentation\/chatroomuikit\/roomeventstype"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsListener/onEventResultChanged(error:type:)":{"navigatorTitle":[{"kind":"identifier","text":"onEventResultChangedWithError:type:"}],"role":"symbol","title":"onEventResultChanged(error:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEventResultChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsType","preciseIdentifier":"c:@M@ChatroomUIKit@E@RoomEventsType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a chat room event error is reported."},{"type":"text","text":" "},{"type":"text","text":"The current user receives the event."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener\/onEventResultChanged(error:type:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/roomeventslistener\/oneventresultchanged(error:type:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onEventResultChangedWithError:type:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEventResultChangedWithError:type:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onEventResultChangedWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMError","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsType","preciseIdentifier":"c:@M@ChatroomUIKit@E@RoomEventsType","text":"RoomEventsType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener\/title","value":"RoomEventsListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener\/fragments","value":[{"kind":"identifier","text":"RoomEventsListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/title","value":"RoomEventsType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsType\/fragments","value":[{"kind":"identifier","text":"RoomEventsType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener~1onEventResultChanged(error:type:)\/title","value":"onEventResultChangedWithError:type:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener~1onEventResultChanged(error:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEventResultChangedWithError:type:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}