{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomContext","text":"ChatroomContext"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatroomcontext\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatroomcontext\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext\/shared","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomContext","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomContext"},{"kind":"text","text":"?"}],"title":"shared","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatroomContext(cpy)shared","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomContext":{"role":"symbol","title":"ChatroomContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatroomContext"}],"abstract":[{"type":"text","text":"A singleton class that represents the context of a chatroom. It contains information about the current user, the owner of the chatroom, the mute map, the room ID, and a dictionary of users in the chatroom."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatroomContext"}],"url":"\/documentation\/chatroomuikit\/chatroomcontext"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatroomContext/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatroomContext","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomContext"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/chatroomuikit\/chatroomcontext\/shared"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"shared"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatroomContext","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatroomContext","text":"ChatroomContext"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shared"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomContext\/title","value":"ChatroomContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomContext\/fragments","value":[{"kind":"identifier","text":"ChatroomContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomContext~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatroomContext~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}