{"variants":[{"paths":["\/documentation\/chatroomuikit\/chatbarragelist\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatbarragelist\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didEndDisplaying:forRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:heightForRowAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UITableViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/tableView(_:didSelectRowAt:)":{"role":"symbol","title":"tableView(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/tableview(_:didselectrowat:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList":{"role":"symbol","title":"ChatBarrageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBarrageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBarrageList"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/tableView(_:didEndDisplaying:forRowAt:)":{"role":"symbol","title":"tableView(_:didEndDisplaying:forRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didEndDisplaying:forRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didEndDisplayingCell:forRowAtIndexPath:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/tableview(_:didenddisplaying:forrowat:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/tableView(_:heightForRowAt:)":{"role":"symbol","title":"tableView(_:heightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:heightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/tableview(_:heightforrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didEndDisplaying:forRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/tableView(_:heightForRowAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList\/title","value":"ChatBarrageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList\/fragments","value":[{"kind":"identifier","text":"ChatBarrageList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:didEndDisplaying:forRowAt:)\/title","value":"tableView:didEndDisplayingCell:forRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:didEndDisplaying:forRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didEndDisplayingCell:forRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:heightForRowAt:)\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1tableView(_:heightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}