{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit_example\/chatbottomitem\/normalimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit_example\/chatbottomitem\/normalimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/normalImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ChatBottomItemProtocol.normalImage"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"normalImage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit_Example@objc(cs)ChatBottomItem(py)normalImage","modules":[{"name":"ChatroomUIKit_Example"}],"navigatorTitle":[{"kind":"identifier","text":"normalImage"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem"]]},"references":{"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example":{"role":"collection","title":"ChatroomUIKit_Example","abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit_example"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem":{"role":"symbol","title":"ChatBottomItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBottomItem"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBottomItem"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem"},"doc://com.easemob.chatroomuikit.demo/documentation/ChatroomUIKit_Example/ChatBottomItem/normalImage":{"role":"symbol","title":"normalImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.easemob.chatroomuikit.demo\/documentation\/ChatroomUIKit_Example\/ChatBottomItem\/normalImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"normalImage"}],"url":"\/documentation\/chatroomuikit_example\/chatbottomitem\/normalimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"normalImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"normalImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"normalImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/title","value":"ChatBottomItem"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem\/fragments","value":[{"kind":"identifier","text":"ChatBottomItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1normalImage\/title","value":"normalImage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.chatroomuikit.demo~1documentation~1ChatroomUIKit_Example~1ChatBottomItem~1normalImage\/fragments","value":[{"kind":"identifier","text":"normalImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}